"""
PDF helpers + 31 render_* functions for SafeTradie Document Library.
Split from docs_module.py for maintainability.

Each render_<doc_type>(doc: dict) -> str returns a full HTML string
that WeasyPrint converts to A4 PDF.
"""
from __future__ import annotations

from datetime import datetime, timezone
from typing import Any


STATE_REGULATORS = {
    "NSW": {"name": "SafeWork NSW", "phone": "13 10 50"},
    "VIC": {"name": "WorkSafe Victoria", "phone": "13 23 60"},
    "QLD": {"name": "Workplace Health and Safety QLD", "phone": "1300 362 128"},
    "WA": {"name": "WorkSafe WA", "phone": "1300 307 877"},
    "SA": {"name": "SafeWork SA", "phone": "1300 365 255"},
    "TAS": {"name": "WorkSafe Tasmania", "phone": "1300 366 322"},
    "NT": {"name": "NT WorkSafe", "phone": "1800 019 115"},
    "ACT": {"name": "WorkSafe ACT", "phone": "02 6207 3000"},
}



def _esc(s: Any) -> str:
    if s is None:
        return ""
    return (str(s).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"))


def _common_css() -> str:
    return """
    @page { size: A4; margin: 15mm 12mm 18mm 12mm;
            @bottom-center { content: attr(data-footer) " · Page " counter(page) " of " counter(pages);
                             font-family: Arial, sans-serif; font-size: 8pt; color: #666; } }
    body { font-family: Arial, sans-serif; color: #0a0a0a; font-size: 10pt; line-height: 1.45; }
    h1 { font-size: 22pt; font-weight: 900; letter-spacing: -0.02em; margin: 0; text-align: center; }
    h2 { font-size: 13pt; font-weight: 900; letter-spacing: -0.01em; margin: 18px 0 8px;
         padding-top: 8px; border-top: 2px solid #0a0a0a; }
    .sub { text-align: center; font-size: 12pt; color: #555; margin: 4px 0 18px; }
    .ref-line { text-align: center; font-size: 10pt; letter-spacing: 0.1em; color: #444; margin-bottom: 12px; }
    .legal { background: #fff7cc; border: 2px solid #0a0a0a; padding: 10px 14px; font-size: 9pt; margin: 16px 0; }
    .legal strong { display: block; font-size: 10pt; margin-bottom: 4px; }
    table { width: 100%; border-collapse: collapse; font-size: 9.5pt; }
    th, td { border: 1px solid #0a0a0a; padding: 6px 8px; vertical-align: top; }
    th { background: #0a0a0a; color: #ffcc00; text-transform: uppercase; font-size: 8.5pt; letter-spacing: 0.05em; }
    .kv td.k { width: 30%; background: #f6f6f6; font-weight: 700; }
    .emergency { background: #e0f2fe; border: 1px solid #075985; padding: 10px 14px; font-size: 9.5pt; }
    .footer-note { font-size: 8pt; color: #666; margin-top: 18px; font-style: italic;
                   border-top: 1px solid #ccc; padding-top: 8px; }
    ul { margin: 4px 0 4px 16px; padding: 0; }
    .ck { padding: 2px 0; font-size: 9.5pt; }
    .mono { font-family: monospace; font-size: 11pt; display: inline-block; width: 14px; }
    """


def _header(title: str, subtitle: str, ref: str, now_str: str) -> str:
    return f"""
    <h1>{_esc(title.upper())}</h1>
    <div class="sub">{_esc(subtitle)}</div>
    <div class="ref-line">{_esc(ref)} · Generated {now_str}</div>
    """


def _legal_box() -> str:
    return ("""<div class="legal"><strong>IMPORTANT</strong>"""
            "This document was generated by SafeTradie using AI assistance. It must be reviewed "
            "and tailored to your specific workplace before use. SafeTradie does not provide legal "
            "or professional advice. All documents must be reviewed by a qualified person. "
            "SafeTradie Pty Ltd accepts no liability for the accuracy or completeness of "
            "generated documents.</div>""")


def _footer_note(doc_type: str) -> str:
    return (f'<div class="footer-note">SafeTradie · {_esc(doc_type)} · This document must be '
            "reviewed and tailored on site before being relied upon for compliance purposes."
            "</div>")


# ---------- PDF renderers (per doc type) ----------

def _render_common(doc: dict, title: str, subtitle: str, body_html: str, footer: str) -> str:
    ref = _esc(doc.get("reference", "") or doc.get("doc_id", ""))
    now_str = datetime.now(timezone.utc).strftime("%d %b %Y")
    return f"""<!doctype html><html><head><meta charset="utf-8"><title>{_esc(title)}</title>
<style>{_common_css()}</style></head>
<body data-footer="{_esc(doc.get('company_name',''))} · {ref} · {footer}">
{_header(title, subtitle, ref, now_str)}
{_legal_box()}
{body_html}
{_footer_note(title)}
</body></html>"""


def _kv(items: list[tuple[str, Any]]) -> str:
    rows = "".join(
        f"<tr><td class='k'>{_esc(k)}</td><td>{_esc(v) if v is not None else '—'}</td></tr>"
        for k, v in items
    )
    return f'<table class="kv"><tbody>{rows}</tbody></table>'


def _section(title: str, inner: str) -> str:
    return f"<h2>{_esc(title)}</h2>{inner}"


# ========== JSA ==========
def render_jsa(doc: dict) -> str:
    steps = doc.get("steps") or []
    rows = ""
    for i, s in enumerate(steps):
        hz = "<ul>" + "".join(f"<li>{_esc(h)}</li>" for h in s.get('hazards', []) if h) + "</ul>"
        ctrl = "<ul>" + "".join(f"<li>{_esc(c)}</li>" for c in s.get('controls', []) if c) + "</ul>"
        rows += f"<tr><td>{i+1}. {_esc(s.get('step',''))}</td><td>{hz}</td><td>{ctrl}</td></tr>"
    body = (
        _section("Job details", _kv([
            ("Task", doc.get("task")), ("Site", doc.get("site")),
            ("Date", doc.get("work_date")), ("Prepared by", doc.get("prepared_by")),
            ("Workers", ", ".join(doc.get("worker_names", []) or [])),
        ]))
        + _section("Steps, Hazards and Controls",
                   f"<table><thead><tr><th>Step</th><th>Hazards</th><th>Controls</th></tr></thead>"
                   f"<tbody>{rows or '<tr><td colspan=3>—</td></tr>'}</tbody></table>")
        + _section("PPE Required", "<div>" + "".join(
            f'<div class="ck"><span class="mono">☒</span> {_esc(p)}</div>'
            for p in (doc.get("ppe") or [])) + "</div>")
        + _section("Note",
                   "<p style='font-size:9pt;color:#666;'>A JSA is NOT a substitute for a SWMS where "
                   "High Risk Construction Work is involved. Use SafeTradie's SWMS Generator for HRCW.</p>")
    )
    return _render_common(doc, "Job Safety Analysis", "Hazard identification for non-HRCW tasks",
                          body, "Job Safety Analysis")


# ========== Risk Assessment ==========
def render_risk_assessment(doc: dict) -> str:
    items = doc.get("items") or []
    rows = ""
    for i, it in enumerate(items):
        inh = (it.get("inherent_likelihood", 0)) * (it.get("inherent_consequence", 0))
        res = (it.get("residual_likelihood", 0)) * (it.get("residual_consequence", 0))
        rows += (f"<tr><td>{i+1}. {_esc(it.get('hazard',''))}</td>"
                 f"<td>{inh}<br><small>({it.get('inherent_likelihood','')}×{it.get('inherent_consequence','')})</small></td>"
                 f"<td>{_esc(it.get('controls',''))}</td>"
                 f"<td>{res}<br><small>({it.get('residual_likelihood','')}×{it.get('residual_consequence','')})</small></td>"
                 f"<td>{_esc(it.get('responsible',''))}</td></tr>")
    body = (
        _section("Activity details", _kv([
            ("Activity", doc.get("activity")), ("Site", doc.get("site")),
            ("Trade", doc.get("trade")), ("Prepared by", doc.get("prepared_by")),
            ("Review date", doc.get("review_date")),
        ]))
        + _section("Risk register",
                   "<table><thead><tr><th>Hazard</th><th>Inherent</th><th>Controls</th>"
                   "<th>Residual</th><th>Responsible</th></tr></thead>"
                   f"<tbody>{rows or '<tr><td colspan=5>—</td></tr>'}</tbody></table>")
    )
    return _render_common(doc, "Risk Assessment",
                          "Activity risk identification and controls",
                          body, "Risk Assessment")


# ========== SSSP ==========
def render_sssp(doc: dict) -> str:
    state = doc.get("site_state", "NSW")
    reg = STATE_REGULATORS.get(state, {"name": "", "phone": ""})
    body = (
        _section("Site details", _kv([
            ("Site name", doc.get("site_name")), ("Site address", doc.get("site_address")),
            ("Principal contractor", doc.get("principal_contractor")),
            ("Site supervisor", doc.get("site_supervisor")),
            ("Supervisor phone", doc.get("supervisor_phone")),
        ]))
        + _section("Emergency contacts",
                   f'<div class="emergency">'
                   f"<div><strong>Emergency:</strong> 000</div>"
                   f"<div><strong>State WHS regulator:</strong> {_esc(reg['name'])} — {_esc(reg['phone'])}</div>"
                   f"<div><strong>Nearest hospital:</strong> {_esc(doc.get('nearest_hospital',''))}</div>"
                   f"<div><strong>Assembly point:</strong> {_esc(doc.get('assembly_point',''))}</div>"
                   f"<div><strong>First aider on site:</strong> {_esc(doc.get('first_aider',''))}</div>"
                   f"</div>")
        + _section("Site-specific hazards",
                   "<ul>" + "".join(f"<li>{_esc(h)}</li>" for h in (doc.get("hazards") or [])) + "</ul>")
        + _section("Site rules",
                   "<ul>" + "".join(f"<li>{_esc(r)}</li>" for r in (doc.get("site_rules") or [])) + "</ul>")
        + _section("PPE requirements",
                   "<div>" + "".join(f'<div class="ck"><span class="mono">☒</span> {_esc(p)}</div>' for p in (doc.get("ppe") or [])) + "</div>")
        + _section("Induction requirements", f"<p>{_esc(doc.get('induction_requirements',''))}</p>")
    )
    return _render_common(doc, "Site-Specific Safety Plan",
                          "Single-page site safety summary",
                          body, "SSSP")


# ========== Emergency Plan ==========
def render_emergency_plan(doc: dict) -> str:
    state = doc.get("site_state", "NSW")
    reg = STATE_REGULATORS.get(state, {"name": "", "phone": ""})
    contacts = doc.get("emergency_contacts") or []
    contact_rows = "".join(
        f"<tr><td>{_esc(c.get('name',''))}</td><td>{_esc(c.get('role',''))}</td><td>{_esc(c.get('phone',''))}</td></tr>"
        for c in contacts)
    equip_rows = "".join(
        f"<tr><td>{_esc(e.get('equipment',''))}</td><td>{_esc(e.get('location',''))}</td></tr>"
        for e in (doc.get("emergency_equipment") or []))
    procs = doc.get("procedures") or {}
    proc_html = ""
    for label in ["fire", "medical", "chemical_spill", "electric_shock",
                  "fall_from_height", "structural_collapse", "flood"]:
        if procs.get(label):
            proc_html += f"<h3 style='font-size:11pt;font-weight:700'>{label.replace('_',' ').title()}</h3><p>{_esc(procs.get(label))}</p>"
    body = (
        _section("Site", _kv([("Site", doc.get("site_name")), ("Address", doc.get("site_address")),
                               ("Prepared by", doc.get("prepared_by")),
                               ("Assembly point", doc.get("assembly_point"))]))
        + _section("Emergency services",
                   f'<div class="emergency">'
                   f"<div><strong>Emergency:</strong> 000</div>"
                   f"<div><strong>State WHS regulator:</strong> {_esc(reg['name'])} — {_esc(reg['phone'])}</div>"
                   f"<div><strong>Nearest hospital:</strong> {_esc(doc.get('nearest_hospital',''))}</div>"
                   f"</div>")
        + _section("Internal emergency contacts",
                   f"<table><thead><tr><th>Name</th><th>Role</th><th>Phone</th></tr></thead>"
                   f"<tbody>{contact_rows or '<tr><td colspan=3>—</td></tr>'}</tbody></table>")
        + _section("Evacuation procedure", f"<p>{_esc(doc.get('evacuation_procedure',''))}</p>")
        + _section("Emergency equipment",
                   f"<table><thead><tr><th>Equipment</th><th>Location</th></tr></thead>"
                   f"<tbody>{equip_rows or '<tr><td colspan=2>—</td></tr>'}</tbody></table>")
        + (_section("Specific emergency procedures", proc_html) if proc_html else "")
    )
    return _render_common(doc, "Emergency Plan",
                          "Emergency response procedures (WHS Reg 43)",
                          body, "Emergency Plan")


# ========== Hazardous Chemicals Register ==========
def render_haz_chemicals(doc: dict) -> str:
    items = doc.get("chemicals") or []
    rows = "".join(
        f"<tr><td>{_esc(c.get('product',''))}</td>"
        f"<td>{_esc(c.get('manufacturer',''))}</td>"
        f"<td>{_esc(c.get('sds_date',''))}</td>"
        f"<td>{_esc(c.get('hazard_class',''))}</td>"
        f"<td>{_esc(c.get('location',''))}</td>"
        f"<td>{_esc(c.get('max_quantity',''))}</td>"
        f"<td>{_esc(c.get('ppe',''))}</td></tr>" for c in items)
    body = (
        _section("Business details", _kv([
            ("Business name", doc.get("company_name")),
            ("Site/location", doc.get("site_location")),
            ("Register compiled by", doc.get("prepared_by")),
            ("Review date", doc.get("review_date")),
        ]))
        + _section("Hazardous chemicals",
                   "<table><thead><tr>"
                   "<th>Product</th><th>Manufacturer</th><th>SDS date</th>"
                   "<th>Hazard class</th><th>Location</th><th>Max qty</th><th>PPE</th>"
                   "</tr></thead>"
                   f"<tbody>{rows or '<tr><td colspan=7>—</td></tr>'}</tbody></table>")
        + _section("Note",
                   "<p style='font-size:9pt;'>SDSs must be kept accessible for all chemicals in this "
                   "register (WHS Reg 344). Review when any new chemical is introduced or SDS updates.</p>")
    )
    return _render_common(doc, "Hazardous Chemicals Register",
                          "WHS Regulations Reg 346",
                          body, "Haz Chemicals Register")


# ========== Site Induction Checklist ==========
def render_site_induction(doc: dict) -> str:
    items = doc.get("checklist") or []
    li = "".join(
        f'<div class="ck"><span class="mono">{"☒" if c.get("done") else "☐"}</span> {_esc(c.get("item",""))}</div>'
        for c in items)
    sig = doc.get("signed_at", "") and f'<img src="{_esc(doc.get("signature_data",""))}" style="max-height:40px"/>' if (doc.get("signature_data") or "").startswith("data:image") else _esc(doc.get("signature_data", ""))
    body = (
        _section("Induction", _kv([
            ("Worker", doc.get("worker_name")),
            ("Trade/Role", doc.get("worker_role")),
            ("Site", doc.get("site_name")),
            ("Inducted by", doc.get("inducted_by")),
            ("Date", doc.get("induction_date")),
        ]))
        + _section("Checklist", f"<div>{li or '—'}</div>")
        + _section("Sign-off",
                   f"<p>Worker: {_esc(doc.get('worker_name',''))}<br>"
                   f"Signature: {sig or '_______________________'}<br>"
                   f"Date: {_esc((doc.get('signed_at') or '')[:10]) or '___/___/______'}</p>")
    )
    return _render_common(doc, "Site Induction Checklist",
                          "WHS Regulations Reg 316-317",
                          body, "Site Induction")


# ========== Confined Space Entry Permit ==========
def render_confined_space(doc: dict) -> str:
    atmos = doc.get("atmosphere") or {}
    body = (
        _section("Space identification", _kv([
            ("Space name/ID", doc.get("space_id")),
            ("Location", doc.get("location")),
            ("Nature of work", doc.get("work_description")),
            ("Date/time of entry", doc.get("entry_datetime")),
            ("Duration of permit", doc.get("duration")),
        ]))
        + _section("Authorised workers", "<ul>" + "".join(f"<li>{_esc(w)}</li>" for w in (doc.get("authorised_workers") or [])) + "</ul>")
        + _section("Atmospheric testing",
                   _kv([("Oxygen %", atmos.get("oxygen")),
                        ("LEL %", atmos.get("lel")),
                        ("Toxic gases (ppm)", atmos.get("toxic_gases")),
                        ("Tested by", atmos.get("tested_by")),
                        ("Test time", atmos.get("tested_at"))]))
        + _section("Entry controls", "<ul>" + "".join(f"<li>{_esc(c)}</li>" for c in (doc.get("entry_controls") or [])) + "</ul>")
        + _section("Standby person + communication", _kv([
            ("Standby person", doc.get("standby_person")),
            ("Communication method", doc.get("communication")),
        ]))
        + _section("Emergency procedures", f"<p>{_esc(doc.get('emergency_procedures',''))}</p>")
        + _section("Authorisation", _kv([
            ("Authorised by", doc.get("authorised_by")),
            ("Signature/ID", doc.get("authorised_by_signature")),
            ("Authorised date/time", doc.get("authorised_at")),
            ("Permit rescinded", doc.get("rescinded_at")),
        ]))
    )
    return _render_common(doc, "Confined Space Entry Permit",
                          "WHS Regulations Reg 66-77",
                          body, "Confined Space Permit")


# ========== Toolbox Talk Record ==========
def render_toolbox_record(doc: dict) -> str:
    attendees = doc.get("attendees") or []
    att_rows = "".join(
        f"<tr><td>{_esc(a.get('name',''))}</td><td>_______________________</td><td>___/___/______</td></tr>"
        for a in attendees)
    body = (
        _section("Talk details", _kv([
            ("Topic", doc.get("topic")), ("Site", doc.get("site")),
            ("Date", doc.get("talk_date")), ("Conducted by", doc.get("conducted_by")),
            ("Duration (mins)", doc.get("duration_mins")),
        ]))
        + _section("Key points",
                   "<ul>" + "".join(f"<li>{_esc(k)}</li>" for k in (doc.get("key_points") or [])) + "</ul>")
        + _section("Worker questions / discussion",
                   f"<p>{_esc(doc.get('discussion','') or '—')}</p>")
        + _section("Attendees",
                   "<table><thead><tr><th>Name</th><th>Signature</th><th>Date</th></tr></thead>"
                   f"<tbody>{att_rows or '<tr><td colspan=3>—</td></tr>'}</tbody></table>")
    )
    return _render_common(doc, "Toolbox Talk Record",
                          "Pre-start safety briefing",
                          body, "Toolbox Talk Record")


# ========== WHS Management Plan ==========
def render_whs_mgmt_plan(doc: dict) -> str:
    state = doc.get("site_state", "NSW")
    reg = STATE_REGULATORS.get(state, {"name": "", "phone": ""})
    personnel = doc.get("key_personnel") or []
    p_rows = "".join(
        f"<tr><td>{_esc(p.get('name',''))}</td><td>{_esc(p.get('role',''))}</td><td>{_esc(p.get('phone',''))}</td></tr>"
        for p in personnel)
    resp = doc.get("responsibilities") or []
    r_rows = "".join(
        f"<tr><td>{_esc(r.get('role',''))}</td><td>{_esc(r.get('responsibility',''))}</td></tr>"
        for r in resp)
    body = (
        _section("Project details", _kv([
            ("Project", doc.get("project_name")),
            ("Principal contractor", doc.get("principal_contractor")),
            ("Site address", doc.get("site_address")),
            ("State", state),
            ("Project value", doc.get("project_value")),
            ("Project duration", doc.get("project_duration")),
            ("Prepared by", doc.get("prepared_by")),
            ("Review date", doc.get("review_date")),
        ]))
        + _section("Scope of work", f"<p>{_esc(doc.get('scope_of_work',''))}</p>")
        + _section("Regulator", f'<div class="emergency">'
                   f"<div><strong>State WHS regulator:</strong> {_esc(reg['name'])} — {_esc(reg['phone'])}</div>"
                   f"<div><strong>Emergency:</strong> 000</div></div>")
        + _section("Key personnel",
                   "<table><thead><tr><th>Name</th><th>Role</th><th>Phone</th></tr></thead>"
                   f"<tbody>{p_rows or '<tr><td colspan=3>—</td></tr>'}</tbody></table>")
        + _section("WHS responsibilities",
                   "<table><thead><tr><th>Role</th><th>Responsibility</th></tr></thead>"
                   f"<tbody>{r_rows or '<tr><td colspan=2>—</td></tr>'}</tbody></table>")
        + _section("Risk management approach", f"<p>{_esc(doc.get('risk_management_approach',''))}</p>")
        + _section("Consultation arrangements", f"<p>{_esc(doc.get('consultation_arrangements',''))}</p>")
        + _section("Training requirements",
                   "<ul>" + "".join(f"<li>{_esc(t)}</li>" for t in (doc.get("training_requirements") or [])) + "</ul>")
        + _section("Monitoring & review", f"<p>{_esc(doc.get('monitoring_review',''))}</p>")
    )
    return _render_common(doc, "WHS Management Plan",
                          "Principal Contractor WHS plan (WHS Reg 309)",
                          body, "WHS Management Plan")


# ========== Asbestos Register ==========
def render_asbestos_register(doc: dict) -> str:
    items = doc.get("items") or []
    rows = "".join(
        f"<tr><td>{_esc(a.get('location',''))}</td>"
        f"<td>{_esc(a.get('material',''))}</td>"
        f"<td>{_esc(a.get('friable',''))}</td>"
        f"<td>{_esc(a.get('condition',''))}</td>"
        f"<td>{_esc(a.get('risk',''))}</td>"
        f"<td>{_esc(a.get('control',''))}</td>"
        f"<td>{_esc(a.get('accessible',''))}</td></tr>" for a in items)
    body = (
        _section("Site details", _kv([
            ("Site", doc.get("site_name")),
            ("Address", doc.get("site_address")),
            ("Prepared by", doc.get("prepared_by")),
            ("Assessor name", doc.get("assessor_name")),
            ("Inspection date", doc.get("inspection_date")),
            ("Next review", doc.get("next_review")),
        ]))
        + _section("Asbestos-containing materials",
                   "<table><thead><tr>"
                   "<th>Location</th><th>Material</th><th>Friable</th>"
                   "<th>Condition</th><th>Risk</th><th>Control</th><th>Accessible</th>"
                   "</tr></thead>"
                   f"<tbody>{rows or '<tr><td colspan=7>—</td></tr>'}</tbody></table>")
        + _section("Note",
                   "<p style='font-size:9pt;'>Required under WHS Regulations Reg 425 for any "
                   "workplace where asbestos or ACM is identified or presumed. Keep current; "
                   "reviewed at least every 5 years, or when asbestos is removed, disturbed, "
                   "sealed or enclosed.</p>")
    )
    return _render_common(doc, "Asbestos Register",
                          "WHS Regulations Reg 425",
                          body, "Asbestos Register")


# ========== CCEW (NSW Electrical Certificate) ==========
def render_ccew(doc: dict) -> str:
    tested = doc.get("test_results") or []
    t_rows = "".join(
        f"<tr><td>{_esc(t.get('test',''))}</td><td>{_esc(t.get('result',''))}</td></tr>"
        for t in tested)
    body = (
        _section("Licensee details", _kv([
            ("Licensee name", doc.get("licensee_name")),
            ("Licence number", doc.get("licence_no")),
            ("Contractor", doc.get("contractor_name")),
        ]))
        + _section("Customer & site", _kv([
            ("Customer", doc.get("customer_name")),
            ("Site address", doc.get("site_address")),
            ("Work type", doc.get("work_type")),
            ("Installation type", doc.get("installation_type")),
            ("Work date", doc.get("work_date")),
        ]))
        + _section("Scope of work", f"<p>{_esc(doc.get('scope',''))}</p>")
        + _section("Tested items",
                   "<ul>" + "".join(f"<li>{_esc(t)}</li>" for t in (doc.get("tested_items") or [])) + "</ul>")
        + _section("Test results",
                   "<table><thead><tr><th>Test</th><th>Result</th></tr></thead>"
                   f"<tbody>{t_rows or '<tr><td colspan=2>—</td></tr>'}</tbody></table>")
        + _section("Compliance statement",
                   f"<p>{_esc(doc.get('compliance_statement','') or 'I certify that the electrical installation work described above complies with AS/NZS 3000 and the Service and Installation Rules of NSW.')}</p>")
        + _section("Sign-off", _kv([
            ("Signed by", doc.get("signed_by")),
            ("Signature/ID", doc.get("signature")),
            ("Signed at", doc.get("signed_at")),
        ]))
    )
    return _render_common(doc, "Certificate of Compliance — Electrical Work (CCEW)",
                          "NSW — AS/NZS 3000",
                          body, "CCEW")


# ========== NOW/COC Plumbing ==========
def render_plumbing_coc(doc: dict) -> str:
    items = doc.get("work_items") or []
    rows = "".join(
        f"<tr><td>{_esc(it.get('item',''))}</td><td>{_esc(it.get('standard',''))}</td>"
        f"<td>{_esc(it.get('result',''))}</td></tr>" for it in items)
    body = (
        _section("Licensee details", _kv([
            ("Licensee name", doc.get("licensee_name")),
            ("Licence number", doc.get("licence_no")),
            ("Company", doc.get("company_name")),
        ]))
        + _section("Job details", _kv([
            ("Job site", doc.get("job_site")),
            ("Job type", doc.get("job_type")),
            ("Council / authority", doc.get("authority")),
            ("Inspection required", doc.get("inspection_required")),
            ("Work date", doc.get("work_date")),
            ("NOW reference", doc.get("now_reference")),
        ]))
        + _section("Scope of work", f"<p>{_esc(doc.get('scope',''))}</p>")
        + _section("Work items + standards",
                   "<table><thead><tr><th>Item</th><th>Standard</th><th>Result</th></tr></thead>"
                   f"<tbody>{rows or '<tr><td colspan=3>—</td></tr>'}</tbody></table>")
        + _section("Compliance statement",
                   f"<p>{_esc(doc.get('compliance_statement','') or 'I certify that the plumbing/drainage work described above complies with AS/NZS 3500 and relevant state regulations.')}</p>")
        + _section("Sign-off", _kv([
            ("Signed by", doc.get("signed_by")),
            ("Signature/ID", doc.get("signature")),
            ("Signed at", doc.get("signed_at")),
        ]))
    )
    return _render_common(doc, "Plumbing NOW / Certificate of Compliance",
                          "AS/NZS 3500 — State plumbing regulations",
                          body, "Plumbing COC")


# ========== Hot Work Permit ==========
def render_hot_work_permit(doc: dict) -> str:
    checks = doc.get("precautions") or []
    li = "".join(
        f'<div class="ck"><span class="mono">{"☒" if c.get("done") else "☐"}</span> {_esc(c.get("item",""))}</div>'
        for c in checks)
    body = (
        _section("Permit details", _kv([
            ("Location", doc.get("location")),
            ("Nature of work", doc.get("work_description")),
            ("Date/time of start", doc.get("start_datetime")),
            ("Duration", doc.get("duration")),
            ("Rescinded at", doc.get("rescinded_at")),
        ]))
        + _section("Workers + fire watch", _kv([
            ("Authorised workers", ", ".join(doc.get("authorised_workers", []) or [])),
            ("Fire watch person", doc.get("fire_watch_person")),
            ("Extinguisher on site", doc.get("extinguisher_on_site")),
            ("Post-work watch (min)", doc.get("post_work_watch_mins")),
        ]))
        + _section("Pre-start precautions", f"<div>{li or '—'}</div>")
        + _section("Atmosphere tested",
                   _kv([("Tested", doc.get("atmosphere_tested")),
                        ("Tested by", doc.get("atmosphere_tested_by")),
                        ("Test time", doc.get("atmosphere_tested_at"))]))
        + _section("Emergency procedures", f"<p>{_esc(doc.get('emergency_procedures',''))}</p>")
        + _section("Authorisation", _kv([
            ("Authorised by", doc.get("authorised_by")),
            ("Signature/ID", doc.get("authorised_by_signature")),
            ("Authorised at", doc.get("authorised_at")),
        ]))
    )
    return _render_common(doc, "Hot Work Permit",
                          "Welding, cutting, grinding — fire risk control",
                          body, "Hot Work Permit")


# ========== Excavation Permit ==========
def render_excavation_permit(doc: dict) -> str:
    services = doc.get("services_checked") or []
    li = "".join(
        f'<div class="ck"><span class="mono">{"☒" if c.get("done") else "☐"}</span> {_esc(c.get("item",""))}</div>'
        for c in services)
    body = (
        _section("Permit details", _kv([
            ("Location", doc.get("location")),
            ("Nature of work", doc.get("work_description")),
            ("Depth (metres)", doc.get("depth_metres")),
            ("Start date/time", doc.get("start_datetime")),
            ("Duration", doc.get("duration")),
        ]))
        + _section("Services check (Dial Before You Dig)", f"<div>{li or '—'}</div>")
        + _section("Barricades & signage",
                   "<ul>" + "".join(f"<li>{_esc(b)}</li>" for b in (doc.get("barricades") or [])) + "</ul>")
        + _section("Spoil location", f"<p>{_esc(doc.get('spoil_location',''))}</p>")
        + _section("Plant & equipment",
                   "<ul>" + "".join(f"<li>{_esc(p)}</li>" for p in (doc.get("plant_equipment") or [])) + "</ul>")
        + _section("Authorised workers",
                   "<ul>" + "".join(f"<li>{_esc(w)}</li>" for w in (doc.get("authorised_workers") or [])) + "</ul>")
        + _section("Emergency procedures", f"<p>{_esc(doc.get('emergency_procedures',''))}</p>")
        + _section("Authorisation", _kv([
            ("Authorised by", doc.get("authorised_by")),
            ("Signature/ID", doc.get("authorised_by_signature")),
            ("Authorised at", doc.get("authorised_at")),
            ("Permit rescinded", doc.get("rescinded_at")),
        ]))
    )
    return _render_common(doc, "Excavation Permit",
                          "Ground disturbance control (WHS Reg 304)",
                          body, "Excavation Permit")


# ========== Lift Plan ==========
def render_lift_plan(doc: dict) -> str:
    body = (
        _section("Lift details", _kv([
            ("Site", doc.get("site")),
            ("Lift date", doc.get("lift_date")),
            ("Load description", doc.get("load_description")),
            ("Load weight (kg)", doc.get("load_weight_kg")),
            ("Working radius (m)", doc.get("working_radius")),
            ("Lift height (m)", doc.get("lift_height")),
        ]))
        + _section("Crane & rigging", _kv([
            ("Crane type", doc.get("crane_type")),
            ("Crane capacity (kg)", doc.get("crane_capacity_kg")),
            ("Capacity utilised (%)", doc.get("capacity_utilised")),
            ("Rigging configuration", doc.get("rigging_config")),
            ("Dogger name", doc.get("dogger_name")),
            ("Rigger name", doc.get("rigger_name")),
            ("Crane operator", doc.get("crane_operator")),
        ]))
        + _section("Lift sequence", f"<p>{_esc(doc.get('lift_sequence',''))}</p>")
        + _section("Hazards",
                   "<ul>" + "".join(f"<li>{_esc(h)}</li>" for h in (doc.get("hazards") or [])) + "</ul>")
        + _section("Controls",
                   "<ul>" + "".join(f"<li>{_esc(c)}</li>" for c in (doc.get("controls") or [])) + "</ul>")
        + _section("Exclusion zone", f"<p>{_esc(doc.get('exclusion_zone',''))}</p>")
        + _section("Authorisation", _kv([
            ("Prepared by", doc.get("prepared_by")),
            ("Approved by", doc.get("approved_by")),
            ("Approved at", doc.get("approved_at")),
        ]))
    )
    return _render_common(doc, "Lift Plan",
                          "Crane / lifting operations — AS 2550",
                          body, "Lift Plan")


# ========== Fall Protection Plan ==========
def render_fall_protection(doc: dict) -> str:
    checks = doc.get("pre_start_check") or []
    li = "".join(
        f'<div class="ck"><span class="mono">{"☒" if c.get("done") else "☐"}</span> {_esc(c.get("item",""))}</div>'
        for c in checks)
    body = (
        _section("Work details", _kv([
            ("Site", doc.get("site")),
            ("Work area", doc.get("work_area")),
            ("Height (metres)", doc.get("height_metres")),
            ("Work date", doc.get("work_date")),
        ]))
        + _section("Nature of work", f"<p>{_esc(doc.get('work_description',''))}</p>")
        + _section("Edge protection",
                   "<ul>" + "".join(f"<li>{_esc(e)}</li>" for e in (doc.get("edge_protection") or [])) + "</ul>")
        + _section("Fall arrest systems",
                   "<ul>" + "".join(f"<li>{_esc(f)}</li>" for f in (doc.get("fall_arrest_systems") or [])) + "</ul>")
        + _section("Anchor points", f"<p>{_esc(doc.get('anchor_points',''))}</p>")
        + _section("Rescue plan", f"<p>{_esc(doc.get('rescue_plan',''))}</p>")
        + _section("Authorised workers",
                   "<ul>" + "".join(f"<li>{_esc(w)}</li>" for w in (doc.get("authorised_workers") or [])) + "</ul>")
        + _section("Pre-start check", f"<div>{li or '—'}</div>")
        + _section("Sign-off", _kv([
            ("Prepared by", doc.get("prepared_by")),
            ("Approved by", doc.get("approved_by")),
            ("Approved at", doc.get("approved_at")),
        ]))
    )
    return _render_common(doc, "Fall Protection Plan",
                          "Working at heights (WHS Reg 78)",
                          body, "Fall Protection Plan")


# ---------- Phase 3 — remaining 15 specialty doc renderers ----------

def _ul(items: list) -> str:
    return "<ul>" + "".join(f"<li>{_esc(i)}</li>" for i in (items or [])) + "</ul>"


def _check_list(items: list) -> str:
    return "<div>" + "".join(
        f'<div class="ck"><span class="mono">{"☒" if c.get("done") else "☐"}</span> {_esc(c.get("item",""))}</div>'
        for c in (items or [])) + "</div>"


def _table_rows(items: list, cols: list[str]) -> str:
    return "".join(
        "<tr>" + "".join(f"<td>{_esc(it.get(c,''))}</td>" for c in cols) + "</tr>"
        for it in (items or []))


def _table_head(cols: list[tuple]) -> str:
    return "<thead><tr>" + "".join(f"<th>{_esc(l)}</th>" for _k, l in cols) + "</tr></thead>"


def _tbl(items: list, cols: list[tuple]) -> str:
    keys = [k for k, _l in cols]
    rows = _table_rows(items, keys) or f"<tr><td colspan={len(cols)}>—</td></tr>"
    return f"<table>{_table_head(cols)}<tbody>{rows}</tbody></table>"


# ========== Gas Compliance Certificate ==========
def render_gas_compliance(doc: dict) -> str:
    body = (
        _section("Licensee details", _kv([
            ("Licensee name", doc.get("licensee_name")),
            ("Licence number", doc.get("licence_no")),
            ("Company", doc.get("company_name")),
        ]))
        + _section("Installation details", _kv([
            ("Customer", doc.get("customer_name")),
            ("Site address", doc.get("site_address")),
            ("Gas type", doc.get("gas_type")),
            ("Appliance type", doc.get("appliance_type")),
            ("Appliance model / serial", doc.get("appliance_model")),
            ("Work date", doc.get("work_date")),
        ]))
        + _section("Scope of work", f"<p>{_esc(doc.get('scope',''))}</p>")
        + _section("Tests performed",
                   _tbl(doc.get("tests") or [], [("test", "Test"), ("result", "Result")]))
        + _section("Compliance statement",
                   f"<p>{_esc(doc.get('compliance_statement','') or 'I certify this gas installation complies with AS/NZS 5601 and applicable state gas regulations.')}</p>")
        + _section("Sign-off", _kv([
            ("Signed by", doc.get("signed_by")),
            ("Signature/ID", doc.get("signature")),
            ("Signed at", doc.get("signed_at")),
        ]))
    )
    return _render_common(doc, "Gas Compliance Certificate",
                          "AS/NZS 5601 — State gas regulations", body, "Gas Compliance")


# ========== Pressure Test Record ==========
def render_pressure_test(doc: dict) -> str:
    body = (
        _section("Project details", _kv([
            ("Project / site", doc.get("project")),
            ("Client", doc.get("client")),
            ("System tested", doc.get("system_tested")),
            ("Test standard", doc.get("test_standard")),
            ("Pipe material / size", doc.get("pipe_material")),
            ("Test date", doc.get("test_date")),
        ]))
        + _section("Test parameters", _kv([
            ("Test medium (air/water/gas)", doc.get("test_medium")),
            ("Test pressure (kPa)", doc.get("test_pressure_kpa")),
            ("Hold duration (mins)", doc.get("hold_mins")),
            ("Start pressure (kPa)", doc.get("start_pressure")),
            ("End pressure (kPa)", doc.get("end_pressure")),
            ("Ambient temp (°C)", doc.get("ambient_temp")),
            ("Result", doc.get("result")),
        ]))
        + _section("Observations", f"<p>{_esc(doc.get('observations',''))}</p>")
        + _section("Sign-off", _kv([
            ("Tested by", doc.get("tested_by")),
            ("Licence / accreditation", doc.get("tester_licence")),
            ("Signature", doc.get("signature")),
            ("Signed at", doc.get("signed_at")),
        ]))
    )
    return _render_common(doc, "Pressure Test Record",
                          "AS/NZS 3500 · AS 4041 · AS/NZS 2885", body, "Pressure Test")


# ========== Backflow Test Report ==========
def render_backflow_test(doc: dict) -> str:
    body = (
        _section("Site details", _kv([
            ("Site / customer", doc.get("site")),
            ("Site address", doc.get("site_address")),
            ("Hazard rating", doc.get("hazard_rating")),
            ("Device type", doc.get("device_type")),
            ("Device make / model", doc.get("device_model")),
            ("Device serial", doc.get("device_serial")),
            ("Install location", doc.get("install_location")),
            ("Test date", doc.get("test_date")),
        ]))
        + _section("Test results",
                   _tbl(doc.get("tests") or [],
                        [("test", "Test"), ("required", "Required"),
                         ("actual", "Actual"), ("result", "Pass/Fail")]))
        + _section("Overall result", _kv([
            ("Test kit make / model", doc.get("kit_model")),
            ("Test kit calibration date", doc.get("kit_calibration")),
            ("Next test due", doc.get("next_test_due")),
            ("Overall result", doc.get("overall_result")),
        ]))
        + _section("Tester sign-off", _kv([
            ("Tester name", doc.get("tester_name")),
            ("Licence number", doc.get("tester_licence")),
            ("Signature", doc.get("signature")),
            ("Signed at", doc.get("signed_at")),
        ]))
    )
    return _render_common(doc, "Backflow Prevention Device Test Report",
                          "AS/NZS 2845.3 · Annual device testing", body, "Backflow Test")


# ========== Traffic Management Plan (TMP) ==========
def render_tmp(doc: dict) -> str:
    body = (
        _section("Project details", _kv([
            ("Project", doc.get("project_name")),
            ("Site address", doc.get("site_address")),
            ("Controlling authority / council", doc.get("authority")),
            ("Road classification", doc.get("road_class")),
            ("Speed zone (km/h)", doc.get("speed_zone")),
            ("Work hours", doc.get("work_hours")),
            ("Start date", doc.get("start_date")),
            ("End date", doc.get("end_date")),
        ]))
        + _section("Scope of work", f"<p>{_esc(doc.get('scope',''))}</p>")
        + _section("Traffic controls",
                   _ul(doc.get("traffic_controls") or []))
        + _section("Signage & devices",
                   _tbl(doc.get("signage") or [],
                        [("device", "Device / sign"), ("location", "Location"),
                         ("qty", "Qty")]))
        + _section("Pedestrian management",
                   f"<p>{_esc(doc.get('pedestrian_management',''))}</p>")
        + _section("Emergency access", f"<p>{_esc(doc.get('emergency_access',''))}</p>")
        + _section("Sign-off", _kv([
            ("TMP designer (RIIWHS302D / equivalent)", doc.get("designer_name")),
            ("Ticket number", doc.get("designer_ticket")),
            ("Approved by", doc.get("approved_by")),
            ("Approved at", doc.get("approved_at")),
        ]))
    )
    return _render_common(doc, "Traffic Management Plan",
                          "AS 1742.3 · State TMP guidelines", body, "Traffic Mgmt Plan")


# ========== Plant/Equipment Pre-Start ==========
def render_plant_prestart(doc: dict) -> str:
    body = (
        _section("Plant details", _kv([
            ("Plant / equipment", doc.get("plant_name")),
            ("Serial / plant number", doc.get("plant_serial")),
            ("Operator", doc.get("operator_name")),
            ("Operator ticket / HR licence", doc.get("operator_licence")),
            ("Hours / km start", doc.get("hours_start")),
            ("Site", doc.get("site")),
            ("Check date", doc.get("check_date")),
        ]))
        + _section("Pre-start checks", _check_list(doc.get("checks") or []))
        + _section("Defects identified", _ul(doc.get("defects") or []))
        + _section("Corrective action", f"<p>{_esc(doc.get('corrective_action',''))}</p>")
        + _section("Fit for use?", _kv([
            ("Operator declaration", doc.get("fit_declaration")),
            ("Supervisor sign-off", doc.get("supervisor_signature")),
            ("Signed at", doc.get("signed_at")),
        ]))
    )
    return _render_common(doc, "Plant / Equipment Pre-Start Check",
                          "WHS Reg 213 · Daily plant inspection", body, "Plant Pre-Start")


# ========== Scaffold Handover Certificate ==========
def render_scaffold_handover(doc: dict) -> str:
    body = (
        _section("Project details", _kv([
            ("Project", doc.get("project")),
            ("Site address", doc.get("site_address")),
            ("Principal contractor", doc.get("principal_contractor")),
            ("Scaffold type", doc.get("scaffold_type")),
            ("Max SWL (kg/m²)", doc.get("max_swl")),
            ("Load class", doc.get("load_class")),
            ("Scaffold height (m)", doc.get("height")),
        ]))
        + _section("Erected by", _kv([
            ("Scaffolder name", doc.get("scaffolder_name")),
            ("Ticket class (basic/int/adv)", doc.get("scaffolder_ticket")),
            ("Ticket number", doc.get("scaffolder_ticket_no")),
            ("Company", doc.get("scaffold_company")),
            ("Date erected", doc.get("erected_date")),
        ]))
        + _section("Inspection checklist", _check_list(doc.get("inspection_checks") or []))
        + _section("Defects / restrictions", _ul(doc.get("restrictions") or []))
        + _section("Handover", _kv([
            ("Handed to (PC/Builder rep)", doc.get("handed_to")),
            ("Signed (scaffolder)", doc.get("scaffolder_signature")),
            ("Signed (recipient)", doc.get("recipient_signature")),
            ("Next inspection due", doc.get("next_inspection")),
        ]))
    )
    return _render_common(doc, "Scaffold Handover Certificate",
                          "AS/NZS 4576 · AS/NZS 1576", body, "Scaffold Handover")


# ========== Working at Heights Permit ==========
def render_heights_permit(doc: dict) -> str:
    body = (
        _section("Permit details", _kv([
            ("Location", doc.get("location")),
            ("Nature of work", doc.get("work_description")),
            ("Height above ground (m)", doc.get("height_metres")),
            ("Start date/time", doc.get("start_datetime")),
            ("Duration", doc.get("duration")),
        ]))
        + _section("Authorised workers", _ul(doc.get("authorised_workers") or []))
        + _section("Access method", f"<p>{_esc(doc.get('access_method',''))}</p>")
        + _section("Fall prevention (first) / arrest (second) controls",
                   _ul(doc.get("controls") or []))
        + _section("Rescue plan", f"<p>{_esc(doc.get('rescue_plan',''))}</p>")
        + _section("Pre-start check", _check_list(doc.get("pre_start_check") or []))
        + _section("Authorisation", _kv([
            ("Authorised by", doc.get("authorised_by")),
            ("Signature/ID", doc.get("authorised_by_signature")),
            ("Authorised at", doc.get("authorised_at")),
            ("Rescinded at", doc.get("rescinded_at")),
        ]))
    )
    return _render_common(doc, "Working at Heights Permit",
                          "WHS Reg 78 · Hierarchy of control", body, "Working at Heights Permit")


# ========== Lock-Out / Tag-Out (LOTO) ==========
def render_loto(doc: dict) -> str:
    body = (
        _section("Isolation details", _kv([
            ("Plant / system", doc.get("system")),
            ("Location", doc.get("location")),
            ("Nature of work", doc.get("work_description")),
            ("Energy sources (all types)", doc.get("energy_sources")),
            ("Start date/time", doc.get("start_datetime")),
        ]))
        + _section("Isolation points",
                   _tbl(doc.get("isolation_points") or [],
                        [("point", "Point / ID"), ("type", "Energy type"),
                         ("device", "Lock/tag ID"), ("verified_by", "Verified by")]))
        + _section("Stored-energy dissipation",
                   f"<p>{_esc(doc.get('stored_energy_steps',''))}</p>")
        + _section("Zero-energy verification",
                   f"<p>{_esc(doc.get('zero_energy_test',''))}</p>")
        + _section("Authorised workers", _ul(doc.get("authorised_workers") or []))
        + _section("Reinstatement", _kv([
            ("All personnel clear (Y/N)", doc.get("personnel_clear")),
            ("Locks/tags removed by", doc.get("removal_by")),
            ("Reinstated at", doc.get("reinstated_at")),
        ]))
        + _section("Authorisation", _kv([
            ("Authorised by", doc.get("authorised_by")),
            ("Signature/ID", doc.get("authorised_by_signature")),
            ("Authorised at", doc.get("authorised_at")),
        ]))
    )
    return _render_common(doc, "Lock-Out / Tag-Out Permit",
                          "AS/NZS 4024 · Isolation of hazardous energy",
                          body, "Lock-Out Tag-Out")


# ========== Manual Handling Risk Assessment ==========
def render_manual_handling_ra(doc: dict) -> str:
    body = (
        _section("Task details", _kv([
            ("Task", doc.get("task")),
            ("Site", doc.get("site")),
            ("Assessed by", doc.get("assessed_by")),
            ("Assessment date", doc.get("assessment_date")),
        ]))
        + _section("Task description", f"<p>{_esc(doc.get('task_description',''))}</p>")
        + _section("Risk factors (ManTRA / NIOSH)",
                   _tbl(doc.get("factors") or [],
                        [("factor", "Factor"), ("rating", "Rating (L/M/H)"),
                         ("detail", "Detail")]))
        + _section("Controls",
                   _tbl(doc.get("controls") or [],
                        [("hierarchy", "Hierarchy"), ("control", "Control"),
                         ("responsible", "Responsible")]))
        + _section("Residual risk", f"<p>{_esc(doc.get('residual_risk',''))}</p>")
        + _section("Review", _kv([
            ("Review date", doc.get("review_date")),
            ("Approved by", doc.get("approved_by")),
        ]))
    )
    return _render_common(doc, "Manual Handling Risk Assessment",
                          "WHS Reg 60 · Hazardous manual tasks",
                          body, "Manual Handling RA")


# ========== Noise Assessment ==========
def render_noise_assessment(doc: dict) -> str:
    body = (
        _section("Site details", _kv([
            ("Site", doc.get("site")),
            ("Assessor", doc.get("assessor_name")),
            ("Sound level meter", doc.get("meter_model")),
            ("Meter calibration date", doc.get("meter_calibration")),
            ("Assessment date", doc.get("assessment_date")),
        ]))
        + _section("Noise sources / measurements",
                   _tbl(doc.get("measurements") or [],
                        [("source", "Source"), ("location", "Location"),
                         ("dba", "LAeq dB(A)"), ("duration", "Duration"),
                         ("exposure", "8-hr exposure")]))
        + _section("Exceedances",
                   f"<p>{_esc(doc.get('exceedances','') or 'Compare against 85 dB(A) LAeq,8h and 140 dB(C) peak exposure standards.')}</p>")
        + _section("Controls",
                   _ul(doc.get("controls") or []))
        + _section("PPE / hearing protection", _ul(doc.get("ppe") or []))
        + _section("Audiometric testing scheduled", _kv([
            ("Workers to be tested (count)", doc.get("audio_count")),
            ("Testing scheduled for", doc.get("audio_scheduled")),
        ]))
        + _section("Approval", _kv([
            ("Approved by", doc.get("approved_by")),
            ("Review date", doc.get("review_date")),
        ]))
    )
    return _render_common(doc, "Noise Assessment",
                          "WHS Reg 56-58 · AS/NZS 1269", body, "Noise Assessment")


# ========== Silica / Dust Control Plan ==========
def render_silica_plan(doc: dict) -> str:
    body = (
        _section("Project details", _kv([
            ("Project / site", doc.get("project")),
            ("Site address", doc.get("site_address")),
            ("Trade", doc.get("trade")),
            ("Prepared by", doc.get("prepared_by")),
            ("Review date", doc.get("review_date")),
        ]))
        + _section("Silica-generating tasks",
                   _tbl(doc.get("tasks") or [],
                        [("task", "Task"), ("material", "Material"),
                         ("duration", "Duration"),
                         ("expected_exposure", "Est. exposure mg/m³")]))
        + _section("Engineering controls (water suppression / LEV)",
                   _ul(doc.get("engineering_controls") or []))
        + _section("Administrative controls",
                   _ul(doc.get("admin_controls") or []))
        + _section("RPE required",
                   _tbl(doc.get("rpe") or [],
                        [("task", "Task"), ("rpe_type", "RPE type"),
                         ("protection_factor", "APF")]))
        + _section("Air monitoring", f"<p>{_esc(doc.get('air_monitoring',''))}</p>")
        + _section("Health monitoring", f"<p>{_esc(doc.get('health_monitoring',''))}</p>")
        + _section("Training requirements", _ul(doc.get("training") or []))
    )
    return _render_common(doc, "Silica / Dust Control Plan",
                          "WHS Reg 49-50 · WES 0.05 mg/m³", body, "Silica Dust Control")


# ========== Welding Procedure Specification (WPS) ==========
def render_welding_procedure(doc: dict) -> str:
    body = (
        _section("Procedure details", _kv([
            ("WPS number", doc.get("wps_number")),
            ("Project", doc.get("project")),
            ("Welding process", doc.get("welding_process")),
            ("Parent material / grade", doc.get("parent_material")),
            ("Joint type", doc.get("joint_type")),
            ("Position", doc.get("position")),
            ("Thickness range (mm)", doc.get("thickness_range")),
        ]))
        + _section("Consumables & parameters", _kv([
            ("Filler metal / classification", doc.get("filler")),
            ("Shielding gas / flux", doc.get("shielding")),
            ("Current / polarity", doc.get("current")),
            ("Voltage (V)", doc.get("voltage")),
            ("Amperage (A)", doc.get("amperage")),
            ("Travel speed (mm/min)", doc.get("travel_speed")),
            ("Preheat (°C)", doc.get("preheat")),
            ("Interpass max (°C)", doc.get("interpass")),
            ("Post-weld heat treatment", doc.get("pwht")),
        ]))
        + _section("Special instructions", f"<p>{_esc(doc.get('special_instructions',''))}</p>")
        + _section("NDT requirements", _ul(doc.get("ndt") or []))
        + _section("Qualification", _kv([
            ("Qualified welder name", doc.get("welder_name")),
            ("Welder ticket / certificate", doc.get("welder_ticket")),
            ("Qualified to standard", doc.get("standard")),
            ("Qualified by", doc.get("qualified_by")),
            ("Date", doc.get("qualified_date")),
        ]))
    )
    return _render_common(doc, "Welding Procedure Specification",
                          "AS/NZS 3834 · AS/NZS 1554", body, "Welding Procedure")


# ========== Electrical Test & Tag Register ==========
def render_test_tag_register(doc: dict) -> str:
    body = (
        _section("Register details", _kv([
            ("Business", doc.get("company_name")),
            ("Site / location", doc.get("site_location")),
            ("Tester name", doc.get("tester_name")),
            ("Tester competency (RII / electrician)", doc.get("tester_competency")),
            ("Test kit / PAT model", doc.get("kit_model")),
            ("Kit calibration date", doc.get("kit_calibration")),
            ("Frequency (months)", doc.get("frequency_months")),
            ("Next scheduled audit", doc.get("next_audit")),
        ]))
        + _section("Appliances tested",
                   _tbl(doc.get("items") or [],
                        [("asset_id", "Asset / tag ID"), ("description", "Description"),
                         ("location", "Location"), ("class", "Class (I/II)"),
                         ("test_date", "Test date"), ("result", "Result"),
                         ("next_test", "Next test")]))
        + _section("Note",
                   "<p style='font-size:9pt;'>AS/NZS 3760:2022 — in-service safety inspection "
                   "and testing of electrical equipment. Test frequency varies by environment "
                   "(construction 3-mo; office 60-mo).</p>")
    )
    return _render_common(doc, "Electrical Test & Tag Register",
                          "AS/NZS 3760", body, "Test & Tag Register")


# ========== Fire Safety Plan ==========
def render_fire_safety_plan(doc: dict) -> str:
    body = (
        _section("Site details", _kv([
            ("Site", doc.get("site_name")),
            ("Address", doc.get("site_address")),
            ("Building class (BCA)", doc.get("building_class")),
            ("Prepared by", doc.get("prepared_by")),
            ("Review date", doc.get("review_date")),
        ]))
        + _section("Fire risks",
                   _ul(doc.get("fire_risks") or []))
        + _section("Fire prevention measures",
                   _ul(doc.get("prevention_measures") or []))
        + _section("Fire detection & alarm systems",
                   _tbl(doc.get("detection_systems") or [],
                        [("system", "System"), ("location", "Location"),
                         ("last_service", "Last service"),
                         ("next_service", "Next service")]))
        + _section("Fire-fighting equipment",
                   _tbl(doc.get("equipment") or [],
                        [("equipment", "Equipment"), ("location", "Location"),
                         ("qty", "Qty"), ("last_inspection", "Last inspection")]))
        + _section("Evacuation procedure", f"<p>{_esc(doc.get('evacuation_procedure',''))}</p>")
        + _section("Assembly points", _ul(doc.get("assembly_points") or []))
        + _section("Fire warden(s)",
                   _tbl(doc.get("wardens") or [],
                        [("name", "Name"), ("role", "Role"), ("phone", "Phone")]))
        + _section("Training", f"<p>{_esc(doc.get('training',''))}</p>")
    )
    return _render_common(doc, "Fire Safety Plan",
                          "BCA / NCC · AS 3745", body, "Fire Safety Plan")


# ========== Environmental Management Plan (EMP) ==========
def render_emp(doc: dict) -> str:
    body = (
        _section("Project details", _kv([
            ("Project", doc.get("project")),
            ("Site address", doc.get("site_address")),
            ("Site state", doc.get("site_state")),
            ("Prepared by", doc.get("prepared_by")),
            ("Review date", doc.get("review_date")),
        ]))
        + _section("Environmental aspects & impacts",
                   _tbl(doc.get("aspects") or [],
                        [("aspect", "Aspect"), ("impact", "Impact"),
                         ("rating", "Rating"), ("control", "Control")]))
        + _section("Sediment & erosion controls",
                   _ul(doc.get("sediment_controls") or []))
        + _section("Waste management",
                   _tbl(doc.get("waste_streams") or [],
                        [("stream", "Stream"), ("disposal", "Disposal method"),
                         ("contractor", "Contractor")]))
        + _section("Water & air quality", f"<p>{_esc(doc.get('water_air_quality',''))}</p>")
        + _section("Noise & vibration management",
                   f"<p>{_esc(doc.get('noise_vibration',''))}</p>")
        + _section("Incident response", f"<p>{_esc(doc.get('incident_response',''))}</p>")
        + _section("Compliance register",
                   _tbl(doc.get("compliance_items") or [],
                        [("requirement", "Requirement"), ("source", "Source"),
                         ("responsible", "Responsible")]))
        + _section("Approval", _kv([
            ("Approved by", doc.get("approved_by")),
            ("Approved at", doc.get("approved_at")),
        ]))
    )
    return _render_common(doc, "Environmental Management Plan",
                          "ISO 14001 · EPA state guidelines", body, "EMP")






