"""
Document Library — Phase 2 (8 most-used non-SWMS compliance documents).

Uses a shared schema-registry pattern: each doc type registers its form fields,
AI prompt hints, and PDF render function. The module ships ONE generic CRUD
surface + ONE PDF endpoint that dispatches by doc_type. Adding new doc types
is additive — no extra routes needed.

Doc types shipped in Phase 2:
  jsa, risk_assessment, sssp, emergency_plan, hazardous_chemicals,
  site_induction, confined_space_permit, toolbox_talk_record
"""
from __future__ import annotations

import uuid
import asyncio
import re
import json as _json
from datetime import datetime, timezone, timedelta
from typing import Any, Optional, List, Callable

from fastapi import APIRouter, Depends, HTTPException, Response
from pydantic import BaseModel

docs_router = APIRouter()

STATE_REGULATORS = {
    "NSW": {"name": "SafeWork NSW", "phone": "13 10 50"},
    "VIC": {"name": "WorkSafe Victoria", "phone": "13 23 60"},
    "QLD": {"name": "Workplace Health and Safety QLD", "phone": "1300 362 128"},
    "WA": {"name": "WorkSafe WA", "phone": "1300 307 877"},
    "SA": {"name": "SafeWork SA", "phone": "1300 365 255"},
    "TAS": {"name": "WorkSafe Tasmania", "phone": "1300 366 322"},
    "NT": {"name": "NT WorkSafe", "phone": "1800 019 115"},
    "ACT": {"name": "WorkSafe ACT", "phone": "02 6207 3000"},
}

CATEGORIES = [
    {"id": "safety", "label": "Safety Documents",
     "blurb": "SWMS, JSA, risk assessment, site safety plan, emergency plan",
     "icon": "ShieldCheck"},
    {"id": "worker", "label": "Worker Documents",
     "blurb": "Inductions, fit-for-work, training records",
     "icon": "UserCircle"},
    {"id": "contractor", "label": "Contractor Documents",
     "blurb": "Prequalification, site acknowledgements",
     "icon": "Handshake"},
    {"id": "incident", "label": "Incident Documents",
     "blurb": "Incident + investigation + RTW + register",
     "icon": "Warning"},
    {"id": "plant", "label": "Plant Documents",
     "blurb": "Pre-start, service, test & tag, defect",
     "icon": "Wrench"},
    {"id": "trade", "label": "Trade-Specific Documents",
     "blurb": "CCEW, NOW/COC, gas, pressure, backflow",
     "icon": "Clipboard"},
]

# ---------- Doc-type registry ----------

DOC_TYPES: dict[str, dict[str, Any]] = {}


def register_doc_type(spec: dict):
    DOC_TYPES[spec["id"]] = spec


def _esc(s: Any) -> str:
    if s is None:
        return ""
    return (str(s).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"))


def _common_css() -> str:
    return """
    @page { size: A4; margin: 15mm 12mm 18mm 12mm;
            @bottom-center { content: attr(data-footer) " · Page " counter(page) " of " counter(pages);
                             font-family: Arial, sans-serif; font-size: 8pt; color: #666; } }
    body { font-family: Arial, sans-serif; color: #0a0a0a; font-size: 10pt; line-height: 1.45; }
    h1 { font-size: 22pt; font-weight: 900; letter-spacing: -0.02em; margin: 0; text-align: center; }
    h2 { font-size: 13pt; font-weight: 900; letter-spacing: -0.01em; margin: 18px 0 8px;
         padding-top: 8px; border-top: 2px solid #0a0a0a; }
    .sub { text-align: center; font-size: 12pt; color: #555; margin: 4px 0 18px; }
    .ref-line { text-align: center; font-size: 10pt; letter-spacing: 0.1em; color: #444; margin-bottom: 12px; }
    .legal { background: #fff7cc; border: 2px solid #0a0a0a; padding: 10px 14px; font-size: 9pt; margin: 16px 0; }
    .legal strong { display: block; font-size: 10pt; margin-bottom: 4px; }
    table { width: 100%; border-collapse: collapse; font-size: 9.5pt; }
    th, td { border: 1px solid #0a0a0a; padding: 6px 8px; vertical-align: top; }
    th { background: #0a0a0a; color: #ffcc00; text-transform: uppercase; font-size: 8.5pt; letter-spacing: 0.05em; }
    .kv td.k { width: 30%; background: #f6f6f6; font-weight: 700; }
    .emergency { background: #e0f2fe; border: 1px solid #075985; padding: 10px 14px; font-size: 9.5pt; }
    .footer-note { font-size: 8pt; color: #666; margin-top: 18px; font-style: italic;
                   border-top: 1px solid #ccc; padding-top: 8px; }
    ul { margin: 4px 0 4px 16px; padding: 0; }
    .ck { padding: 2px 0; font-size: 9.5pt; }
    .mono { font-family: monospace; font-size: 11pt; display: inline-block; width: 14px; }
    """


def _header(title: str, subtitle: str, ref: str, now_str: str) -> str:
    return f"""
    <h1>{_esc(title.upper())}</h1>
    <div class="sub">{_esc(subtitle)}</div>
    <div class="ref-line">{_esc(ref)} · Generated {now_str}</div>
    """


def _legal_box() -> str:
    return ("""<div class="legal"><strong>IMPORTANT</strong>"""
            "This document was generated by SafeTradie using AI assistance. It must be reviewed "
            "and tailored to your specific workplace before use. SafeTradie does not provide legal "
            "or professional advice. All documents must be reviewed by a qualified person. "
            "SafeTradie Pty Ltd accepts no liability for the accuracy or completeness of "
            "generated documents.</div>""")


def _footer_note(doc_type: str) -> str:
    return (f'<div class="footer-note">SafeTradie · {_esc(doc_type)} · This document must be '
            "reviewed and tailored on site before being relied upon for compliance purposes."
            "</div>")


# ---------- PDF renderers (per doc type) ----------

def _render_common(doc: dict, title: str, subtitle: str, body_html: str, footer: str) -> str:
    ref = _esc(doc.get("reference", "") or doc.get("doc_id", ""))
    now_str = datetime.now(timezone.utc).strftime("%d %b %Y")
    return f"""<!doctype html><html><head><meta charset="utf-8"><title>{_esc(title)}</title>
<style>{_common_css()}</style></head>
<body data-footer="{_esc(doc.get('company_name',''))} · {ref} · {footer}">
{_header(title, subtitle, ref, now_str)}
{_legal_box()}
{body_html}
{_footer_note(title)}
</body></html>"""


def _kv(items: list[tuple[str, Any]]) -> str:
    rows = "".join(
        f"<tr><td class='k'>{_esc(k)}</td><td>{_esc(v) if v is not None else '—'}</td></tr>"
        for k, v in items
    )
    return f'<table class="kv"><tbody>{rows}</tbody></table>'


def _section(title: str, inner: str) -> str:
    return f"<h2>{_esc(title)}</h2>{inner}"


# ========== JSA ==========
def render_jsa(doc: dict) -> str:
    steps = doc.get("steps") or []
    rows = ""
    for i, s in enumerate(steps):
        hz = "<ul>" + "".join(f"<li>{_esc(h)}</li>" for h in s.get('hazards', []) if h) + "</ul>"
        ctrl = "<ul>" + "".join(f"<li>{_esc(c)}</li>" for c in s.get('controls', []) if c) + "</ul>"
        rows += f"<tr><td>{i+1}. {_esc(s.get('step',''))}</td><td>{hz}</td><td>{ctrl}</td></tr>"
    body = (
        _section("Job details", _kv([
            ("Task", doc.get("task")), ("Site", doc.get("site")),
            ("Date", doc.get("work_date")), ("Prepared by", doc.get("prepared_by")),
            ("Workers", ", ".join(doc.get("worker_names", []) or [])),
        ]))
        + _section("Steps, Hazards and Controls",
                   f"<table><thead><tr><th>Step</th><th>Hazards</th><th>Controls</th></tr></thead>"
                   f"<tbody>{rows or '<tr><td colspan=3>—</td></tr>'}</tbody></table>")
        + _section("PPE Required", "<div>" + "".join(
            f'<div class="ck"><span class="mono">☒</span> {_esc(p)}</div>'
            for p in (doc.get("ppe") or [])) + "</div>")
        + _section("Note",
                   "<p style='font-size:9pt;color:#666;'>A JSA is NOT a substitute for a SWMS where "
                   "High Risk Construction Work is involved. Use SafeTradie's SWMS Generator for HRCW.</p>")
    )
    return _render_common(doc, "Job Safety Analysis", "Hazard identification for non-HRCW tasks",
                          body, "Job Safety Analysis")


# ========== Risk Assessment ==========
def render_risk_assessment(doc: dict) -> str:
    items = doc.get("items") or []
    rows = ""
    for i, it in enumerate(items):
        inh = (it.get("inherent_likelihood", 0)) * (it.get("inherent_consequence", 0))
        res = (it.get("residual_likelihood", 0)) * (it.get("residual_consequence", 0))
        rows += (f"<tr><td>{i+1}. {_esc(it.get('hazard',''))}</td>"
                 f"<td>{inh}<br><small>({it.get('inherent_likelihood','')}×{it.get('inherent_consequence','')})</small></td>"
                 f"<td>{_esc(it.get('controls',''))}</td>"
                 f"<td>{res}<br><small>({it.get('residual_likelihood','')}×{it.get('residual_consequence','')})</small></td>"
                 f"<td>{_esc(it.get('responsible',''))}</td></tr>")
    body = (
        _section("Activity details", _kv([
            ("Activity", doc.get("activity")), ("Site", doc.get("site")),
            ("Trade", doc.get("trade")), ("Prepared by", doc.get("prepared_by")),
            ("Review date", doc.get("review_date")),
        ]))
        + _section("Risk register",
                   "<table><thead><tr><th>Hazard</th><th>Inherent</th><th>Controls</th>"
                   "<th>Residual</th><th>Responsible</th></tr></thead>"
                   f"<tbody>{rows or '<tr><td colspan=5>—</td></tr>'}</tbody></table>")
    )
    return _render_common(doc, "Risk Assessment",
                          "Activity risk identification and controls",
                          body, "Risk Assessment")


# ========== SSSP ==========
def render_sssp(doc: dict) -> str:
    state = doc.get("site_state", "NSW")
    reg = STATE_REGULATORS.get(state, {"name": "", "phone": ""})
    body = (
        _section("Site details", _kv([
            ("Site name", doc.get("site_name")), ("Site address", doc.get("site_address")),
            ("Principal contractor", doc.get("principal_contractor")),
            ("Site supervisor", doc.get("site_supervisor")),
            ("Supervisor phone", doc.get("supervisor_phone")),
        ]))
        + _section("Emergency contacts",
                   f'<div class="emergency">'
                   f"<div><strong>Emergency:</strong> 000</div>"
                   f"<div><strong>State WHS regulator:</strong> {_esc(reg['name'])} — {_esc(reg['phone'])}</div>"
                   f"<div><strong>Nearest hospital:</strong> {_esc(doc.get('nearest_hospital',''))}</div>"
                   f"<div><strong>Assembly point:</strong> {_esc(doc.get('assembly_point',''))}</div>"
                   f"<div><strong>First aider on site:</strong> {_esc(doc.get('first_aider',''))}</div>"
                   f"</div>")
        + _section("Site-specific hazards",
                   "<ul>" + "".join(f"<li>{_esc(h)}</li>" for h in (doc.get("hazards") or [])) + "</ul>")
        + _section("Site rules",
                   "<ul>" + "".join(f"<li>{_esc(r)}</li>" for r in (doc.get("site_rules") or [])) + "</ul>")
        + _section("PPE requirements",
                   "<div>" + "".join(f'<div class="ck"><span class="mono">☒</span> {_esc(p)}</div>' for p in (doc.get("ppe") or [])) + "</div>")
        + _section("Induction requirements", f"<p>{_esc(doc.get('induction_requirements',''))}</p>")
    )
    return _render_common(doc, "Site-Specific Safety Plan",
                          "Single-page site safety summary",
                          body, "SSSP")


# ========== Emergency Plan ==========
def render_emergency_plan(doc: dict) -> str:
    state = doc.get("site_state", "NSW")
    reg = STATE_REGULATORS.get(state, {"name": "", "phone": ""})
    contacts = doc.get("emergency_contacts") or []
    contact_rows = "".join(
        f"<tr><td>{_esc(c.get('name',''))}</td><td>{_esc(c.get('role',''))}</td><td>{_esc(c.get('phone',''))}</td></tr>"
        for c in contacts)
    equip_rows = "".join(
        f"<tr><td>{_esc(e.get('equipment',''))}</td><td>{_esc(e.get('location',''))}</td></tr>"
        for e in (doc.get("emergency_equipment") or []))
    procs = doc.get("procedures") or {}
    proc_html = ""
    for label in ["fire", "medical", "chemical_spill", "electric_shock",
                  "fall_from_height", "structural_collapse", "flood"]:
        if procs.get(label):
            proc_html += f"<h3 style='font-size:11pt;font-weight:700'>{label.replace('_',' ').title()}</h3><p>{_esc(procs.get(label))}</p>"
    body = (
        _section("Site", _kv([("Site", doc.get("site_name")), ("Address", doc.get("site_address")),
                               ("Prepared by", doc.get("prepared_by")),
                               ("Assembly point", doc.get("assembly_point"))]))
        + _section("Emergency services",
                   f'<div class="emergency">'
                   f"<div><strong>Emergency:</strong> 000</div>"
                   f"<div><strong>State WHS regulator:</strong> {_esc(reg['name'])} — {_esc(reg['phone'])}</div>"
                   f"<div><strong>Nearest hospital:</strong> {_esc(doc.get('nearest_hospital',''))}</div>"
                   f"</div>")
        + _section("Internal emergency contacts",
                   f"<table><thead><tr><th>Name</th><th>Role</th><th>Phone</th></tr></thead>"
                   f"<tbody>{contact_rows or '<tr><td colspan=3>—</td></tr>'}</tbody></table>")
        + _section("Evacuation procedure", f"<p>{_esc(doc.get('evacuation_procedure',''))}</p>")
        + _section("Emergency equipment",
                   f"<table><thead><tr><th>Equipment</th><th>Location</th></tr></thead>"
                   f"<tbody>{equip_rows or '<tr><td colspan=2>—</td></tr>'}</tbody></table>")
        + (_section("Specific emergency procedures", proc_html) if proc_html else "")
    )
    return _render_common(doc, "Emergency Plan",
                          "Emergency response procedures (WHS Reg 43)",
                          body, "Emergency Plan")


# ========== Hazardous Chemicals Register ==========
def render_haz_chemicals(doc: dict) -> str:
    items = doc.get("chemicals") or []
    rows = "".join(
        f"<tr><td>{_esc(c.get('product',''))}</td>"
        f"<td>{_esc(c.get('manufacturer',''))}</td>"
        f"<td>{_esc(c.get('sds_date',''))}</td>"
        f"<td>{_esc(c.get('hazard_class',''))}</td>"
        f"<td>{_esc(c.get('location',''))}</td>"
        f"<td>{_esc(c.get('max_quantity',''))}</td>"
        f"<td>{_esc(c.get('ppe',''))}</td></tr>" for c in items)
    body = (
        _section("Business details", _kv([
            ("Business name", doc.get("company_name")),
            ("Site/location", doc.get("site_location")),
            ("Register compiled by", doc.get("prepared_by")),
            ("Review date", doc.get("review_date")),
        ]))
        + _section("Hazardous chemicals",
                   "<table><thead><tr>"
                   "<th>Product</th><th>Manufacturer</th><th>SDS date</th>"
                   "<th>Hazard class</th><th>Location</th><th>Max qty</th><th>PPE</th>"
                   "</tr></thead>"
                   f"<tbody>{rows or '<tr><td colspan=7>—</td></tr>'}</tbody></table>")
        + _section("Note",
                   "<p style='font-size:9pt;'>SDSs must be kept accessible for all chemicals in this "
                   "register (WHS Reg 344). Review when any new chemical is introduced or SDS updates.</p>")
    )
    return _render_common(doc, "Hazardous Chemicals Register",
                          "WHS Regulations Reg 346",
                          body, "Haz Chemicals Register")


# ========== Site Induction Checklist ==========
def render_site_induction(doc: dict) -> str:
    items = doc.get("checklist") or []
    li = "".join(
        f'<div class="ck"><span class="mono">{"☒" if c.get("done") else "☐"}</span> {_esc(c.get("item",""))}</div>'
        for c in items)
    sig = doc.get("signed_at", "") and f'<img src="{_esc(doc.get("signature_data",""))}" style="max-height:40px"/>' if (doc.get("signature_data") or "").startswith("data:image") else _esc(doc.get("signature_data", ""))
    body = (
        _section("Induction", _kv([
            ("Worker", doc.get("worker_name")),
            ("Trade/Role", doc.get("worker_role")),
            ("Site", doc.get("site_name")),
            ("Inducted by", doc.get("inducted_by")),
            ("Date", doc.get("induction_date")),
        ]))
        + _section("Checklist", f"<div>{li or '—'}</div>")
        + _section("Sign-off",
                   f"<p>Worker: {_esc(doc.get('worker_name',''))}<br>"
                   f"Signature: {sig or '_______________________'}<br>"
                   f"Date: {_esc((doc.get('signed_at') or '')[:10]) or '___/___/______'}</p>")
    )
    return _render_common(doc, "Site Induction Checklist",
                          "WHS Regulations Reg 316-317",
                          body, "Site Induction")


# ========== Confined Space Entry Permit ==========
def render_confined_space(doc: dict) -> str:
    atmos = doc.get("atmosphere") or {}
    body = (
        _section("Space identification", _kv([
            ("Space name/ID", doc.get("space_id")),
            ("Location", doc.get("location")),
            ("Nature of work", doc.get("work_description")),
            ("Date/time of entry", doc.get("entry_datetime")),
            ("Duration of permit", doc.get("duration")),
        ]))
        + _section("Authorised workers", "<ul>" + "".join(f"<li>{_esc(w)}</li>" for w in (doc.get("authorised_workers") or [])) + "</ul>")
        + _section("Atmospheric testing",
                   _kv([("Oxygen %", atmos.get("oxygen")),
                        ("LEL %", atmos.get("lel")),
                        ("Toxic gases (ppm)", atmos.get("toxic_gases")),
                        ("Tested by", atmos.get("tested_by")),
                        ("Test time", atmos.get("tested_at"))]))
        + _section("Entry controls", "<ul>" + "".join(f"<li>{_esc(c)}</li>" for c in (doc.get("entry_controls") or [])) + "</ul>")
        + _section("Standby person + communication", _kv([
            ("Standby person", doc.get("standby_person")),
            ("Communication method", doc.get("communication")),
        ]))
        + _section("Emergency procedures", f"<p>{_esc(doc.get('emergency_procedures',''))}</p>")
        + _section("Authorisation", _kv([
            ("Authorised by", doc.get("authorised_by")),
            ("Signature/ID", doc.get("authorised_by_signature")),
            ("Authorised date/time", doc.get("authorised_at")),
            ("Permit rescinded", doc.get("rescinded_at")),
        ]))
    )
    return _render_common(doc, "Confined Space Entry Permit",
                          "WHS Regulations Reg 66-77",
                          body, "Confined Space Permit")


# ========== Toolbox Talk Record ==========
def render_toolbox_record(doc: dict) -> str:
    attendees = doc.get("attendees") or []
    att_rows = "".join(
        f"<tr><td>{_esc(a.get('name',''))}</td><td>_______________________</td><td>___/___/______</td></tr>"
        for a in attendees)
    body = (
        _section("Talk details", _kv([
            ("Topic", doc.get("topic")), ("Site", doc.get("site")),
            ("Date", doc.get("talk_date")), ("Conducted by", doc.get("conducted_by")),
            ("Duration (mins)", doc.get("duration_mins")),
        ]))
        + _section("Key points",
                   "<ul>" + "".join(f"<li>{_esc(k)}</li>" for k in (doc.get("key_points") or [])) + "</ul>")
        + _section("Worker questions / discussion",
                   f"<p>{_esc(doc.get('discussion','') or '—')}</p>")
        + _section("Attendees",
                   "<table><thead><tr><th>Name</th><th>Signature</th><th>Date</th></tr></thead>"
                   f"<tbody>{att_rows or '<tr><td colspan=3>—</td></tr>'}</tbody></table>")
    )
    return _render_common(doc, "Toolbox Talk Record",
                          "Pre-start safety briefing",
                          body, "Toolbox Talk Record")


# ========== WHS Management Plan ==========
def render_whs_mgmt_plan(doc: dict) -> str:
    state = doc.get("site_state", "NSW")
    reg = STATE_REGULATORS.get(state, {"name": "", "phone": ""})
    personnel = doc.get("key_personnel") or []
    p_rows = "".join(
        f"<tr><td>{_esc(p.get('name',''))}</td><td>{_esc(p.get('role',''))}</td><td>{_esc(p.get('phone',''))}</td></tr>"
        for p in personnel)
    resp = doc.get("responsibilities") or []
    r_rows = "".join(
        f"<tr><td>{_esc(r.get('role',''))}</td><td>{_esc(r.get('responsibility',''))}</td></tr>"
        for r in resp)
    body = (
        _section("Project details", _kv([
            ("Project", doc.get("project_name")),
            ("Principal contractor", doc.get("principal_contractor")),
            ("Site address", doc.get("site_address")),
            ("State", state),
            ("Project value", doc.get("project_value")),
            ("Project duration", doc.get("project_duration")),
            ("Prepared by", doc.get("prepared_by")),
            ("Review date", doc.get("review_date")),
        ]))
        + _section("Scope of work", f"<p>{_esc(doc.get('scope_of_work',''))}</p>")
        + _section("Regulator", f'<div class="emergency">'
                   f"<div><strong>State WHS regulator:</strong> {_esc(reg['name'])} — {_esc(reg['phone'])}</div>"
                   f"<div><strong>Emergency:</strong> 000</div></div>")
        + _section("Key personnel",
                   "<table><thead><tr><th>Name</th><th>Role</th><th>Phone</th></tr></thead>"
                   f"<tbody>{p_rows or '<tr><td colspan=3>—</td></tr>'}</tbody></table>")
        + _section("WHS responsibilities",
                   "<table><thead><tr><th>Role</th><th>Responsibility</th></tr></thead>"
                   f"<tbody>{r_rows or '<tr><td colspan=2>—</td></tr>'}</tbody></table>")
        + _section("Risk management approach", f"<p>{_esc(doc.get('risk_management_approach',''))}</p>")
        + _section("Consultation arrangements", f"<p>{_esc(doc.get('consultation_arrangements',''))}</p>")
        + _section("Training requirements",
                   "<ul>" + "".join(f"<li>{_esc(t)}</li>" for t in (doc.get("training_requirements") or [])) + "</ul>")
        + _section("Monitoring & review", f"<p>{_esc(doc.get('monitoring_review',''))}</p>")
    )
    return _render_common(doc, "WHS Management Plan",
                          "Principal Contractor WHS plan (WHS Reg 309)",
                          body, "WHS Management Plan")


# ========== Asbestos Register ==========
def render_asbestos_register(doc: dict) -> str:
    items = doc.get("items") or []
    rows = "".join(
        f"<tr><td>{_esc(a.get('location',''))}</td>"
        f"<td>{_esc(a.get('material',''))}</td>"
        f"<td>{_esc(a.get('friable',''))}</td>"
        f"<td>{_esc(a.get('condition',''))}</td>"
        f"<td>{_esc(a.get('risk',''))}</td>"
        f"<td>{_esc(a.get('control',''))}</td>"
        f"<td>{_esc(a.get('accessible',''))}</td></tr>" for a in items)
    body = (
        _section("Site details", _kv([
            ("Site", doc.get("site_name")),
            ("Address", doc.get("site_address")),
            ("Prepared by", doc.get("prepared_by")),
            ("Assessor name", doc.get("assessor_name")),
            ("Inspection date", doc.get("inspection_date")),
            ("Next review", doc.get("next_review")),
        ]))
        + _section("Asbestos-containing materials",
                   "<table><thead><tr>"
                   "<th>Location</th><th>Material</th><th>Friable</th>"
                   "<th>Condition</th><th>Risk</th><th>Control</th><th>Accessible</th>"
                   "</tr></thead>"
                   f"<tbody>{rows or '<tr><td colspan=7>—</td></tr>'}</tbody></table>")
        + _section("Note",
                   "<p style='font-size:9pt;'>Required under WHS Regulations Reg 425 for any "
                   "workplace where asbestos or ACM is identified or presumed. Keep current; "
                   "reviewed at least every 5 years, or when asbestos is removed, disturbed, "
                   "sealed or enclosed.</p>")
    )
    return _render_common(doc, "Asbestos Register",
                          "WHS Regulations Reg 425",
                          body, "Asbestos Register")


# ========== CCEW (NSW Electrical Certificate) ==========
def render_ccew(doc: dict) -> str:
    tested = doc.get("test_results") or []
    t_rows = "".join(
        f"<tr><td>{_esc(t.get('test',''))}</td><td>{_esc(t.get('result',''))}</td></tr>"
        for t in tested)
    body = (
        _section("Licensee details", _kv([
            ("Licensee name", doc.get("licensee_name")),
            ("Licence number", doc.get("licence_no")),
            ("Contractor", doc.get("contractor_name")),
        ]))
        + _section("Customer & site", _kv([
            ("Customer", doc.get("customer_name")),
            ("Site address", doc.get("site_address")),
            ("Work type", doc.get("work_type")),
            ("Installation type", doc.get("installation_type")),
            ("Work date", doc.get("work_date")),
        ]))
        + _section("Scope of work", f"<p>{_esc(doc.get('scope',''))}</p>")
        + _section("Tested items",
                   "<ul>" + "".join(f"<li>{_esc(t)}</li>" for t in (doc.get("tested_items") or [])) + "</ul>")
        + _section("Test results",
                   "<table><thead><tr><th>Test</th><th>Result</th></tr></thead>"
                   f"<tbody>{t_rows or '<tr><td colspan=2>—</td></tr>'}</tbody></table>")
        + _section("Compliance statement",
                   f"<p>{_esc(doc.get('compliance_statement','') or 'I certify that the electrical installation work described above complies with AS/NZS 3000 and the Service and Installation Rules of NSW.')}</p>")
        + _section("Sign-off", _kv([
            ("Signed by", doc.get("signed_by")),
            ("Signature/ID", doc.get("signature")),
            ("Signed at", doc.get("signed_at")),
        ]))
    )
    return _render_common(doc, "Certificate of Compliance — Electrical Work (CCEW)",
                          "NSW — AS/NZS 3000",
                          body, "CCEW")


# ========== NOW/COC Plumbing ==========
def render_plumbing_coc(doc: dict) -> str:
    items = doc.get("work_items") or []
    rows = "".join(
        f"<tr><td>{_esc(it.get('item',''))}</td><td>{_esc(it.get('standard',''))}</td>"
        f"<td>{_esc(it.get('result',''))}</td></tr>" for it in items)
    body = (
        _section("Licensee details", _kv([
            ("Licensee name", doc.get("licensee_name")),
            ("Licence number", doc.get("licence_no")),
            ("Company", doc.get("company_name")),
        ]))
        + _section("Job details", _kv([
            ("Job site", doc.get("job_site")),
            ("Job type", doc.get("job_type")),
            ("Council / authority", doc.get("authority")),
            ("Inspection required", doc.get("inspection_required")),
            ("Work date", doc.get("work_date")),
            ("NOW reference", doc.get("now_reference")),
        ]))
        + _section("Scope of work", f"<p>{_esc(doc.get('scope',''))}</p>")
        + _section("Work items + standards",
                   "<table><thead><tr><th>Item</th><th>Standard</th><th>Result</th></tr></thead>"
                   f"<tbody>{rows or '<tr><td colspan=3>—</td></tr>'}</tbody></table>")
        + _section("Compliance statement",
                   f"<p>{_esc(doc.get('compliance_statement','') or 'I certify that the plumbing/drainage work described above complies with AS/NZS 3500 and relevant state regulations.')}</p>")
        + _section("Sign-off", _kv([
            ("Signed by", doc.get("signed_by")),
            ("Signature/ID", doc.get("signature")),
            ("Signed at", doc.get("signed_at")),
        ]))
    )
    return _render_common(doc, "Plumbing NOW / Certificate of Compliance",
                          "AS/NZS 3500 — State plumbing regulations",
                          body, "Plumbing COC")


# ========== Hot Work Permit ==========
def render_hot_work_permit(doc: dict) -> str:
    checks = doc.get("precautions") or []
    li = "".join(
        f'<div class="ck"><span class="mono">{"☒" if c.get("done") else "☐"}</span> {_esc(c.get("item",""))}</div>'
        for c in checks)
    body = (
        _section("Permit details", _kv([
            ("Location", doc.get("location")),
            ("Nature of work", doc.get("work_description")),
            ("Date/time of start", doc.get("start_datetime")),
            ("Duration", doc.get("duration")),
            ("Rescinded at", doc.get("rescinded_at")),
        ]))
        + _section("Workers + fire watch", _kv([
            ("Authorised workers", ", ".join(doc.get("authorised_workers", []) or [])),
            ("Fire watch person", doc.get("fire_watch_person")),
            ("Extinguisher on site", doc.get("extinguisher_on_site")),
            ("Post-work watch (min)", doc.get("post_work_watch_mins")),
        ]))
        + _section("Pre-start precautions", f"<div>{li or '—'}</div>")
        + _section("Atmosphere tested",
                   _kv([("Tested", doc.get("atmosphere_tested")),
                        ("Tested by", doc.get("atmosphere_tested_by")),
                        ("Test time", doc.get("atmosphere_tested_at"))]))
        + _section("Emergency procedures", f"<p>{_esc(doc.get('emergency_procedures',''))}</p>")
        + _section("Authorisation", _kv([
            ("Authorised by", doc.get("authorised_by")),
            ("Signature/ID", doc.get("authorised_by_signature")),
            ("Authorised at", doc.get("authorised_at")),
        ]))
    )
    return _render_common(doc, "Hot Work Permit",
                          "Welding, cutting, grinding — fire risk control",
                          body, "Hot Work Permit")


# ========== Excavation Permit ==========
def render_excavation_permit(doc: dict) -> str:
    services = doc.get("services_checked") or []
    li = "".join(
        f'<div class="ck"><span class="mono">{"☒" if c.get("done") else "☐"}</span> {_esc(c.get("item",""))}</div>'
        for c in services)
    body = (
        _section("Permit details", _kv([
            ("Location", doc.get("location")),
            ("Nature of work", doc.get("work_description")),
            ("Depth (metres)", doc.get("depth_metres")),
            ("Start date/time", doc.get("start_datetime")),
            ("Duration", doc.get("duration")),
        ]))
        + _section("Services check (Dial Before You Dig)", f"<div>{li or '—'}</div>")
        + _section("Barricades & signage",
                   "<ul>" + "".join(f"<li>{_esc(b)}</li>" for b in (doc.get("barricades") or [])) + "</ul>")
        + _section("Spoil location", f"<p>{_esc(doc.get('spoil_location',''))}</p>")
        + _section("Plant & equipment",
                   "<ul>" + "".join(f"<li>{_esc(p)}</li>" for p in (doc.get("plant_equipment") or [])) + "</ul>")
        + _section("Authorised workers",
                   "<ul>" + "".join(f"<li>{_esc(w)}</li>" for w in (doc.get("authorised_workers") or [])) + "</ul>")
        + _section("Emergency procedures", f"<p>{_esc(doc.get('emergency_procedures',''))}</p>")
        + _section("Authorisation", _kv([
            ("Authorised by", doc.get("authorised_by")),
            ("Signature/ID", doc.get("authorised_by_signature")),
            ("Authorised at", doc.get("authorised_at")),
            ("Permit rescinded", doc.get("rescinded_at")),
        ]))
    )
    return _render_common(doc, "Excavation Permit",
                          "Ground disturbance control (WHS Reg 304)",
                          body, "Excavation Permit")


# ========== Lift Plan ==========
def render_lift_plan(doc: dict) -> str:
    body = (
        _section("Lift details", _kv([
            ("Site", doc.get("site")),
            ("Lift date", doc.get("lift_date")),
            ("Load description", doc.get("load_description")),
            ("Load weight (kg)", doc.get("load_weight_kg")),
            ("Working radius (m)", doc.get("working_radius")),
            ("Lift height (m)", doc.get("lift_height")),
        ]))
        + _section("Crane & rigging", _kv([
            ("Crane type", doc.get("crane_type")),
            ("Crane capacity (kg)", doc.get("crane_capacity_kg")),
            ("Capacity utilised (%)", doc.get("capacity_utilised")),
            ("Rigging configuration", doc.get("rigging_config")),
            ("Dogger name", doc.get("dogger_name")),
            ("Rigger name", doc.get("rigger_name")),
            ("Crane operator", doc.get("crane_operator")),
        ]))
        + _section("Lift sequence", f"<p>{_esc(doc.get('lift_sequence',''))}</p>")
        + _section("Hazards",
                   "<ul>" + "".join(f"<li>{_esc(h)}</li>" for h in (doc.get("hazards") or [])) + "</ul>")
        + _section("Controls",
                   "<ul>" + "".join(f"<li>{_esc(c)}</li>" for c in (doc.get("controls") or [])) + "</ul>")
        + _section("Exclusion zone", f"<p>{_esc(doc.get('exclusion_zone',''))}</p>")
        + _section("Authorisation", _kv([
            ("Prepared by", doc.get("prepared_by")),
            ("Approved by", doc.get("approved_by")),
            ("Approved at", doc.get("approved_at")),
        ]))
    )
    return _render_common(doc, "Lift Plan",
                          "Crane / lifting operations — AS 2550",
                          body, "Lift Plan")


# ========== Fall Protection Plan ==========
def render_fall_protection(doc: dict) -> str:
    checks = doc.get("pre_start_check") or []
    li = "".join(
        f'<div class="ck"><span class="mono">{"☒" if c.get("done") else "☐"}</span> {_esc(c.get("item",""))}</div>'
        for c in checks)
    body = (
        _section("Work details", _kv([
            ("Site", doc.get("site")),
            ("Work area", doc.get("work_area")),
            ("Height (metres)", doc.get("height_metres")),
            ("Work date", doc.get("work_date")),
        ]))
        + _section("Nature of work", f"<p>{_esc(doc.get('work_description',''))}</p>")
        + _section("Edge protection",
                   "<ul>" + "".join(f"<li>{_esc(e)}</li>" for e in (doc.get("edge_protection") or [])) + "</ul>")
        + _section("Fall arrest systems",
                   "<ul>" + "".join(f"<li>{_esc(f)}</li>" for f in (doc.get("fall_arrest_systems") or [])) + "</ul>")
        + _section("Anchor points", f"<p>{_esc(doc.get('anchor_points',''))}</p>")
        + _section("Rescue plan", f"<p>{_esc(doc.get('rescue_plan',''))}</p>")
        + _section("Authorised workers",
                   "<ul>" + "".join(f"<li>{_esc(w)}</li>" for w in (doc.get("authorised_workers") or [])) + "</ul>")
        + _section("Pre-start check", f"<div>{li or '—'}</div>")
        + _section("Sign-off", _kv([
            ("Prepared by", doc.get("prepared_by")),
            ("Approved by", doc.get("approved_by")),
            ("Approved at", doc.get("approved_at")),
        ]))
    )
    return _render_common(doc, "Fall Protection Plan",
                          "Working at heights (WHS Reg 78)",
                          body, "Fall Protection Plan")




# ---------- Register doc types ----------
# Each: {id, category, label, blurb, fields[], ai_prompt (or None), pdf, counter_prefix}

def _f(key, label, type_="text", **kw):
    return {"key": key, "label": label, "type": type_, **kw}

register_doc_type({
    "id": "jsa", "category": "safety",
    "label": "Job Safety Analysis (JSA)",
    "blurb": "Hazard identification for non-HRCW tasks",
    "counter_prefix": "JSA",
    "fields": [
        _f("task", "Task description", "text", required=True),
        _f("site", "Site location"),
        _f("work_date", "Work date", "date"),
        _f("prepared_by", "Prepared by"),
        _f("worker_names", "Workers", "chips"),
        _f("steps", "Steps (with hazards + controls)", "jsa_steps"),
        _f("ppe", "PPE required", "chips"),
    ],
    "ai_prompt": ("Given a JSA task + trade, return JSON: {steps:[{step, hazards:[str], "
                  "controls:[str]}, ...]} with 4-6 steps in logical sequence."),
    "pdf": render_jsa,
})

register_doc_type({
    "id": "risk_assessment", "category": "safety",
    "label": "Risk Assessment",
    "blurb": "Activity risk identification with inherent + residual scoring",
    "counter_prefix": "RA",
    "fields": [
        _f("activity", "Activity", "text", required=True),
        _f("site", "Site"),
        _f("trade", "Trade"),
        _f("prepared_by", "Prepared by"),
        _f("review_date", "Review date", "date"),
        _f("items", "Hazards + controls", "risk_items"),
    ],
    "ai_prompt": ("Given an activity + trade, return JSON: {items:[{hazard, "
                  "inherent_likelihood (1-5), inherent_consequence (1-5), "
                  "controls, residual_likelihood (1-5), residual_consequence (1-5), "
                  "responsible}, ...]} with 4-6 items."),
    "pdf": render_risk_assessment,
})

register_doc_type({
    "id": "sssp", "category": "safety",
    "label": "Site-Specific Safety Plan (SSSP)",
    "blurb": "Single-page site safety summary",
    "counter_prefix": "SSSP",
    "fields": [
        _f("site_name", "Site name", required=True),
        _f("site_address", "Site address"),
        _f("site_state", "Site state", "state"),
        _f("principal_contractor", "Principal contractor"),
        _f("site_supervisor", "Site supervisor"),
        _f("supervisor_phone", "Supervisor phone"),
        _f("nearest_hospital", "Nearest hospital"),
        _f("assembly_point", "Assembly point"),
        _f("first_aider", "First aider on site"),
        _f("hazards", "Site-specific hazards", "chips"),
        _f("site_rules", "Site rules", "chips"),
        _f("ppe", "PPE requirements", "chips"),
        _f("induction_requirements", "Induction requirements", "textarea"),
    ],
    "ai_prompt": ("Given a site name + trade, return JSON: {hazards:[str], "
                  "site_rules:[str], ppe:[str], induction_requirements}"),
    "pdf": render_sssp,
})

register_doc_type({
    "id": "emergency_plan", "category": "safety",
    "label": "Emergency Plan",
    "blurb": "Emergency response procedures (WHS Reg 43 — required for every workplace)",
    "counter_prefix": "EP",
    "fields": [
        _f("site_name", "Site name", required=True),
        _f("site_address", "Site address"),
        _f("site_state", "Site state", "state"),
        _f("prepared_by", "Prepared by"),
        _f("nearest_hospital", "Nearest hospital"),
        _f("assembly_point", "Assembly point"),
        _f("emergency_contacts", "Emergency contacts (name/role/phone)", "contacts"),
        _f("evacuation_procedure", "Evacuation procedure", "textarea"),
        _f("emergency_equipment", "Emergency equipment (equipment/location)", "equipment"),
        _f("procedures", "Specific procedures", "emergency_procs"),
    ],
    "ai_prompt": ("Given a site name + state, return JSON: {evacuation_procedure, "
                  "procedures:{fire, medical, chemical_spill, electric_shock, "
                  "fall_from_height, structural_collapse, flood}}"),
    "pdf": render_emergency_plan,
})

register_doc_type({
    "id": "hazardous_chemicals", "category": "safety",
    "label": "Hazardous Chemicals Register",
    "blurb": "SDS register (WHS Regulations Reg 346)",
    "counter_prefix": "HCR",
    "fields": [
        _f("company_name", "Business name", required=True),
        _f("site_location", "Site / location"),
        _f("prepared_by", "Compiled by"),
        _f("review_date", "Review date", "date"),
        _f("chemicals", "Chemicals (product/manufacturer/SDS/class/location)", "chemicals"),
    ],
    "ai_prompt": None,
    "pdf": render_haz_chemicals,
})

register_doc_type({
    "id": "site_induction", "category": "worker",
    "label": "Site Induction Checklist",
    "blurb": "Worker induction record (WHS Regulations Reg 316-317)",
    "counter_prefix": "IND",
    "fields": [
        _f("worker_name", "Worker name", required=True),
        _f("worker_role", "Trade / role"),
        _f("site_name", "Site"),
        _f("inducted_by", "Inducted by"),
        _f("induction_date", "Induction date", "date"),
        _f("checklist", "Checklist (item / done)", "checklist"),
        _f("signature_data", "Signature (typed or drawn)"),
        _f("signed_at", "Signed at", "datetime"),
    ],
    "ai_prompt": None,
    "pdf": render_site_induction,
})

register_doc_type({
    "id": "confined_space_permit", "category": "safety",
    "label": "Confined Space Entry Permit",
    "blurb": "Entry permit (WHS Regulations Reg 66-77)",
    "counter_prefix": "CSP",
    "fields": [
        _f("space_id", "Space name/ID", required=True),
        _f("location", "Location"),
        _f("work_description", "Nature of work", "textarea"),
        _f("entry_datetime", "Date/time of entry", "datetime"),
        _f("duration", "Duration of permit"),
        _f("authorised_workers", "Authorised workers", "chips"),
        _f("atmosphere", "Atmospheric testing", "atmosphere"),
        _f("entry_controls", "Entry controls", "chips"),
        _f("standby_person", "Standby person"),
        _f("communication", "Communication method"),
        _f("emergency_procedures", "Emergency procedures", "textarea"),
        _f("authorised_by", "Authorised by"),
        _f("authorised_by_signature", "Auth signature / ID"),
        _f("authorised_at", "Authorised at", "datetime"),
        _f("rescinded_at", "Rescinded at", "datetime"),
    ],
    "ai_prompt": None,
    "pdf": render_confined_space,
})

register_doc_type({
    "id": "toolbox_talk_record", "category": "safety",
    "label": "Toolbox Talk Record",
    "blurb": "Pre-start safety briefing",
    "counter_prefix": "TBT",
    "fields": [
        _f("topic", "Topic", required=True),
        _f("site", "Site"),
        _f("talk_date", "Date", "date"),
        _f("conducted_by", "Conducted by"),
        _f("duration_mins", "Duration (mins)", "number"),
        _f("key_points", "Key points", "chips"),
        _f("discussion", "Worker questions / discussion", "textarea"),
        _f("attendees", "Attendees", "attendees"),
    ],
    "ai_prompt": ("Given a topic + trade, return JSON: {key_points:[str (5-7 items)], "
                  "discussion: short paragraph}"),
    "pdf": render_toolbox_record,
})

register_doc_type({
    "id": "whs_mgmt_plan", "category": "safety",
    "label": "WHS Management Plan",
    "blurb": "Principal Contractor WHS plan (WHS Reg 309 — required for construction projects > A$250k)",
    "counter_prefix": "WMP",
    "fields": [
        _f("project_name", "Project name", required=True),
        _f("principal_contractor", "Principal contractor"),
        _f("site_address", "Site address"),
        _f("site_state", "Site state", "state"),
        _f("project_value", "Project value (A$)"),
        _f("project_duration", "Project duration"),
        _f("prepared_by", "Prepared by"),
        _f("review_date", "Review date", "date"),
        _f("scope_of_work", "Scope of work", "textarea"),
        _f("key_personnel", "Key personnel (name/role/phone)", "contacts"),
        _f("responsibilities", "WHS responsibilities (role/responsibility)", "responsibilities"),
        _f("risk_management_approach", "Risk management approach", "textarea"),
        _f("consultation_arrangements", "Consultation arrangements", "textarea"),
        _f("training_requirements", "Training requirements", "chips"),
        _f("monitoring_review", "Monitoring & review", "textarea"),
    ],
    "ai_prompt": ("Given a project name + trade, return JSON: {scope_of_work, "
                  "risk_management_approach, consultation_arrangements, "
                  "training_requirements:[str], monitoring_review}"),
    "pdf": render_whs_mgmt_plan,
})

register_doc_type({
    "id": "asbestos_register", "category": "safety",
    "label": "Asbestos Register",
    "blurb": "ACM register — mandatory for pre-2004 workplaces (WHS Reg 425)",
    "counter_prefix": "ASB",
    "fields": [
        _f("site_name", "Site name", required=True),
        _f("site_address", "Site address"),
        _f("prepared_by", "Prepared by"),
        _f("assessor_name", "Competent assessor name"),
        _f("inspection_date", "Inspection date", "date"),
        _f("next_review", "Next review date", "date"),
        _f("items", "ACM items (location/material/friable/condition/risk/control/accessible)",
           "asbestos_items"),
    ],
    "ai_prompt": None,
    "pdf": render_asbestos_register,
})

register_doc_type({
    "id": "ccew", "category": "trade",
    "label": "Certificate of Compliance — Electrical Work (CCEW)",
    "blurb": "NSW electrical certificate (AS/NZS 3000)",
    "counter_prefix": "CCEW",
    "fields": [
        _f("licensee_name", "Licensee name", required=True),
        _f("licence_no", "Licence number"),
        _f("contractor_name", "Contractor / company"),
        _f("customer_name", "Customer"),
        _f("site_address", "Site address"),
        _f("work_type", "Work type"),
        _f("installation_type", "Installation type"),
        _f("work_date", "Work date", "date"),
        _f("scope", "Scope of work", "textarea"),
        _f("tested_items", "Tested items", "chips"),
        _f("test_results", "Test results (test/result)", "test_results"),
        _f("compliance_statement", "Compliance statement", "textarea"),
        _f("signed_by", "Signed by"),
        _f("signature", "Signature / ID"),
        _f("signed_at", "Signed at", "datetime"),
    ],
    "ai_prompt": None,
    "pdf": render_ccew,
})

register_doc_type({
    "id": "plumbing_coc", "category": "trade",
    "label": "Plumbing NOW / Certificate of Compliance",
    "blurb": "Notice of Work & Certificate of Compliance (AS/NZS 3500)",
    "counter_prefix": "PLB",
    "fields": [
        _f("licensee_name", "Licensee name", required=True),
        _f("licence_no", "Licence number"),
        _f("company_name", "Company"),
        _f("job_site", "Job site"),
        _f("job_type", "Job type (sanitary/water/drain/gas)"),
        _f("authority", "Council / authority"),
        _f("inspection_required", "Inspection required (Y/N)"),
        _f("work_date", "Work date", "date"),
        _f("now_reference", "NOW reference"),
        _f("scope", "Scope of work", "textarea"),
        _f("work_items", "Work items (item/standard/result)", "plumbing_items"),
        _f("compliance_statement", "Compliance statement", "textarea"),
        _f("signed_by", "Signed by"),
        _f("signature", "Signature / ID"),
        _f("signed_at", "Signed at", "datetime"),
    ],
    "ai_prompt": None,
    "pdf": render_plumbing_coc,
})

register_doc_type({
    "id": "hot_work_permit", "category": "safety",
    "label": "Hot Work Permit",
    "blurb": "Welding / cutting / grinding — fire risk control",
    "counter_prefix": "HWP",
    "fields": [
        _f("location", "Location", required=True),
        _f("work_description", "Nature of work", "textarea"),
        _f("start_datetime", "Start date/time", "datetime"),
        _f("duration", "Duration"),
        _f("authorised_workers", "Authorised workers", "chips"),
        _f("fire_watch_person", "Fire watch person"),
        _f("extinguisher_on_site", "Extinguisher on site"),
        _f("post_work_watch_mins", "Post-work watch (mins)", "number"),
        _f("precautions", "Pre-start precautions (item/done)", "checklist"),
        _f("atmosphere_tested", "Atmosphere tested (Y/N)"),
        _f("atmosphere_tested_by", "Tested by"),
        _f("atmosphere_tested_at", "Test time", "datetime"),
        _f("emergency_procedures", "Emergency procedures", "textarea"),
        _f("authorised_by", "Authorised by"),
        _f("authorised_by_signature", "Auth signature / ID"),
        _f("authorised_at", "Authorised at", "datetime"),
        _f("rescinded_at", "Rescinded at", "datetime"),
    ],
    "ai_prompt": None,
    "pdf": render_hot_work_permit,
})

register_doc_type({
    "id": "excavation_permit", "category": "safety",
    "label": "Excavation Permit",
    "blurb": "Ground disturbance control (WHS Reg 304)",
    "counter_prefix": "EXP",
    "fields": [
        _f("location", "Location", required=True),
        _f("work_description", "Nature of work", "textarea"),
        _f("depth_metres", "Depth (metres)", "number"),
        _f("start_datetime", "Start date/time", "datetime"),
        _f("duration", "Duration"),
        _f("services_checked", "Services check — DBYD (item/done)", "checklist"),
        _f("barricades", "Barricades & signage", "chips"),
        _f("spoil_location", "Spoil location", "textarea"),
        _f("plant_equipment", "Plant & equipment", "chips"),
        _f("authorised_workers", "Authorised workers", "chips"),
        _f("emergency_procedures", "Emergency procedures", "textarea"),
        _f("authorised_by", "Authorised by"),
        _f("authorised_by_signature", "Auth signature / ID"),
        _f("authorised_at", "Authorised at", "datetime"),
        _f("rescinded_at", "Rescinded at", "datetime"),
    ],
    "ai_prompt": None,
    "pdf": render_excavation_permit,
})

register_doc_type({
    "id": "lift_plan", "category": "plant",
    "label": "Lift Plan",
    "blurb": "Crane / lifting operations — AS 2550",
    "counter_prefix": "LIFT",
    "fields": [
        _f("site", "Site", required=True),
        _f("lift_date", "Lift date", "date"),
        _f("load_description", "Load description"),
        _f("load_weight_kg", "Load weight (kg)", "number"),
        _f("working_radius", "Working radius (m)"),
        _f("lift_height", "Lift height (m)"),
        _f("crane_type", "Crane type"),
        _f("crane_capacity_kg", "Crane capacity (kg)", "number"),
        _f("capacity_utilised", "Capacity utilised (%)"),
        _f("rigging_config", "Rigging configuration"),
        _f("dogger_name", "Dogger name"),
        _f("rigger_name", "Rigger name"),
        _f("crane_operator", "Crane operator"),
        _f("lift_sequence", "Lift sequence", "textarea"),
        _f("hazards", "Hazards", "chips"),
        _f("controls", "Controls", "chips"),
        _f("exclusion_zone", "Exclusion zone", "textarea"),
        _f("prepared_by", "Prepared by"),
        _f("approved_by", "Approved by"),
        _f("approved_at", "Approved at", "datetime"),
    ],
    "ai_prompt": ("Given a load description + crane type, return JSON: "
                  "{hazards:[str], controls:[str], lift_sequence, exclusion_zone}"),
    "pdf": render_lift_plan,
})

register_doc_type({
    "id": "fall_protection", "category": "safety",
    "label": "Fall Protection Plan",
    "blurb": "Working at heights (WHS Reg 78)",
    "counter_prefix": "FPP",
    "fields": [
        _f("site", "Site", required=True),
        _f("work_area", "Work area"),
        _f("height_metres", "Height (metres)", "number"),
        _f("work_date", "Work date", "date"),
        _f("work_description", "Nature of work", "textarea"),
        _f("edge_protection", "Edge protection", "chips"),
        _f("fall_arrest_systems", "Fall arrest systems", "chips"),
        _f("anchor_points", "Anchor points", "textarea"),
        _f("rescue_plan", "Rescue plan", "textarea"),
        _f("authorised_workers", "Authorised workers", "chips"),
        _f("pre_start_check", "Pre-start check (item/done)", "checklist"),
        _f("prepared_by", "Prepared by"),
        _f("approved_by", "Approved by"),
        _f("approved_at", "Approved at", "datetime"),
    ],
    "ai_prompt": ("Given a work area + height, return JSON: {edge_protection:[str], "
                  "fall_arrest_systems:[str], anchor_points, rescue_plan}"),
    "pdf": render_fall_protection,
})




async def _call_claude(system: str, user_prompt: str, fallback: Any,
                       llm_chat_cls, user_message_cls, llm_key: str,
                       timeout: float = 55.0) -> Any:
    try:
        chat = llm_chat_cls(
            api_key=llm_key, session_id=f"doc_{uuid.uuid4().hex[:8]}",
            system_message=system,
        ).with_model("anthropic", "claude-sonnet-4-5-20250929")

        def _run():
            return asyncio.run(chat.send_message(user_message_cls(text=user_prompt)))

        raw = await asyncio.wait_for(asyncio.to_thread(_run), timeout=timeout)
        txt = raw if isinstance(raw, str) else str(raw)
        m = re.search(r"\{[\s\S]*\}|\[[\s\S]*\]", txt)
        if m:
            return _json.loads(m.group(0))
        return fallback
    except Exception:
        return fallback


def register_docs_routes(app_db, get_current_user, llm_chat_cls, user_message_cls, llm_key):

    @docs_router.get("/docs/types")
    async def list_doc_types():
        """Returns lightweight catalog for the hub UI. Field definitions live
        on each type and are needed by the form renderer."""
        out = []
        for t in DOC_TYPES.values():
            out.append({k: v for k, v in t.items() if k != "pdf"})
        return {
            "categories": CATEGORIES,
            "types": out,
            "states": list(STATE_REGULATORS.keys()),
        }

    async def _next_ref(user_id: str, prefix: str) -> str:
        year = datetime.now(timezone.utc).year
        res = await app_db.docs_counters.find_one_and_update(
            {"user_id": user_id, "year": year, "prefix": prefix},
            {"$inc": {"count": 1}},
            upsert=True, return_document=True,
        )
        n = (res or {}).get("count") or 1
        return f"{prefix}-{year}-{n:04d}"

    @docs_router.post("/docs/{doc_type}")
    async def create_doc(doc_type: str, body: dict, current_user=Depends(get_current_user)):
        spec = DOC_TYPES.get(doc_type)
        if not spec:
            raise HTTPException(404, f"Unknown doc type: {doc_type}")
        doc_id = f"doc_{uuid.uuid4().hex[:10]}"
        ref = await _next_ref(current_user.user_id, spec["counter_prefix"])
        now = datetime.now(timezone.utc).isoformat()
        doc = {
            "doc_id": doc_id,
            "reference": ref,
            "user_id": current_user.user_id,
            "doc_type": doc_type,
            "category": spec["category"],
            "label": spec["label"],
            "status": "draft",
            "version": 1,
            "created_at": now,
            "updated_at": now,
            "retention_until": (datetime.now(timezone.utc) + timedelta(days=5*365)).isoformat(),
            **{k: v for k, v in body.items() if k not in ("_id", "doc_id", "reference",
                                                          "user_id", "created_at")},
        }
        await app_db.compliance_docs.insert_one({**doc})
        return {k: v for k, v in doc.items() if k != "_id"}

    @docs_router.get("/docs")
    async def list_docs(doc_type: Optional[str] = None,
                         category: Optional[str] = None,
                         current_user=Depends(get_current_user)):
        q = {"user_id": current_user.user_id}
        if doc_type:
            q["doc_type"] = doc_type
        if category:
            q["category"] = category
        rows = await app_db.compliance_docs.find(q, {"_id": 0}).sort("created_at", -1).to_list(500)
        return rows

    @docs_router.get("/docs/{doc_id}")
    async def get_doc(doc_id: str, current_user=Depends(get_current_user)):
        doc = await app_db.compliance_docs.find_one(
            {"doc_id": doc_id, "user_id": current_user.user_id}, {"_id": 0})
        if not doc:
            raise HTTPException(404, "Document not found")
        return doc

    @docs_router.patch("/docs/{doc_id}")
    async def update_doc(doc_id: str, body: dict, current_user=Depends(get_current_user)):
        for k in ("doc_id", "user_id", "reference", "created_at", "doc_type", "category"):
            body.pop(k, None)
        body["updated_at"] = datetime.now(timezone.utc).isoformat()
        res = await app_db.compliance_docs.update_one(
            {"doc_id": doc_id, "user_id": current_user.user_id}, {"$set": body}
        )
        if res.matched_count == 0:
            raise HTTPException(404, "Document not found")
        return await app_db.compliance_docs.find_one(
            {"doc_id": doc_id, "user_id": current_user.user_id}, {"_id": 0}
        )

    @docs_router.delete("/docs/{doc_id}")
    async def delete_doc(doc_id: str, current_user=Depends(get_current_user)):
        doc = await app_db.compliance_docs.find_one(
            {"doc_id": doc_id, "user_id": current_user.user_id})
        if not doc:
            raise HTTPException(404, "Document not found")
        if doc.get("status") != "archived":
            await app_db.compliance_docs.update_one(
                {"doc_id": doc_id, "user_id": current_user.user_id},
                {"$set": {"status": "archived",
                          "archived_at": datetime.now(timezone.utc).isoformat()}})
            return {"archived": True}
        await app_db.compliance_docs.delete_one(
            {"doc_id": doc_id, "user_id": current_user.user_id})
        return {"deleted": True}

    @docs_router.post("/docs/{doc_id}/ai-draft")
    async def ai_draft(doc_id: str, current_user=Depends(get_current_user)):
        doc = await app_db.compliance_docs.find_one(
            {"doc_id": doc_id, "user_id": current_user.user_id}, {"_id": 0})
        if not doc:
            raise HTTPException(404, "Document not found")
        spec = DOC_TYPES.get(doc.get("doc_type"))
        if not spec or not spec.get("ai_prompt"):
            raise HTTPException(400, "AI draft not available for this doc type")
        system = ("You are a senior Australian WHS consultant. Output ONLY valid JSON "
                  "matching the requested schema, no prose.")
        # Context from existing doc fields
        ctx = {k: v for k, v in doc.items() if k in
               ("task", "activity", "site", "site_name", "topic", "trade", "worker_role", "company_name")}
        user_prompt = f"Context: {_json.dumps(ctx)}\n\nSchema: {spec['ai_prompt']}"
        res = await _call_claude(system, user_prompt, {}, llm_chat_cls, user_message_cls, llm_key)
        return res or {}

    @docs_router.get("/docs/{doc_id}/pdf")
    async def get_pdf(doc_id: str, current_user=Depends(get_current_user)):
        doc = await app_db.compliance_docs.find_one(
            {"doc_id": doc_id, "user_id": current_user.user_id}, {"_id": 0})
        if not doc:
            raise HTTPException(404, "Document not found")
        spec = DOC_TYPES.get(doc.get("doc_type"))
        if not spec:
            raise HTTPException(400, "Unknown doc type")
        try:
            from weasyprint import HTML
        except Exception:
            raise HTTPException(503, "PDF engine unavailable")
        html = spec["pdf"](doc)
        pdf_bytes = await asyncio.to_thread(lambda: HTML(string=html).write_pdf())
        return Response(
            content=pdf_bytes, media_type="application/pdf",
            headers={"Content-Disposition": f'attachment; filename="{doc.get("reference")}.pdf"'})

    return docs_router
