/**
 * Dynamic form renderer for Document Library doc types.
 * Reads the field schema from /api/docs/types and renders appropriate inputs
 * for each field type. Supports create + edit via URL params.
 */
import { useEffect, useMemo, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import api from "@/lib/api";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import {
  Plus, Trash, FloppyDisk, FilePdf, Sparkle, ArrowLeft, CheckCircle,
} from "@phosphor-icons/react";
import { toast } from "sonner";

const STATES = ["NSW", "VIC", "QLD", "WA", "SA", "TAS", "NT", "ACT"];

export default function DocumentForm() {
  const { doc_type, doc_id } = useParams();
  const nav = useNavigate();
  const [types, setTypes] = useState(null);
  const [form, setForm] = useState({});
  const [saving, setSaving] = useState(false);
  const [busyAi, setBusyAi] = useState(false);

  useEffect(() => {
    api.get("/docs/types").then((r) => setTypes(r.data));
  }, []);

  useEffect(() => {
    if (!doc_id) return;
    api.get(`/docs/${doc_id}`).then((r) => setForm(r.data));
  }, [doc_id]);

  const spec = useMemo(() => {
    if (!types) return null;
    const tId = form.doc_type || doc_type;
    return types.types.find((t) => t.id === tId);
  }, [types, form.doc_type, doc_type]);

  const patch = (k, v) => setForm((f) => ({ ...f, [k]: v }));

  const save = async ({ navigate = false } = {}) => {
    setSaving(true);
    try {
      let res;
      if (form.doc_id) {
        res = await api.patch(`/docs/${form.doc_id}`, form);
      } else {
        res = await api.post(`/docs/${doc_type}`, form);
      }
      setForm(res.data);
      toast.success(`Saved — ${res.data.reference}`);
      if (navigate) nav(`/dashboard/document-library/${res.data.doc_type}`);
    } catch (e) {
      toast.error(e?.response?.data?.detail || "Save failed");
    }
    setSaving(false);
  };

  const aiDraft = async () => {
    if (!form.doc_id) { toast.error("Save first to use AI draft"); return; }
    setBusyAi(true);
    try {
      const r = await api.post(`/docs/${form.doc_id}/ai-draft`);
      setForm((f) => ({ ...f, ...(r.data || {}) }));
      toast.success("AI draft applied — review and edit");
    } catch (e) {
      toast.error(e?.response?.data?.detail || "AI draft failed");
    }
    setBusyAi(false);
  };

  const downloadPdf = () => {
    if (!form.doc_id) { toast.error("Save first"); return; }
    const token = localStorage.getItem("st_token");
    const backend = process.env.REACT_APP_BACKEND_URL;
    fetch(`${backend}/api/docs/${form.doc_id}/pdf`, { headers: { Authorization: `Bearer ${token}` } })
      .then((r) => r.blob()).then((b) => {
        const url = URL.createObjectURL(b);
        const a = document.createElement("a");
        a.href = url; a.download = `${form.reference || "document"}.pdf`; a.click();
        URL.revokeObjectURL(url);
        toast.success("PDF downloaded");
      }).catch(() => toast.error("PDF failed"));
  };

  if (!types) return <div className="p-8 text-sm text-muted-foreground">Loading…</div>;
  if (!spec) return <div className="p-8 text-sm text-muted-foreground">Unknown doc type.</div>;

  const aiAvailable = !!spec.ai_prompt;

  return (
    <div className="space-y-4" data-testid="doc-form">
      <div className="border-b-2 border-ink pb-3 flex items-end justify-between flex-wrap gap-2">
        <div>
          <div className="label-eyebrow">/ Document Library · {spec.label}</div>
          <h1 className="font-display text-3xl font-black tracking-tighter mt-1">
            {form.doc_id ? form.reference : `New ${spec.label}`}
          </h1>
          <p className="text-xs text-muted-foreground mt-1">{spec.blurb}</p>
        </div>
        <div className="flex gap-2">
          <Button variant="outline" className="btn-sharp border-ink" onClick={() => nav(-1)} data-testid="doc-back">
            <ArrowLeft className="mr-2" />Back
          </Button>
        </div>
      </div>

      <div className="bg-warning/20 border-2 border-ink p-3 text-xs leading-relaxed" data-testid="doc-legal-notice">
        <strong className="block label-eyebrow mb-1">LEGAL NOTICE</strong>
        This document was generated by SafeTradie using AI assistance. It must be reviewed and
        tailored to your specific workplace before use. SafeTradie does not provide legal or
        professional advice.
      </div>

      <div className="bg-background border border-border p-4 space-y-3">
        {spec.fields.map((f) => (
          <FieldRenderer key={f.key} field={f} value={form[f.key]} onChange={(v) => patch(f.key, v)} />
        ))}
      </div>

      <div className="flex flex-wrap gap-2">
        <Button className="btn-sharp bg-ink text-white hover:bg-authority" onClick={() => save()} disabled={saving} data-testid="doc-save">
          <FloppyDisk className="mr-2" weight="fill" />{saving ? "Saving…" : "Save"}
        </Button>
        {aiAvailable && (
          <Button variant="outline" className="btn-sharp border-ink" onClick={aiDraft} disabled={busyAi || !form.doc_id} data-testid="doc-ai-draft">
            <Sparkle className="mr-2" weight="fill" />{busyAi ? "Drafting…" : "AI draft"}
          </Button>
        )}
        <Button variant="outline" className="btn-sharp border-ink" onClick={downloadPdf} disabled={!form.doc_id} data-testid="doc-pdf">
          <FilePdf className="mr-2" weight="fill" />Download PDF
        </Button>
        <Button variant="outline" className="btn-sharp bg-warning text-ink border-ink" onClick={() => save({ navigate: true })} disabled={saving} data-testid="doc-finish">
          <CheckCircle className="mr-2" weight="fill" />Finish
        </Button>
      </div>
    </div>
  );
}

// ===== FIELD RENDERERS =====
function FieldRenderer({ field, value, onChange }) {
  const t = field.type || "text";
  if (t === "textarea") {
    return (
      <div><Label className="label-eyebrow">{field.label}</Label>
        <Textarea rows={3} value={value || ""} onChange={(e) => onChange(e.target.value)} className="rounded-none border-ink mt-1" data-testid={`field-${field.key}`} />
      </div>
    );
  }
  if (t === "state") {
    return (
      <div><Label className="label-eyebrow">{field.label}</Label>
        <Select value={value || "NSW"} onValueChange={onChange}>
          <SelectTrigger className="h-10 rounded-none border-ink mt-1 w-32" data-testid={`field-${field.key}`}><SelectValue /></SelectTrigger>
          <SelectContent>{STATES.map((s) => <SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent>
        </Select>
      </div>
    );
  }
  if (t === "date" || t === "datetime") {
    return (
      <div><Label className="label-eyebrow">{field.label}</Label>
        <Input type={t === "datetime" ? "datetime-local" : "date"} value={value || ""} onChange={(e) => onChange(e.target.value)} className="h-10 rounded-none border-ink mt-1 w-64" data-testid={`field-${field.key}`} />
      </div>
    );
  }
  if (t === "number") {
    return (
      <div><Label className="label-eyebrow">{field.label}</Label>
        <Input type="number" value={value || ""} onChange={(e) => onChange(e.target.value)} className="h-10 rounded-none border-ink mt-1 w-32" data-testid={`field-${field.key}`} />
      </div>
    );
  }
  if (t === "chips") {
    return <ChipsField field={field} value={value} onChange={onChange} />;
  }
  if (t === "jsa_steps") {
    return <JsaStepsField field={field} value={value} onChange={onChange} />;
  }
  if (t === "risk_items") {
    return <RiskItemsField field={field} value={value} onChange={onChange} />;
  }
  if (t === "checklist") {
    return <ChecklistField field={field} value={value} onChange={onChange} />;
  }
  if (t === "chemicals") {
    return <TableField field={field} value={value} onChange={onChange}
                       cols={[{k:"product",l:"Product"},{k:"manufacturer",l:"Manufacturer"},{k:"sds_date",l:"SDS date"},{k:"hazard_class",l:"Hazard class"},{k:"location",l:"Location"},{k:"max_quantity",l:"Max qty"},{k:"ppe",l:"PPE"}]} />;
  }
  if (t === "contacts") {
    return <TableField field={field} value={value} onChange={onChange}
                       cols={[{k:"name",l:"Name"},{k:"role",l:"Role"},{k:"phone",l:"Phone"}]} />;
  }
  if (t === "equipment") {
    return <TableField field={field} value={value} onChange={onChange}
                       cols={[{k:"equipment",l:"Equipment"},{k:"location",l:"Location"}]} />;
  }
  if (t === "attendees") {
    return <TableField field={field} value={value} onChange={onChange}
                       cols={[{k:"name",l:"Attendee name"}]} />;
  }
  if (t === "atmosphere") {
    return <AtmosphereField field={field} value={value} onChange={onChange} />;
  }
  if (t === "emergency_procs") {
    return <EmergencyProcsField field={field} value={value} onChange={onChange} />;
  }
  // default text
  return (
    <div><Label className="label-eyebrow">{field.label}{field.required ? " *" : ""}</Label>
      <Input value={value || ""} onChange={(e) => onChange(e.target.value)} className="h-10 rounded-none border-ink mt-1" data-testid={`field-${field.key}`} />
    </div>
  );
}

function ChipsField({ field, value, onChange }) {
  const arr = Array.isArray(value) ? value : [];
  const [entry, setEntry] = useState("");
  const add = () => { if (entry.trim()) { onChange([...arr, entry.trim()]); setEntry(""); } };
  return (
    <div>
      <Label className="label-eyebrow">{field.label}</Label>
      <div className="flex gap-2 mt-1">
        <Input value={entry} onChange={(e) => setEntry(e.target.value)}
               onKeyDown={(e) => e.key === "Enter" && (e.preventDefault(), add())}
               className="h-10 rounded-none border-ink" placeholder="Type and press Enter or +"
               data-testid={`chip-input-${field.key}`} />
        <Button type="button" variant="outline" className="btn-sharp border-ink h-10" onClick={add}><Plus /></Button>
      </div>
      <div className="flex flex-wrap gap-1 mt-2" data-testid={`field-${field.key}`}>
        {arr.map((x, i) => (
          <span key={i} className="inline-flex items-center gap-1 bg-muted px-2 py-1 text-xs border border-border">
            {x}
            <button type="button" onClick={() => onChange(arr.filter((_, j) => j !== i))} className="text-destructive"><Trash size={10} /></button>
          </span>
        ))}
      </div>
    </div>
  );
}

function JsaStepsField({ field, value, onChange }) {
  const arr = Array.isArray(value) ? value : [];
  const patch = (i, k, v) => { const n = [...arr]; n[i] = { ...n[i], [k]: v }; onChange(n); };
  const patchArr = (i, k, j, v) => { const n = [...arr]; const a = [...(n[i]?.[k] || [])]; a[j] = v; n[i] = { ...n[i], [k]: a }; onChange(n); };
  const addToArr = (i, k) => { const n = [...arr]; n[i] = { ...n[i], [k]: [...(n[i]?.[k] || []), ""] }; onChange(n); };
  const add = () => onChange([...arr, { step: "", hazards: [""], controls: [""] }]);
  const rm = (i) => onChange(arr.filter((_, j) => j !== i));
  return (
    <div>
      <Label className="label-eyebrow">{field.label}</Label>
      <div className="space-y-2 mt-1" data-testid={`field-${field.key}`}>
        {arr.map((s, i) => (
          <div key={i} className="border-2 border-ink p-3 space-y-2">
            <div className="flex gap-2">
              <Input value={s.step || ""} onChange={(e) => patch(i, "step", e.target.value)}
                     className="h-10 rounded-none border-ink flex-1" placeholder={`Step ${i+1}`} />
              <Button type="button" variant="ghost" size="sm" className="text-destructive" onClick={() => rm(i)}><Trash /></Button>
            </div>
            <div>
              <div className="label-eyebrow">Hazards</div>
              {(s.hazards || []).map((h, j) => (
                <Input key={j} value={h} onChange={(e) => patchArr(i, "hazards", j, e.target.value)} className="h-9 rounded-none border-ink mt-1" />
              ))}
              <button type="button" className="text-xs underline mt-1" onClick={() => addToArr(i, "hazards")}>+ Add hazard</button>
            </div>
            <div>
              <div className="label-eyebrow">Controls</div>
              {(s.controls || []).map((c, j) => (
                <Input key={j} value={c} onChange={(e) => patchArr(i, "controls", j, e.target.value)} className="h-9 rounded-none border-ink mt-1" />
              ))}
              <button type="button" className="text-xs underline mt-1" onClick={() => addToArr(i, "controls")}>+ Add control</button>
            </div>
          </div>
        ))}
      </div>
      <Button type="button" variant="outline" size="sm" className="btn-sharp border-ink mt-2" onClick={add}><Plus className="mr-1" />Add step</Button>
    </div>
  );
}

function RiskItemsField({ field, value, onChange }) {
  const arr = Array.isArray(value) ? value : [];
  const patch = (i, k, v) => { const n = [...arr]; n[i] = { ...n[i], [k]: v }; onChange(n); };
  const add = () => onChange([...arr, { hazard: "", inherent_likelihood: 3, inherent_consequence: 3, controls: "", residual_likelihood: 2, residual_consequence: 2, responsible: "" }]);
  const rm = (i) => onChange(arr.filter((_, j) => j !== i));
  return (
    <div>
      <Label className="label-eyebrow">{field.label}</Label>
      <div className="space-y-2 mt-1" data-testid={`field-${field.key}`}>
        {arr.map((it, i) => (
          <div key={i} className="border-2 border-ink p-3 grid grid-cols-2 md:grid-cols-4 gap-2">
            <div className="col-span-2 md:col-span-4 flex gap-2">
              <Input value={it.hazard || ""} onChange={(e) => patch(i, "hazard", e.target.value)} placeholder="Hazard" className="h-10 rounded-none border-ink flex-1" />
              <Button type="button" variant="ghost" size="sm" className="text-destructive" onClick={() => rm(i)}><Trash /></Button>
            </div>
            <InputNum label="Inherent L" value={it.inherent_likelihood} onChange={(v) => patch(i, "inherent_likelihood", v)} />
            <InputNum label="Inherent C" value={it.inherent_consequence} onChange={(v) => patch(i, "inherent_consequence", v)} />
            <InputNum label="Residual L" value={it.residual_likelihood} onChange={(v) => patch(i, "residual_likelihood", v)} />
            <InputNum label="Residual C" value={it.residual_consequence} onChange={(v) => patch(i, "residual_consequence", v)} />
            <div className="col-span-2 md:col-span-4">
              <Label className="text-xs">Controls</Label>
              <Textarea rows={2} value={it.controls || ""} onChange={(e) => patch(i, "controls", e.target.value)} className="rounded-none border-ink mt-1" />
            </div>
            <div className="col-span-2 md:col-span-4">
              <Label className="text-xs">Responsible</Label>
              <Input value={it.responsible || ""} onChange={(e) => patch(i, "responsible", e.target.value)} className="h-9 rounded-none border-ink mt-1" />
            </div>
          </div>
        ))}
      </div>
      <Button type="button" variant="outline" size="sm" className="btn-sharp border-ink mt-2" onClick={add}><Plus className="mr-1" />Add hazard</Button>
    </div>
  );
}

function InputNum({ label, value, onChange }) {
  return (
    <div>
      <Label className="text-xs">{label}</Label>
      <Input type="number" min="1" max="5" value={value || ""} onChange={(e) => onChange(Number(e.target.value))} className="h-9 rounded-none border-ink mt-1" />
    </div>
  );
}

function ChecklistField({ field, value, onChange }) {
  const arr = Array.isArray(value) ? value : [];
  const [entry, setEntry] = useState("");
  const add = () => { if (entry.trim()) { onChange([...arr, { item: entry.trim(), done: false }]); setEntry(""); } };
  const toggle = (i) => { const n = [...arr]; n[i] = { ...n[i], done: !n[i].done }; onChange(n); };
  const rm = (i) => onChange(arr.filter((_, j) => j !== i));
  return (
    <div>
      <Label className="label-eyebrow">{field.label}</Label>
      <div className="flex gap-2 mt-1">
        <Input value={entry} onChange={(e) => setEntry(e.target.value)}
               onKeyDown={(e) => e.key === "Enter" && (e.preventDefault(), add())}
               className="h-10 rounded-none border-ink flex-1" placeholder="Checklist item" />
        <Button type="button" variant="outline" className="btn-sharp border-ink h-10" onClick={add}><Plus /></Button>
      </div>
      <div className="mt-2 space-y-1" data-testid={`field-${field.key}`}>
        {arr.map((c, i) => (
          <div key={i} className="flex items-center gap-2 text-sm border border-border p-2">
            <input type="checkbox" checked={!!c.done} onChange={() => toggle(i)} />
            <span className={c.done ? "line-through text-muted-foreground flex-1" : "flex-1"}>{c.item}</span>
            <button type="button" onClick={() => rm(i)} className="text-destructive text-xs"><Trash size={12} /></button>
          </div>
        ))}
      </div>
    </div>
  );
}

function TableField({ field, value, onChange, cols }) {
  const arr = Array.isArray(value) ? value : [];
  const add = () => { const row = {}; cols.forEach((c) => row[c.k] = ""); onChange([...arr, row]); };
  const patch = (i, k, v) => { const n = [...arr]; n[i] = { ...n[i], [k]: v }; onChange(n); };
  const rm = (i) => onChange(arr.filter((_, j) => j !== i));
  return (
    <div>
      <Label className="label-eyebrow">{field.label}</Label>
      <div className="border border-ink overflow-x-auto mt-1" data-testid={`field-${field.key}`}>
        <table className="w-full text-xs">
          <thead className="bg-ink text-warning">
            <tr>
              {cols.map((c) => <th key={c.k} className="text-left p-2 label-eyebrow">{c.l}</th>)}
              <th className="w-8"></th>
            </tr>
          </thead>
          <tbody>
            {arr.length === 0 && <tr><td colSpan={cols.length + 1} className="text-center p-3 text-muted-foreground">No entries yet</td></tr>}
            {arr.map((row, i) => (
              <tr key={i} className="border-t border-border">
                {cols.map((c) => (
                  <td key={c.k} className="p-1">
                    <Input value={row[c.k] || ""} onChange={(e) => patch(i, c.k, e.target.value)} className="h-8 rounded-none border-ink" />
                  </td>
                ))}
                <td><button type="button" onClick={() => rm(i)} className="text-destructive p-1"><Trash size={12} /></button></td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      <Button type="button" variant="outline" size="sm" className="btn-sharp border-ink mt-2" onClick={add}><Plus className="mr-1" />Add row</Button>
    </div>
  );
}

function AtmosphereField({ field, value, onChange }) {
  const v = value || {};
  const patch = (k, val) => onChange({ ...v, [k]: val });
  return (
    <div>
      <Label className="label-eyebrow">{field.label}</Label>
      <div className="grid grid-cols-2 md:grid-cols-3 gap-2 border border-ink p-3 mt-1" data-testid={`field-${field.key}`}>
        <div><Label className="text-xs">Oxygen %</Label><Input value={v.oxygen || ""} onChange={(e) => patch("oxygen", e.target.value)} className="h-9 rounded-none border-ink mt-1" /></div>
        <div><Label className="text-xs">LEL %</Label><Input value={v.lel || ""} onChange={(e) => patch("lel", e.target.value)} className="h-9 rounded-none border-ink mt-1" /></div>
        <div><Label className="text-xs">Toxic gases (ppm)</Label><Input value={v.toxic_gases || ""} onChange={(e) => patch("toxic_gases", e.target.value)} className="h-9 rounded-none border-ink mt-1" /></div>
        <div><Label className="text-xs">Tested by</Label><Input value={v.tested_by || ""} onChange={(e) => patch("tested_by", e.target.value)} className="h-9 rounded-none border-ink mt-1" /></div>
        <div><Label className="text-xs">Test time</Label><Input type="datetime-local" value={v.tested_at || ""} onChange={(e) => patch("tested_at", e.target.value)} className="h-9 rounded-none border-ink mt-1" /></div>
      </div>
    </div>
  );
}

function EmergencyProcsField({ field, value, onChange }) {
  const v = value || {};
  const patch = (k, val) => onChange({ ...v, [k]: val });
  const types = [
    ["fire", "Fire"], ["medical", "Medical emergency"], ["chemical_spill", "Chemical spill"],
    ["electric_shock", "Electric shock"], ["fall_from_height", "Fall from height"],
    ["structural_collapse", "Structural collapse"], ["flood", "Flood / water ingress"],
  ];
  return (
    <div>
      <Label className="label-eyebrow">{field.label}</Label>
      <div className="space-y-2 mt-1" data-testid={`field-${field.key}`}>
        {types.map(([k, l]) => (
          <div key={k}>
            <Label className="text-xs">{l}</Label>
            <Textarea rows={2} value={v[k] || ""} onChange={(e) => patch(k, e.target.value)} className="rounded-none border-ink mt-1" />
          </div>
        ))}
      </div>
    </div>
  );
}
