/**
 * Document Library Hub — entry point for all non-SWMS compliance documents.
 * 6 category tiles, recent docs list, quick-generate dropdown.
 */
import { useEffect, useState, useMemo } from "react";
import { Link, useNavigate } from "react-router-dom";
import api from "@/lib/api";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import {
  ShieldCheck, UserCircle, Handshake, Warning, Wrench, ClipboardText,
  ArrowRight, Plus, FileText,
} from "@phosphor-icons/react";

const ICONS = { ShieldCheck, UserCircle, Handshake, Warning, Wrench, Clipboard: ClipboardText };

export default function DocumentLibraryHub() {
  const [cat, setCat] = useState(null);
  const [rows, setRows] = useState([]);
  const [loading, setLoading] = useState(true);
  const [quickType, setQuickType] = useState("");
  const nav = useNavigate();

  useEffect(() => {
    Promise.all([
      api.get("/docs/types"),
      api.get("/docs"),
    ]).then(([t, r]) => {
      setCat(t.data);
      setRows(r.data || []);
      setLoading(false);
    }).catch(() => setLoading(false));
  }, []);

  const recent = useMemo(() => (rows || []).slice(0, 5), [rows]);
  const countByCat = useMemo(() => {
    const m = {};
    for (const r of rows) m[r.category] = (m[r.category] || 0) + 1;
    return m;
  }, [rows]);

  if (loading) return <div className="p-8 text-sm text-muted-foreground">Loading library…</div>;
  if (!cat) return <div className="p-8 text-sm text-muted-foreground">Could not load library.</div>;

  return (
    <div className="space-y-6" data-testid="doc-library-hub">
      <div className="border-b-2 border-ink pb-4">
        <div className="label-eyebrow">/ Documents · Document Library</div>
        <h1 className="font-display text-3xl md:text-4xl font-black tracking-tighter mt-1">
          Generate Any Compliance Document
        </h1>
        <p className="text-sm text-muted-foreground mt-2 max-w-2xl">
          Every document your trade business needs — generated by AI, tailored to your business,
          ready to sign and store. Legal retention is enforced automatically.
        </p>
      </div>

      {/* Quick generate */}
      <div className="bg-ink text-white p-4 flex items-center gap-3 flex-wrap">
        <div className="label-eyebrow text-warning whitespace-nowrap">Quick generate</div>
        <div className="flex-1 min-w-[200px]">
          <Select value={quickType} onValueChange={setQuickType}>
            <SelectTrigger className="h-10 rounded-none border-warning bg-white text-ink" data-testid="quick-type-select">
              <SelectValue placeholder="Pick a document type…" />
            </SelectTrigger>
            <SelectContent>
              {cat.types.map((t) => <SelectItem key={t.id} value={t.id}>{t.label}</SelectItem>)}
            </SelectContent>
          </Select>
        </div>
        <Button
          className="btn-sharp bg-warning text-ink hover:bg-yellow-400 h-10"
          disabled={!quickType}
          onClick={() => nav(`/dashboard/document-library/${quickType}/new`)}
          data-testid="quick-generate-btn"
        >
          Generate <ArrowRight className="ml-2" />
        </Button>
      </div>

      {/* Category tiles */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
        {cat.categories.map((c) => {
          const IconC = ICONS[c.icon] || FileText;
          const count = countByCat[c.id] || 0;
          const types = cat.types.filter((t) => t.category === c.id);
          return (
            <div key={c.id} className="border border-border hover:border-ink bg-background p-4 flex flex-col" data-testid={`cat-tile-${c.id}`}>
              <div className="flex items-start justify-between">
                <IconC size={36} weight="duotone" />
                <div className="text-right">
                  <div className="font-display text-2xl font-black">{count}</div>
                  <div className="label-eyebrow text-muted-foreground">generated</div>
                </div>
              </div>
              <div className="font-display text-lg font-black mt-3 tracking-tighter">{c.label}</div>
              <div className="text-xs text-muted-foreground mt-1">{c.blurb}</div>
              <div className="border-t border-border mt-3 pt-2 space-y-1 flex-1">
                {types.length === 0 && (
                  <div className="text-xs text-muted-foreground italic">Coming soon — this category will land in Phase 3.</div>
                )}
                {types.map((t) => (
                  <Link
                    key={t.id}
                    to={`/dashboard/document-library/${t.id}`}
                    className="flex items-center justify-between text-xs hover:bg-warning hover:text-ink p-1.5 border border-transparent hover:border-ink"
                    data-testid={`cat-type-${t.id}`}
                  >
                    <span className="font-bold">{t.label}</span>
                    <ArrowRight size={12} />
                  </Link>
                ))}
              </div>
            </div>
          );
        })}
      </div>

      {/* Recent */}
      {recent.length > 0 && (
        <div>
          <h2 className="font-display text-xl font-black tracking-tighter mb-2">Recently generated</h2>
          <div className="bg-background border border-border divide-y divide-border">
            {recent.map((r) => (
              <Link
                key={r.doc_id}
                to={`/dashboard/document-library/doc/${r.doc_id}`}
                className="flex items-center justify-between p-3 hover:bg-muted"
                data-testid={`recent-${r.doc_id}`}
              >
                <div>
                  <div className="font-bold text-sm">{r.reference}</div>
                  <div className="text-xs text-muted-foreground">{r.label} · {(r.created_at || "").slice(0, 10)}</div>
                </div>
                <span className="text-xs label-eyebrow bg-muted px-2 py-1">{r.status}</span>
              </Link>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
