// 20 seed blog articles for SafeTradie. Plain text body, markdown-ish formatting.
export const BLOG_POSTS = [
  {
    slug: "whs-act-2024-changes-australian-tradies",
    category: "Legislation",
    title: "What the 2024 WHS Act changes mean for Australian tradies",
    excerpt: "Model WHS laws have shifted again. Here's the plain-English summary every owner-operator needs — and the 5 changes you must act on this quarter.",
    author: "SafeTradie Editorial",
    date: "2026-02-14",
    read_mins: 6,
    body: "The model WHS Act under the 2024 harmonisation updates introduced stricter industrial manslaughter provisions in every state except WA (which updated in 2022). Fines for breaches rose by an average of 18%. For a trade business, the practical implications are: 1) notifiable incident reporting windows shortened, 2) psychosocial hazards must be documented in your risk register, 3) officers (directors/sole traders) carry personal liability. Use SafeTradie's Incident Register to ensure you meet the reporting window. Open your Risk Register and add the 5 psychosocial hazards WorkSafe now audits against. Book a 1:1 with a SafeTradie consultant if you're unsure whether you count as an 'officer'.",
  },
  {
    slug: "swms-australia-cheatsheet",
    category: "SWMS",
    title: "The SWMS cheatsheet: every box Australian regulators want ticked",
    excerpt: "A one-page checklist every SWMS needs to satisfy WorkSafe, SafeWork, and principal contractors across Australia — with real hazard-control examples.",
    author: "Ben Marshall",
    date: "2026-02-12",
    read_mins: 4,
    body: "A compliant SWMS has seven sections: scope, hazard identification, risk matrix, hierarchy of controls, PPE, emergency procedures, sign-off. Most templates fail on hazard identification — tradies list generic hazards instead of job-specific ones. The fix: tie every hazard to a specific task step. Your SWMS for a 3m pipe chase isn't the same as one for a 10-storey riser. SafeTradie's AI generator produces job-specific SWMS from trade + job description + hazards + site. Save it, review it, sign it off on site.",
  },
  {
    slug: "incident-reporting-notifiable-vs-not",
    category: "Incidents",
    title: "Notifiable vs non-notifiable incidents — know the line",
    excerpt: "Getting this wrong costs up to A$10k per incident. A plain-English breakdown of what to report, when, and to whom.",
    author: "SafeTradie Editorial",
    date: "2026-02-10",
    read_mins: 5,
    body: "A notifiable incident = any death, serious injury/illness, or dangerous incident (near-miss with serious potential) on a workplace. Report to the state regulator immediately (phone) and in writing within 48 hours. Serious injury includes amputation, head injury requiring treatment, loss of sight, burns, 24h+ hospitalisation. Dangerous incidents include falls from height, collapses, electric shocks, pressure-vessel failures. SafeTradie's Incident module auto-flags notifiable status based on your inputs and prompts you to lodge.",
  },
  {
    slug: "psychosocial-hazards-trade-business",
    category: "Mental Health",
    title: "Psychosocial hazards: the WHS topic tradies can't ignore anymore",
    excerpt: "Since 2023, WorkSafe audits treat mental health risks like any other hazard. Here are the 6 categories and how to document controls.",
    author: "Dr Sarah Kim",
    date: "2026-02-08",
    read_mins: 7,
    body: "Psychosocial hazards are workplace factors that can cause psychological harm. The 6 categories regulators audit: 1) High job demands / low control, 2) Poor support, 3) Bullying/harassment, 4) Traumatic events, 5) Remote/isolated work, 6) Poor change management. For trades, the biggest risks are fatigue from long hours, isolation on small crews, bullying cultures, and trauma from serious incidents. Document each in your Risk Register with controls: EAP access, fair rostering, respectful-workplace policy, post-incident support. SafeTradie's Risk Register has a dedicated Psychosocial category.",
  },
  {
    slug: "working-at-heights-controls",
    category: "Hazards",
    title: "Working at heights: 9 controls that actually pass audit",
    excerpt: "Forget rope-and-a-prayer. The hierarchy-of-controls applied to real construction-site height work, with photos of what good looks like.",
    author: "Luke Pemberton",
    date: "2026-02-05",
    read_mins: 8,
    body: "Hierarchy of controls for heights: 1) Eliminate — do the work at ground level if possible. 2) Substitute — use telescopic poles. 3) Engineer — scaffold, edge protection, guardrails. 4) Admin — work permits, buddy system. 5) PPE — harness as LAST resort. Tradies who default to harness-only fail audits 70% of the time. Principal contractors increasingly reject harness-only SWMS for work above 4m. Invest in scaffold or EWPs for multi-day jobs. SafeTradie's Plant register tracks EWP inspections automatically.",
  },
  {
    slug: "electrical-safety-test-tag-2026",
    category: "Electrical",
    title: "Test & tag: the updated 2026 AS/NZS 3760 refresher",
    excerpt: "New testing intervals, new labels, new evidence. If your sparkie hasn't updated this year, you're exposed.",
    author: "Brett Alvarez",
    date: "2026-02-02",
    read_mins: 6,
    body: "AS/NZS 3760:2022 (implemented 2024 across Australia) updated testing frequencies. Hostile environment (construction) = 3 months. Office = 5 years. Evidence = dated tag + digital register. WorkSafe now accepts photo-of-tag + register entry. SafeTradie's Plant module lets you photo-upload test tags with date stamp. Your licensed test-and-tagger can sync their schedule in.",
  },
  {
    slug: "fatigue-management-construction",
    category: "Mental Health",
    title: "Fatigue management: the silent killer on Aussie sites",
    excerpt: "Over 20% of serious injuries in construction involve fatigue. Practical rosters, shift caps, and toolbox-talk scripts that work.",
    author: "Dr Sarah Kim",
    date: "2026-01-29",
    read_mins: 5,
    body: "Fatigue impairs judgment and motor skills equivalent to 0.05 BAC after 17 waking hours. Yet many sites routinely roster 10+ hour shifts for weeks. Practical controls: 1) Cap rolling shifts at 12 hours, 2) Mandate 10h rest between shifts, 3) Rotate high-risk tasks early in the shift, 4) Toolbox-talk fatigue signs (irritability, blurred vision, microsleep), 5) No-blame stand-down policy. SafeTradie has a pre-built Fatigue toolbox talk in the Toolbox Talks library.",
  },
  {
    slug: "licence-expiry-tracking-that-works",
    category: "People",
    title: "Licence expiry tracking that actually works (not a spreadsheet)",
    excerpt: "Spreadsheets fail. Here's how 500+ Australian tradies use automated reminders to stop expired tickets derailing jobs.",
    author: "SafeTradie Editorial",
    date: "2026-01-26",
    read_mins: 4,
    body: "Spreadsheets fail because: 1) Nobody reads them until they break, 2) Data drifts, 3) Nobody tests expiry reminders. Automated licence tracking means: 60-day, 30-day, 7-day, day-of alerts to owner AND worker. Hard gate: worker can't be rostered to a licensed task if ticket expired. SafeTradie's Licence module does this out of the box. Upload licence photo, set expiry, go.",
  },
  {
    slug: "toolbox-talks-that-dont-suck",
    category: "Culture",
    title: "Toolbox talks that don't suck",
    excerpt: "Five principles of a 5-minute pre-start that workers actually remember — not the same droning bullshit every Monday.",
    author: "Luke Pemberton",
    date: "2026-01-23",
    read_mins: 4,
    body: "Good toolbox talks: 1) One topic, 2) Site-specific (not generic), 3) Includes a story (last week's near-miss), 4) Invites questions, 5) Signed-off evidence. SafeTradie's Toolbox Talks module pre-loads 14 trade-relevant topics and tracks attendance. Each talk generates signed-off evidence your principal contractor will ask for.",
  },
  {
    slug: "principal-contractor-audit-ready",
    category: "Audits",
    title: "Being principal-contractor audit ready in 30 days",
    excerpt: "Lendlease, Multiplex, John Holland — they all ask for the same things. Here's the 12-item pack every subbie needs.",
    author: "Ben Marshall",
    date: "2026-01-20",
    read_mins: 7,
    body: "Tier-1 principal contractor audit packs require: 1) Current SWMS for every high-risk task, 2) Evidence of worker licences (photos), 3) Insurance certificates (currency < 30 days), 4) Toolbox talk log (last 4 weeks), 5) Inspection register, 6) Plant & equipment list with test tags, 7) Hazardous substance register with SDS, 8) Incident/near-miss log (last 12 months), 9) WHS policy signed by director, 10) Risk register, 11) Emergency procedures, 12) Mental-health support statement. Every one of these is a SafeTradie module output.",
  },
  {
    slug: "hazardous-substances-sds-100-second-read",
    category: "Hazards",
    title: "How to read an SDS in 100 seconds",
    excerpt: "Safety Data Sheets are 16 sections. You only need 4 on site. Here's exactly which ones and what to do with them.",
    author: "Luke Pemberton",
    date: "2026-01-17",
    read_mins: 3,
    body: "An SDS has 16 sections. For on-site use you only need: Section 2 (hazard identification), Section 4 (first aid), Section 7 (handling & storage), Section 8 (exposure controls/PPE). Laminate these 4 pages for each substance in the store. SafeTradie's Substances module lets you link an SDS PDF to each substance and extracts the PPE requirements automatically.",
  },
  {
    slug: "mental-health-first-aid-site",
    category: "Mental Health",
    title: "Mental Health First Aid on site: a practical 12-month plan",
    excerpt: "MHFA certification in construction is now a differentiator at tender. Rollout plan that costs under A$3k.",
    author: "Dr Sarah Kim",
    date: "2026-01-14",
    read_mins: 6,
    body: "Mental Health First Aid (MHFA) certifies workers to recognise and respond to psychological distress. 12-month rollout: 1) Q1 — certify 2 senior leaders, 2) Q2 — 1 MHFA per crew of 10, 3) Q3 — toolbox talks on asking 'are you ok?', 4) Q4 — measure psychosocial survey score. Cost ~A$2,400 for 6 MHFA certs + materials. SafeTradie Academy includes a Mental Health & Psychosocial course as a prerequisite.",
  },
  {
    slug: "incident-investigation-5-whys",
    category: "Incidents",
    title: "Incident investigation using 5-Whys (with a real tradie example)",
    excerpt: "Root-cause analysis without a consultant. A worked example of a real plumbing incident from a SafeTradie customer.",
    author: "Ben Marshall",
    date: "2026-01-11",
    read_mins: 5,
    body: "5-Whys example: worker slipped on a wet floor. Why 1: floor was wet. Why 2: hose had burst. Why 3: hose was 4 years old. Why 4: no replacement schedule. Why 5: no PM register. Root cause: missing maintenance register, not 'worker didn't look'. Corrective action: introduce plant & equipment register with service dates. SafeTradie's Plant module does this; Incident module walks you through 5-Whys automatically.",
  },
  {
    slug: "first-aid-kits-what-the-law-says",
    category: "First Aid",
    title: "First aid kits: what the law actually says for trade businesses",
    excerpt: "Low-risk vs high-risk workplace. What your kit must contain. How often to check it. What WorkSafe inspectors actually look at.",
    author: "Luke Pemberton",
    date: "2026-01-08",
    read_mins: 4,
    body: "Trade businesses (construction, mechanical, electrical) = high-risk workplace. Minimum Type B kit per 25 workers PLUS an additional kit for each remote site + vehicle. Inspect monthly, restock within 14 days. First aid officer must hold current HLTAID011 (basic first aid) + HLTAID009 (CPR). SafeTradie's First Aid & PPE module lists all kit locations and last-inspection dates.",
  },
  {
    slug: "ppe-standards-compliance-2026",
    category: "PPE",
    title: "PPE compliance: the 2026 standards refresh (AS/NZS 2210 and friends)",
    excerpt: "New standards for high-vis, hard hats, steel caps. If you haven't refreshed your PPE register this year you're out of spec.",
    author: "SafeTradie Editorial",
    date: "2026-01-05",
    read_mins: 5,
    body: "Updated standards in 2026: high-vis (AS/NZS 4602.1:2023), hard hats (AS/NZS 1801:2023), safety footwear (AS/NZS 2210.3:2024). Key changes: improved retroreflective tape placement, hard-hat chin-strap mandatory in windy conditions, steel caps required to disclose impact rating. Maintain PPE register with issue date, replacement due date. SafeTradie's First Aid & PPE module tracks issue + replacement.",
  },
  {
    slug: "subcontractor-engagement-checklist",
    category: "People",
    title: "Engaging subcontractors: the 7-step compliance checklist",
    excerpt: "Sub fails a WHS audit = you fail. Protect yourself with this 7-step engagement process (W5 workflow in SafeTradie).",
    author: "Ben Marshall",
    date: "2026-01-02",
    read_mins: 6,
    body: "The 7 steps (matches SafeTradie's W5 Subcontractor workflow): 1) Invite, 2) Company details + ABN, 3) Insurance certs (public liability + workers comp), 4) Licences verified, 5) SWMS approved, 6) Induction completed, 7) Engaged. Skip any step and principal contractor audits can exclude the sub — meaning you lose the sub AND the job. SafeTradie automates steps 1-6.",
  },
  {
    slug: "confined-spaces-permit-to-work",
    category: "Hazards",
    title: "Confined spaces: permit-to-work that survives audit",
    excerpt: "Stand-by person, atmospheric test, rescue plan. Three things every permit needs — and three things most permits miss.",
    author: "Luke Pemberton",
    date: "2025-12-28",
    read_mins: 7,
    body: "Confined space entry under AS/NZS 2865:2020 requires: 1) Authorised permit, 2) Atmospheric test (O2, LEL, CO, H2S), 3) Stand-by person outside, 4) Rescue plan (not just '000'), 5) Communication every 15 min. Most permits miss: rescue plan details, atmospheric re-test after breaks, qualified stand-by person. SafeTradie's Inspections module includes a confined-space checklist.",
  },
  {
    slug: "plant-registration-rego-inspection",
    category: "Plant",
    title: "Plant registration, rego, inspection — keeping vehicles and gear legal",
    excerpt: "Cranes, EWPs, scaffolding, vehicles. Each has a different inspection regime. Keep them all in one register or lose jobs.",
    author: "Brett Alvarez",
    date: "2025-12-24",
    read_mins: 5,
    body: "Each class of plant has its own regime. Cranes = 25-year registration design + annual inspection. EWPs = 10-year major inspection + annual. Scaffolding = per-erect inspection by competent person. Vehicles = state rego + log-book servicing. Miss any and you're liable. SafeTradie's Plant module tracks next_service, next_inspection, rego_expiry with alerts at 60/30/7 days.",
  },
  {
    slug: "small-tradie-audit-pass-under-2k",
    category: "Audits",
    title: "How a 4-person plumbing crew passed a tier-1 audit under A$2k",
    excerpt: "Case study: real SafeTradie customer. What they did, what they didn't, the principal contractor's exact checklist.",
    author: "Ben Marshall",
    date: "2025-12-20",
    read_mins: 8,
    body: "Case study: PlumbRight (4-worker plumbing crew, Sydney). Principal contractor: Multiplex. Pre-audit state: spreadsheet WHS. Action plan: sign up to SafeTradie Small Business (A$250/mo), run onboarding wizard, generate 8 SWMS for common tasks, upload 4 worker licences, create risk register with 12 entries, schedule monthly toolbox talks, fill Plant register. Audit result: pass first time, no corrective actions. Total cost: A$2,250 first year incl. setup. ROI: retained a A$180k contract that would have been lost.",
  },
  {
    slug: "what-is-whs-culture-and-how-to-measure-it",
    category: "Culture",
    title: "What is WHS culture and how do you measure it?",
    excerpt: "Culture isn't a poster. It's how people behave when nobody's watching. 5 measurable indicators + quarterly pulse survey you can run for free.",
    author: "Dr Sarah Kim",
    date: "2025-12-16",
    read_mins: 6,
    body: "5 measurable indicators of WHS culture: 1) Near-miss reporting rate (high = good, people feel safe reporting), 2) Toolbox talk attendance rate, 3) Time-to-close corrective actions, 4) Psychosocial pulse score, 5) Leading-indicator vs lagging-indicator ratio. Run a 5-question quarterly pulse (anonymous) and track it over time. SafeTradie's Reports module produces an Incidents Trend report that surfaces leading indicators automatically.",
  },
];

export const BLOG_CATEGORIES = [...new Set(BLOG_POSTS.map((p) => p.category))].sort();

export const getPost = (slug) => BLOG_POSTS.find((p) => p.slug === slug);
