// Per-industry free templates library.
// `body` is rendered as a Word document (.doc) using Microsoft Office HTML when
// the user clicks Download. Each template lists realistic Australian compliance
// sections — owners can edit in Word/LibreOffice/Pages.
export const INDUSTRY_TEMPLATES = {
  trades: [
    { id: "swms-plumbing", cat: "SWMS", title: "SWMS — General plumbing", desc: "Safe Work Method Statement for residential plumbing work. Covers typical hazards, hierarchy of controls, PPE and sign-off.", size: "42 KB",
      body: "SWMS — GENERAL PLUMBING\n\nScope of work: general residential plumbing installations, repairs and maintenance.\nHazards: manual handling, slips/trips, confined spaces, hot work.\nControls: per hierarchy — eliminate, substitute, engineer, admin, PPE.\nPPE required: safety boots, eye protection, gloves, hi-vis.\nEmergency procedures: first aid officer on site, nearest hospital, stop-work triggers.\nSign-off: worker name, signature, date." },
    { id: "swms-electrical", cat: "SWMS", title: "SWMS — Electrical installation", desc: "Covers isolation, test-before-touch, RCDs and sign-off for all licensed electrical work.", size: "44 KB",
      body: "SWMS — ELECTRICAL INSTALLATION\n\nScope: AC wiring, switchboard work, RCD installation.\nHazards: electric shock, arc flash, falls from height, manual handling.\nControls: LOTO, test-before-touch, RCDs, warning signs, barricades.\nPPE: Cat-1 arc-rated where applicable, insulated gloves, safety glasses, steel caps.\nEmergency: first aider trained in CPR/AED, nearest hospital, AS/NZS 3000 compliant." },
    { id: "swms-heights", cat: "SWMS", title: "SWMS — Working at heights (2m+)", desc: "Edge protection, EWP, scaffold or harness. AS/NZS 1891 aligned.", size: "46 KB",
      body: "SWMS — WORKING AT HEIGHTS\n\nScope: any work above 2m.\nHazards: fall from height, dropped objects, weather, fatigue.\nControls: edge protection preferred, EWP next, harness last resort.\nPPE: full-body harness with shock-absorbing lanyard, anchor points rated 15kN.\nPermit-to-work required above 4m." },
    { id: "induction-form-trades", cat: "Induction", title: "Site induction form", desc: "10-question induction for new workers and subbies. Prints to A4.", size: "28 KB",
      body: "SITE INDUCTION\n\nWorker name: ____________\nContact: ____________\nDate: ____________\n\n1. Have you read the site-specific SWMS? Y/N\n2. Do you hold a valid White Card? Y/N\n3. Do you have the PPE required? Y/N\n4. Have you been briefed on emergency procedures? Y/N\n5. Any pre-existing medical conditions? Y/N\n6. Do you understand reporting lines? Y/N\n7. Have you been shown the first-aid location? Y/N\n8. Have you been shown the assembly point? Y/N\n9. Do you understand lock-out procedures? Y/N\n10. Any questions? ____________\n\nSignature: ____________" },
    { id: "toolbox-mental-health", cat: "Toolbox", title: "Toolbox talk — Mental health & wellbeing", desc: "Psychosocial safety talk aligned to 2023 regulation change.", size: "24 KB",
      body: "TOOLBOX TALK — MENTAL HEALTH\n\n1. Construction has the highest male suicide rate of any industry.\n2. Warning signs in mates: withdrawal, anger, fatigue, substance use.\n3. How to ask: 'Are you ok? For real?'\n4. Resources: Mates in Construction 1300 642 111, Lifeline 13 11 14.\n5. Our workplace commitment: no-blame reporting, EAP access, reasonable hours.\n\nAttendees: _____________________________" },
    { id: "incident-report-trades", cat: "Incidents", title: "Incident report form (5-Whys)", desc: "A4 printable incident report with root-cause fields.", size: "26 KB",
      body: "INCIDENT REPORT\n\nDate/time: ____________\nSite: ____________\nWorker(s) involved: ____________\nInjury/damage: ____________\nSequence of events: ____________\n\n5-WHYS ROOT CAUSE:\n1. Why? ____________\n2. Why? ____________\n3. Why? ____________\n4. Why? ____________\n5. Why? ____________\n\nCorrective actions: ____________\nResponsible: ____________\nDue date: ____________\nSignature: ____________" },
    { id: "risk-register-trades", cat: "Risk", title: "Risk register (5×5 matrix)", desc: "5×5 likelihood × consequence matrix with inherent + residual columns.", size: "38 KB",
      body: "RISK REGISTER\n\nID | Risk | Category | Likelihood(1-5) | Consequence(1-5) | Inherent | Controls | Residual L | Residual C | Owner | Review date\n—\n\nMatrix key:\n1 Rare · 2 Unlikely · 3 Possible · 4 Likely · 5 Almost certain\n1 Insig · 2 Minor · 3 Moderate · 4 Major · 5 Catastrophic\n\nScore = L × C. 1-4 Low, 5-9 Medium, 10-15 High, 16-25 Extreme." },
    { id: "whs-policy", cat: "Policy", title: "WHS policy statement", desc: "One-page signed policy aligned to WHS Act.", size: "18 KB",
      body: "WHS POLICY STATEMENT\n\n[Business name] is committed to providing a safe and healthy workplace for all workers, contractors, and visitors. We will:\n\n1. Comply with the WHS Act, Regulations, and Codes of Practice.\n2. Consult with workers on health and safety matters.\n3. Provide a risk-based approach to hazard management.\n4. Train workers to work safely.\n5. Report and investigate all incidents.\n6. Support worker mental health and wellbeing.\n\nSigned: _____________ (Director)\nDate: _____________\nReview: annually." },
  ],

  hospitality: [
    { id: "haccp-plan", cat: "Food Safety", title: "HACCP plan template", desc: "7-principle HACCP plan aligned to Food Standards Code 3.2.1/3.2.2.", size: "48 KB",
      body: "HACCP PLAN\n\nBusiness name: ____________\nPremises address: ____________\nDate prepared: ____________\nReview date: ____________\n\n1. SCOPE & PRODUCTS COVERED\n____________\n\n2. HAZARD ANALYSIS\nBiological | Chemical | Physical | Allergenic\n____________\n\n3. CRITICAL CONTROL POINTS (CCPs)\nCCP # | Step | Hazard | Critical limit | Monitoring | Corrective action\n____________\n\n4. MONITORING PROCEDURES\n____________\n\n5. CORRECTIVE ACTIONS\n____________\n\n6. VERIFICATION\n____________\n\n7. RECORD-KEEPING\nLogs: temperature, cleaning, supplier, training, calibration. Retained 12 months minimum.\n\nFood Safety Supervisor: ____________ (qualification + date)" },
    { id: "temperature-log", cat: "Food Safety", title: "Temperature monitoring log", desc: "Daily fridge / freezer / hot-hold temperature record (printable A4).", size: "22 KB",
      body: "DAILY TEMPERATURE MONITORING LOG\n\nWeek of: ____________\n\nUnit | Target | Mon AM | Mon PM | Tue AM | Tue PM | Wed AM | Wed PM | Thu AM | Thu PM | Fri AM | Fri PM | Sat AM | Sat PM | Sun AM | Sun PM | Initials\nWalk-in cold | ≤5°C | | | | | | | | | | | | | | |\nFreezer | ≤-15°C | | | | | | | | | | | | | | |\nHot hold | ≥60°C | | | | | | | | | | | | | | |\nDelivery | ≤5°C | | | | | | | | | | | | | | |\n\nNotes / corrective actions: ____________\n\nSigned (FSS): ____________" },
    { id: "cleaning-schedule", cat: "Food Safety", title: "Cleaning schedule template", desc: "Daily / weekly / monthly cleaning schedule with sign-off.", size: "26 KB",
      body: "CLEANING SCHEDULE\n\nFREQUENCY | AREA | TASK | CHEMICAL | PPE | DONE BY | SIGNATURE\n\nDAILY\n— Front-of-house tables | Wipe with sanitiser | Quat-amm | Gloves | | \n— Toilets | Clean & restock | Bleach-based | Gloves, mask | | \n— Kitchen benches | Sanitise after service | Food-grade san | Gloves | | \n— Floors | Sweep + mop | Neutral detergent | Slip-resistant footwear | | \n\nWEEKLY\n— Fridges | Empty + sanitise | Quat-amm | Gloves | | \n— Range hood filters | Degrease | Caustic degreaser | Gloves, eye, mask | | \n— Drains | Flush + sanitise | Enzymatic | Gloves | | \n\nMONTHLY\n— Walk-in cold | Deep clean | Quat-amm | Gloves | | \n— Pest stations | Inspect + log | n/a | n/a | | \n\nReviewed by FSS: ____________  Date: ____________" },
    { id: "allergen-matrix", cat: "Food Safety", title: "Allergen disclosure matrix", desc: "Menu × 14 priority allergens cross-reference (Australian disclosure standard).", size: "30 KB",
      body: "ALLERGEN DISCLOSURE MATRIX\n\nMENU ITEM | Cereals/Gluten | Crustacean | Egg | Fish | Lupin | Milk | Mollusc | Mustard | Peanut | Sesame | Soybean | Sulphites | Tree nut | Added sulphites\n____________ | | | | | | | | | | | | | | \n\nFAQ for staff\n1. Can we substitute? Only with manager and FSS sign-off.\n2. Cross-contact risk? List every shared surface, utensil, oil.\n3. If a customer asks: don't guess. Refer to FSS.\n\nReviewed by FSS: ____________  Date: ____________" },
    { id: "rsa-register", cat: "Liquor", title: "RSA / RSG register", desc: "Track Responsible Service of Alcohol qualifications and expiry dates.", size: "20 KB",
      body: "RSA & RSG REGISTER\n\nStaff name | Role | RSA number | Issuing body | State | Issue date | Expiry | Verified by | Date verified\n____________ | | | | | | | | \n\nRefresher cycle\n— NSW: refresher every 5 years (or as Liquor & Gaming NSW publishes)\n— VIC: lifetime (subject to review)\n— QLD: refresher every 3 years\n— WA: lifetime + cell-issued every 3 years\n\nApproved Manager (if applicable): ____________  Licence #: ____________" },
    { id: "incident-report-hosp", cat: "Incidents", title: "Customer / staff incident report", desc: "Records customer injuries (slip, choke, allergen) and staff incidents.", size: "24 KB",
      body: "INCIDENT REPORT — HOSPITALITY\n\nDate/time: ____________\nVenue: ____________\nPerson(s) involved (staff/customer): ____________\nNature of incident: slip | trip | burn | choke | allergen | aggression | other ____________\nFood/drink involved? Y/N: ____________\nMedical attention required? Y/N: ____________\nAmbulance called? Y/N: ____________\nWitness(es): ____________\n\nRoot cause: ____________\nCorrective action: ____________\nResponsible: ____________  Due: ____________\n\nFor allergen events: copy of allergen matrix attached? Y/N\nNotifiable to regulator? Y/N — if Y, lodged within: ____________\n\nSigned by FSS or duty manager: ____________" },
    { id: "fss-checklist", cat: "Food Safety", title: "Council inspection self-assessment", desc: "37-point self-assessment matching what most local councils audit against.", size: "32 KB",
      body: "COUNCIL INSPECTION SELF-ASSESSMENT (37 items)\n\nA — STRUCTURE & CLEANING\n[ ] Walls, floors, ceilings clean and free of damage\n[ ] Lighting adequate, fittings food-safe\n[ ] Hand-wash sinks with soap + paper towels\n[ ] Garbage area enclosed and cleaned\n\nB — TEMPERATURE CONTROL\n[ ] Fridge ≤5°C, freezer ≤-15°C — recorded daily\n[ ] Hot-hold ≥60°C — recorded\n[ ] Cooling 60→21°C in <2hr, 21→5°C in <4hr\n[ ] Calibrated probe thermometer available\n\nC — STAFF & TRAINING\n[ ] FSS qualified and current\n[ ] All food handlers trained (record on file)\n[ ] Sick-leave policy excludes infectious staff\n[ ] Hand-wash signs in language(s) staff read\n\nD — DOCUMENTATION\n[ ] HACCP plan on premises\n[ ] Temperature logs — current 30 days\n[ ] Cleaning schedule — signed\n[ ] Allergen matrix — current menu\n[ ] Supplier register — approved suppliers only\n[ ] Pest control records\n[ ] Calibration records\n\nE — TRACEABILITY\n[ ] Supplier invoices retained 6 months\n[ ] Recall procedure documented\n\nF — ALLERGENS\n[ ] 14-allergen matrix per menu item\n[ ] Cross-contact controls described\n[ ] Staff trained to refer requests to FSS\n\nSigned (FSS): ____________  Date: ____________" },
    { id: "psychosocial-hosp", cat: "WHS", title: "Psychosocial risk assessment (hospitality)", desc: "Customer aggression, fatigue, shift design, harassment — documented.", size: "28 KB",
      body: "PSYCHOSOCIAL RISK ASSESSMENT — HOSPITALITY\n\nWHS Act 2011 + 2023 psychosocial regulations require employers to identify, assess and control psychosocial hazards.\n\nHAZARD | LIKELIHOOD | CONSEQUENCE | EXISTING CONTROLS | ADDITIONAL CONTROLS | REVIEW DATE\nCustomer aggression (especially late-shift) | | | | | \nIntoxicated patrons | | | | | \nFatigue — split shifts, late closes | | | | | \nSexual harassment (esp. floor staff) | | | | | \nWorkload during peak service | | | | | \nLone working — close, open, cash handling | | | | | \nBullying — kitchen culture | | | | | \nExposure to traumatic events — choke, medical | | | | | \n\nConsultation completed? Y/N (date): ____________\nReviewed by manager: ____________  Date: ____________" },
  ],

  transport: [
    { id: "cor-mgmt-plan", cat: "CoR", title: "CoR Management Plan template", desc: "Chain of Responsibility management plan template aligned to HVNL S26C.", size: "52 KB",
      body: "CHAIN OF RESPONSIBILITY MANAGEMENT PLAN\n\nBusiness name: ____________\nABN: ____________\nDate of plan: ____________\nReview date: ____________\n\n1. SCOPE & DUTY HOLDERS\nDuty holders in our operation (per HVNL S26A-C): consigner, packer, loader, driver, scheduler, operator.\nNominated CoR officer: ____________\n\n2. SAFETY DUTIES (HVNL S26C)\nWe will, so far as is reasonably practicable, ensure:\n— mass, dimension and load restraint comply\n— speed limits are observed\n— fatigue management is observed\n— vehicles are roadworthy\n\n3. SCHEDULING\nTrip plans must include: route, REST stops, driving hours within Standard / BFM / AFM as applicable.\nFatigue triggers: ____________\n\n4. DRIVER MANAGEMENT\nLicence check at hire + annual. Drug & alcohol policy: AS 4308 / AS/NZS 4760 aligned.\n\n5. LOAD MANAGEMENT\nLoad Restraint Guide 3rd Edition. Pre-trip check mandatory.\n\n6. VEHICLE MANAGEMENT\nPre-trip + post-trip inspections logged. Roadworthy inspections per state. Maintenance records.\n\n7. INVESTIGATION & REPORTING\nNotifiable incidents reported to NHVR within required window.\n\n8. CONSULTATION & TRAINING\nDriver induction includes CoR. Refresher annually.\n\nSigned (CoR officer): ____________  Date: ____________" },
    { id: "pre-trip-checklist", cat: "Pre-trip", title: "Vehicle pre-trip inspection checklist", desc: "Heavy-vehicle pre-trip checklist (printable, A4).", size: "24 KB",
      body: "PRE-TRIP VEHICLE INSPECTION\n\nDriver: ____________\nDate: ____________\nVehicle rego: ____________\nOdometer: ____________\n\nEXTERIOR\n[ ] Tyres — tread, inflation, no damage\n[ ] Wheels & rims — no cracks, all nuts tight\n[ ] Lights — head, indicators, tail, brake, hazard\n[ ] Mirrors — clean, secure\n[ ] Number plates — visible, legible\n[ ] Bodywork — no damage compromising load\n[ ] Coupling (if combination) — secure, locked\n\nLOAD\n[ ] Load secured per Load Restraint Guide\n[ ] No overhang exceeding limits\n[ ] Weight within GVM / GCM\n\nFLUIDS & UNDER BONNET\n[ ] Oil, coolant, washer fluid\n[ ] No leaks visible\n[ ] Belts and hoses intact\n\nCAB\n[ ] Brakes — air pressure builds, no leaks\n[ ] Steering — no excess play\n[ ] Wipers, horn, demister\n[ ] Gauges all reading normal\n[ ] Seat belts functional\n[ ] First aid kit, fire extinguisher\n\nDOCS ON BOARD\n[ ] Licence + medical (if applicable)\n[ ] Logbook / EWD\n[ ] Permit (if oversized)\n\nDriver signature: ____________" },
    { id: "fatigue-log", cat: "Fatigue", title: "Driver fatigue (work diary) log", desc: "Work-and-rest record matching National Work Diary requirements.", size: "26 KB",
      body: "DRIVER WORK DIARY (work-and-rest log)\n\nDriver: ____________\nLicence #: ____________\nOperator: ____________\nFatigue category: Standard / BFM / AFM\n\nDate | Start | End | Activity (Work / Rest / Other) | Location | Odometer | Vehicle\n____ | ____ | ____ | ____ | ____ | ____ | ____\n____ | ____ | ____ | ____ | ____ | ____ | ____\n\nSTANDARD HOURS LIMITS\n— Max 12 hours work in 24\n— Min 7 hours continuous rest\n— Max 6 days work in 7\n\nBFM LIMITS\n— Max 14 hours work in 24\n— Min 7 hours rest in 24\n\nDeclaration: This record is true and accurate.\nDriver: ____________  Date: ____________" },
    { id: "load-restraint", cat: "Load", title: "Load restraint record", desc: "Pre-trip load-restraint verification per Load Restraint Guide 3rd Edition.", size: "20 KB",
      body: "LOAD RESTRAINT RECORD\n\nDate: ____________\nDriver: ____________\nVehicle: ____________\nLoad description: ____________\n\nRestraint method: chains | webbing | dunnage | tie-rails | curtain | other ____________\nNumber of restraint points: ____________\nWLL of each restraint: ____________\nLoad packed tight (no movement)? Y/N\nForward restraint adequate (per LRG)? Y/N\nSide & rear restraint adequate? Y/N\nLoad-shift indicators (e.g. paint dots) used? Y/N\n\nDriver signed (verifying restraint): ____________" },
    { id: "incident-report-transport", cat: "Incidents", title: "Heavy vehicle incident report", desc: "Crash, near-miss, roadside breakdown, fatigue event — captures NHVR-required detail.", size: "28 KB",
      body: "HEAVY VEHICLE INCIDENT REPORT\n\nDate/time: ____________\nLocation (street, suburb, state): ____________\nVehicle rego: ____________\nDriver: ____________\nCompany: ____________\nABN: ____________\n\nNature of incident: crash | near-miss | rollover | mechanical | fatigue | load-shift | other ____________\nInjuries? Y/N\nFatalities? Y/N\nProperty damage? Y/N\nAmbulance/police attended? Y/N\nNotifiable to NHVR? Y/N — lodged on: ____________\n\nSequence of events: ____________\n\n5-Whys root cause: ____________\nCorrective actions: ____________\nResponsible: ____________  Due: ____________\n\nCoR officer signature: ____________" },
    { id: "fitness-for-duty", cat: "Driver", title: "Fitness for duty declaration", desc: "Drug, alcohol, fatigue, fitness declaration prior to trip.", size: "18 KB",
      body: "FITNESS FOR DUTY DECLARATION\n\nI, ____________ (driver), declare that on ____________ (date):\n\n1. I have had at least 7 hours of continuous rest in the past 24 hours.\n2. I am not under the influence of alcohol or any drug that impairs my ability to drive.\n3. I am not taking prescription medication that affects my driving.\n4. I am physically and mentally fit to drive.\n5. If at any time during my shift this changes, I will notify the scheduler immediately.\n\nDriver signature: ____________\nWitness (where required): ____________" },
    { id: "subcontractor-cor", cat: "Contractors", title: "Subcontractor CoR declaration", desc: "Subcontractor CoR declaration covering driver licensing, fatigue, load restraint.", size: "22 KB",
      body: "SUBCONTRACTOR CoR DECLARATION\n\nWe, ____________ (subcontractor), declare to ____________ (principal operator) that:\n\n1. All drivers we engage hold valid heavy-vehicle licences.\n2. Our drivers operate within Standard / BFM / AFM hours as nominated below.\n3. Our vehicles are roadworthy and inspections are current.\n4. Loads are restrained per LRG 3rd Edition.\n5. We hold workers compensation insurance.\n6. We carry public liability of at least A$20m.\n7. We will report incidents within the timeframes required by HVNL.\n\nFatigue category: ____________\nWorkCover policy #: ____________\nPL policy + insurer: ____________\nABN: ____________\n\nSigned: ____________  Date: ____________" },
    { id: "drug-alcohol-policy", cat: "WHS", title: "Drug & alcohol management policy", desc: "AS 4308 / AS/NZS 4760 aligned policy with testing regime.", size: "30 KB",
      body: "DRUG & ALCOHOL MANAGEMENT POLICY\n\n1. PURPOSE\nThis policy supports safe operation of heavy vehicles and compliance with HVNL S26C.\n\n2. SCOPE\nApplies to all employees, subcontractors, and visitors operating or accessing our vehicles.\n\n3. STANDARDS\n— Alcohol: zero BAC for drivers.\n— Drugs: per AS/NZS 4760 cut-off values (saliva) and AS 4308 (urine where required).\n\n4. TESTING\n— Random testing — annual rate ≥10% of driver workforce.\n— Post-incident testing — within 8 hours.\n— Reasonable cause testing — supervisor + second witness present.\n\n5. CONSEQUENCES\nFirst breach: 5-day suspension + EAP referral. Second breach: termination subject to industrial process.\n\n6. SUPPORT\nConfidential EAP access for any worker requesting support.\n\nApproved (Director): ____________  Date: ____________" },
  ],

  healthcare: [
    { id: "ahpra-register", cat: "AHPRA", title: "AHPRA registration tracking register", desc: "Track AHPRA registration per clinician with renewal alerts column.", size: "22 KB",
      body: "AHPRA REGISTRATION REGISTER\n\nClinician name | Profession | AHPRA registration # | Endorsements | Conditions | Registration type | Date of registration | Renewal due | Verified by | Date verified | Next verification\n____________ | | | | | | | | | | \n\nVerification frequency: at hire + at every renewal (annual for most professions, biennial for others).\nResponsible officer: ____________" },
    { id: "ndis-worker-screening", cat: "NDIS", title: "NDIS Worker Screening register", desc: "Track NDIS WSC clearance per worker (5-year cycle).", size: "20 KB",
      body: "NDIS WORKER SCREENING CLEARANCE REGISTER\n\nWorker name | Role | Risk-assessed role? Y/N | Clearance state | Clearance number | Issue date | Expiry (5 years) | Verified by | Verified date | Next verification\n____________ | | | | | | | | | \n\nAll workers in 'risk-assessed roles' under the NDIS Practice Standards must hold a current Clearance prior to commencing work.\n\nResponsible officer: ____________" },
    { id: "manual-handling-ra", cat: "Clinical", title: "Manual handling risk assessment (clinical)", desc: "Patient / resident transfer manual-handling assessment.", size: "32 KB",
      body: "MANUAL HANDLING RISK ASSESSMENT — CLINICAL\n\nResident/patient: ____________\nDate of assessment: ____________\nAssessor: ____________\n\nPATIENT FACTORS\nWeight (kg): ____________\nCognition / cooperation: ____________\nMobility (independent / partial / dependent): ____________\nMedical equipment attached: ____________\n\nTASK\nTransfer type: bed-to-chair | chair-to-toilet | reposition | shower | other ____________\nFrequency / day: ____________\n\nCONTROLS\nMechanical aid required? hoist | sit-to-stand | slide sheet | n/a\nNumber of carers required: ____________\nPPE required: ____________\n\nReview triggers: incident, deterioration in mobility, equipment change.\nReview date: ____________\n\nSigned (RN / clinical lead): ____________" },
    { id: "psychosocial-healthcare", cat: "WHS", title: "Psychosocial risk register (healthcare)", desc: "Workload, exposure to trauma, rostering, patient aggression — documented.", size: "30 KB",
      body: "PSYCHOSOCIAL RISK REGISTER — HEALTHCARE\n\nWHS Act 2011 + 2023 psychosocial regulations.\n\nHAZARD | LIKELIHOOD | CONSEQUENCE | EXISTING CONTROLS | ADDITIONAL CONTROLS | REVIEW DATE\nPatient / resident aggression | | | | | \nClinician workload — staffing ratios | | | | | \nRostering — fatigue from night shifts | | | | | \nExposure to trauma / death | | | | | \nBullying — hierarchical structures | | | | | \nViolence from visitors | | | | | \nIsolation — sole clinician shifts | | | | | \nVicarious trauma — palliative / dementia care | | | | | \n\nConsultation completed? Y/N (date): ____________\nReviewed by clinical governance lead: ____________  Date: ____________" },
    { id: "incident-report-healthcare", cat: "Incidents", title: "Clinical incident & near-miss report", desc: "Captures serious events for ACQSC SIRS / NDIS Commission reporting.", size: "28 KB",
      body: "CLINICAL INCIDENT REPORT\n\nDate/time: ____________\nFacility / service: ____________\nResident/patient identifier (de-identified): ____________\nReporter: ____________  Role: ____________\n\nCATEGORY (tick)\n[ ] Fall  [ ] Medication error  [ ] Restrictive practice  [ ] Pressure injury\n[ ] Aggression  [ ] Elopement  [ ] Choke  [ ] Infection control  [ ] Other\n\nDescription: ____________\n\nIMMEDIATE ACTION\nClinical: ____________\nFamily notified? Y/N — by whom: ____________\nMedical attention required? Y/N\n\nREPORTING (tick where applicable)\n[ ] ACQSC SIRS — Priority 1 (24 hr) / Priority 2 (5 day)\n[ ] NDIS Commission reportable incident\n[ ] WorkSafe (if worker injury)\n[ ] Police\n\n5-Whys root cause: ____________\nCorrective actions: ____________\nResponsible: ____________  Due: ____________\n\nClinical governance signature: ____________" },
    { id: "emergency-plan-healthcare", cat: "Emergency", title: "Emergency response plan (healthcare)", desc: "Evacuation, lockdown, fire, medical emergency, infection outbreak.", size: "34 KB",
      body: "EMERGENCY RESPONSE PLAN — HEALTHCARE\n\nService / facility: ____________\nAddress: ____________\nDate: ____________  Review: ____________\n\n1. WARDENS & RESPONSIBLE OFFICERS\nChief warden: ____________  mobile: ____________\nClinical lead on call: ____________  mobile: ____________\n\n2. ASSEMBLY POINT\nPrimary: ____________\nSecondary: ____________\n\n3. EVACUATION ROUTE\nMap on back page. Resident / patient mobility considered (hoists, walkers, wheelchairs).\n\n4. SCENARIOS\n— Fire: raise alarm, evacuate horizontally if possible, call 000.\n— Medical (resident/patient): clinical response per condition, call 000 if serious.\n— Medical (worker): first aid, call 000 if serious.\n— Infection outbreak: isolate, contact PHU, follow national IPC guidelines.\n— Aggression / lockdown: code black procedure.\n— Missing resident (elopement): code yellow, search, escalate to police if not located within 30 minutes.\n\n5. AFTER ACTION\nDebrief within 48 hours. Update RA + register.\n\nApproved: ____________  Date: ____________" },
    { id: "infection-control-policy", cat: "IPC", title: "Infection prevention & control policy", desc: "Hand hygiene, PPE, cleaning, outbreak management aligned to NHMRC guidelines.", size: "36 KB",
      body: "INFECTION PREVENTION & CONTROL POLICY\n\nAligned to the NHMRC Australian Guidelines for the Prevention and Control of Infection in Healthcare (current edition).\n\n1. STANDARD PRECAUTIONS\n— Hand hygiene per WHO 5 Moments\n— PPE based on task risk assessment\n— Safe handling of sharps\n— Respiratory hygiene + cough etiquette\n— Cleaning of patient-care equipment per manufacturer + IPC\n\n2. TRANSMISSION-BASED PRECAUTIONS\nContact / droplet / airborne — donning + doffing sequence trained annually.\n\n3. STAFF HEALTH\nImmunisations per role (Hep B, MMR, varicella, dTpa, influenza, COVID-19).\nExclusion criteria for infectious staff.\n\n4. OUTBREAK MANAGEMENT\nNotification to PHU within required timeframe. Cohorting, environmental controls, supplemental staffing.\n\n5. CLEANING & WASTE\nCleaning frequency table. Clinical waste segregation, storage, disposal per state EPA.\n\n6. AUDIT\nMonthly hand-hygiene audit. PPE compliance audit. Quarterly review.\n\nIPC officer: ____________  Approved: ____________" },
    { id: "acqsc-self-assessment", cat: "ACQSC", title: "ACQSC Strengthened Standards self-assessment", desc: "All 8 strengthened standards self-assessment matrix.", size: "44 KB",
      body: "STRENGTHENED AGED CARE QUALITY STANDARDS — SELF-ASSESSMENT\n\nFor each Standard (1–8) rate evidence as MET / PARTIALLY MET / NOT MET, with notes and corrective action.\n\nStandard 1: The Person\nEvidence: ____________  Rating: ____________\n\nStandard 2: The Organisation\nEvidence: ____________  Rating: ____________\n\nStandard 3: Care and Services\nEvidence: ____________  Rating: ____________\n\nStandard 4: The Environment\nEvidence: ____________  Rating: ____________\n\nStandard 5: Clinical Care\nEvidence: ____________  Rating: ____________\n\nStandard 6: Food and Nutrition\nEvidence: ____________  Rating: ____________\n\nStandard 7: The Residential Community\nEvidence: ____________  Rating: ____________\n\nStandard 8: Workforce\nEvidence: ____________  Rating: ____________\n\nCorrective actions plan attached: Y/N\n\nQuality lead signature: ____________  Date: ____________" },
  ],

  retail: [
    { id: "quick-induction-retail", cat: "Induction", title: "Quick induction (casual retail staff)", desc: "10-minute induction for new casual staff — printable A4.", size: "20 KB",
      body: "RETAIL CASUAL INDUCTION\n\nName: ____________\nStore: ____________\nDate: ____________\n\n1. EMERGENCY\n— Fire alarm location: ____________\n— Assembly point: ____________\n— First aid officer today: ____________\n\n2. HAZARDS YOU MAY ENCOUNTER\n— Manual handling: bend at knees, ask for help with >15 kg\n— Slips/trips: wet-floor signs, no boxes in aisles\n— Customer aggression: stay behind counter, call manager\n— Lone working: see check-in process\n\n3. EQUIPMENT\n— Step ladder location: ____________\n— Knife / box-cutter storage: ____________\n\n4. POLICIES READ AND UNDERSTOOD\n[ ] Code of conduct  [ ] WHS  [ ] Customer aggression  [ ] Cash handling  [ ] RSA (if applicable)\n\nSigned (staff): ____________\nSigned (manager): ____________" },
    { id: "lone-worker-checkin", cat: "Lone Worker", title: "Lone-worker check-in log", desc: "Shift-by-shift lone-worker check-in record with escalation timing.", size: "18 KB",
      body: "LONE WORKER CHECK-IN LOG\n\nDate: ____________\nWorker: ____________\nStore / site: ____________\nShift type: open | mid | close | overnight\n\nCheck-in schedule (every 60 minutes minimum)\nTime | Status (OK / not responding) | Initials of nominated contact | Notes\n____ | ____ | ____ | ____\n____ | ____ | ____ | ____\n\nIf a check-in is missed, the nominated contact must:\n1. Phone the worker.\n2. If no response within 5 minutes, attempt second contact.\n3. If still no response within 10 minutes, attend in person or call 000.\n\nNominated contact: ____________  mobile: ____________\nBackup: ____________  mobile: ____________\n\nSigned: ____________" },
    { id: "cleaning-spill-record", cat: "WHS", title: "Cleaning & spill response record", desc: "Routine cleaning + customer-spill record for slip/trip defence.", size: "22 KB",
      body: "CLEANING & SPILL RESPONSE RECORD\n\nDate: ____________\nStore: ____________\n\nROUTINE CLEANING\nTime | Area | Task | Done by\n____ | ____ | ____ | ____\n____ | ____ | ____ | ____\n\nSPILLS / WET FLOORS (record every event)\nTime | Location | Source (drink / produce / cleaning) | Wet-floor sign placed? Y/N | Cleaned by | Time complete\n____ | ____ | ____ | ____ | ____ | ____\n\nManager review: ____________  Date: ____________" },
    { id: "customer-aggression", cat: "WHS", title: "Customer aggression response procedure", desc: "De-escalation, reporting, debrief — front-line retail.", size: "24 KB",
      body: "CUSTOMER AGGRESSION RESPONSE PROCEDURE\n\n1. STAY SAFE\n— Stay behind the counter where possible.\n— Do not chase a shoplifter.\n— Keep an exit clear.\n\n2. DE-ESCALATE\n— Lower voice and pace.\n— Acknowledge feelings: 'I can see you're frustrated.'\n— Offer to call a manager.\n— Do not match aggression.\n\n3. ESCALATE\n— If threatened: call 000 and your manager.\n— Trigger any duress alarm.\n\n4. AFTER THE EVENT\n— Complete an incident report within 24 hours (see template).\n— Debrief with manager.\n— EAP available — confidential.\n\nManager signature: ____________  Date: ____________" },
    { id: "incident-report-retail", cat: "Incidents", title: "Customer / staff incident report", desc: "Customer slip-and-fall, theft confrontation, worker injury.", size: "22 KB",
      body: "INCIDENT REPORT — RETAIL\n\nDate/time: ____________\nStore: ____________\nPerson involved: customer | staff | contractor\nName + contact (if customer): ____________\nNature of incident: slip | trip | fall | aggression | theft | injury | medical | other ____________\n\nLocation in store: ____________\nWitnesses: ____________\nCCTV reviewed? Y/N\nMedical attention? Y/N — by whom: ____________\nAmbulance? Y/N\n\nCleaning log reviewed (slip/trip)? Y/N\nMaintenance log reviewed? Y/N\n\nRoot cause: ____________\nCorrective action: ____________\nResponsible: ____________  Due: ____________\n\nManager signature: ____________" },
    { id: "manual-handling-retail", cat: "WHS", title: "Manual handling RA (retail)", desc: "Stock-shelving, deliveries, lifting — manual-handling assessment.", size: "26 KB",
      body: "MANUAL HANDLING RISK ASSESSMENT — RETAIL\n\nTask | Frequency | Load weight | Posture | Existing controls | Additional controls | Reviewed\nStocking shelves | | | | | | \nUnloading deliveries | | | | | | \nMoving floor stock | | | | | | \nLifting at counter | | | | | | \nReaching high shelves (step ladder) | | | | | | \n\nGENERAL CONTROLS\n— Two-person lift >15 kg or awkward shape\n— Trolleys available for floor stock\n— Step ladders rated, inspected quarterly\n— No reaching above shoulder for >5 kg\n\nReviewed by manager: ____________  Date: ____________" },
    { id: "rsa-register-retail", cat: "Liquor", title: "Bottle-shop RSA register", desc: "Track RSA currency for bottle-shop / liquor retail staff.", size: "16 KB",
      body: "BOTTLE-SHOP RSA REGISTER\n\nStaff name | Role | RSA number | State issued | Issue date | Expiry (state-dependent) | Verified by | Verified date\n____________ | | | | | | | \n\nNotes:\n— NSW RSA: 5-yearly refresher (subject to Liquor & Gaming NSW updates).\n— VIC: lifetime, subject to formal review.\n— QLD: 3-yearly refresher.\n— WA: cell-issued every 3 years.\n\nApproved Manager (if applicable): ____________  Liquor licence #: ____________" },
    { id: "whs-policy-retail", cat: "Policy", title: "WHS policy statement (retail)", desc: "One-page signed WHS policy for retail / multi-site environments.", size: "16 KB",
      body: "WHS POLICY STATEMENT — RETAIL\n\n[Business name] is committed to providing a safe and healthy retail workplace for all workers, contractors, customers, and visitors. We will:\n\n1. Comply with the WHS Act, Regulations, and Codes of Practice in every state we operate.\n2. Consult with workers on health and safety matters.\n3. Use a risk-based approach to managing slips, trips, manual handling, lone working, and customer aggression.\n4. Provide induction and ongoing training for every worker including casuals.\n5. Investigate every incident — customer or worker — and act on findings.\n6. Support worker mental health and wellbeing with confidential EAP access.\n\nSigned: _____________ (Director)\nDate: _____________\nReview: annually." },
  ],
};

// Aggregate flat list (used by the legacy /templates page before the
// industry filter was introduced). Keeps backwards compatibility.
export const ALL_TEMPLATES = Object.entries(INDUSTRY_TEMPLATES).flatMap(
  ([industry, items]) => items.map((t) => ({ ...t, industry }))
);
