// Free downloadable templates + state guides + integrations + fine-calc data
export const TEMPLATES = [
  { id: "swms-plumbing", cat: "SWMS", title: "SWMS — General plumbing", desc: "Safe Work Method Statement for residential plumbing work. Covers typical hazards, hierarchy of controls, PPE and sign-off.", size: "42 KB", body: "SWMS — GENERAL PLUMBING\n\nScope of work: general residential plumbing installations, repairs and maintenance.\nHazards: manual handling, slips/trips, confined spaces, hot work.\nControls: per hierarchy — eliminate, substitute, engineer, admin, PPE.\nPPE required: safety boots, eye protection, gloves, hi-vis.\nEmergency procedures: first aid officer on site, nearest hospital, stop-work triggers.\nSign-off: worker name, signature, date." },
  { id: "swms-electrical", cat: "SWMS", title: "SWMS — Electrical installation", desc: "Covers isolation, test-before-touch, RCDs and sign-off for all licensed electrical work.", size: "44 KB", body: "SWMS — ELECTRICAL INSTALLATION\n\nScope: AC wiring, switchboard work, RCD installation.\nHazards: electric shock, arc flash, falls from height, manual handling.\nControls: LOTO, test-before-touch, RCDs, warning signs, barricades.\nPPE: Cat-1 arc-rated where applicable, insulated gloves, safety glasses, steel caps.\nEmergency: first aider trained in CPR/AED, nearest hospital, AS/NZS 3000 compliant." },
  { id: "swms-heights", cat: "SWMS", title: "SWMS — Working at heights (2m+)", desc: "Edge protection, EWP, scaffold or harness. AS/NZS 1891 aligned.", size: "46 KB", body: "SWMS — WORKING AT HEIGHTS\n\nScope: any work above 2m.\nHazards: fall from height, dropped objects, weather, fatigue.\nControls: edge protection preferred, EWP next, harness last resort.\nPPE: full-body harness with shock-absorbing lanyard, anchor points rated 15kN.\nPermit-to-work required above 4m." },
  { id: "induction-form", cat: "Induction", title: "Site induction form (editable)", desc: "10-question induction form for new workers & subbies. Prints to A4.", size: "28 KB", body: "SITE INDUCTION\n\nWorker name: ____________\nContact: ____________\nDate: ____________\n\n1. Have you read the site-specific SWMS? Y/N\n2. Do you hold a valid White Card? Y/N\n3. Do you have the PPE required? Y/N\n4. Have you been briefed on emergency procedures? Y/N\n5. Any pre-existing medical conditions? Y/N\n6. Do you understand reporting lines? Y/N\n7. Have you been shown the first-aid location? Y/N\n8. Have you been shown assembly point? Y/N\n9. Do you understand lock-out procedures? Y/N\n10. Any questions? ____________\n\nSignature: ____________" },
  { id: "toolbox-heights", cat: "Toolbox", title: "Toolbox talk — Working at heights", desc: "Pre-filled 5-minute pre-start talk with discussion prompts.", size: "22 KB", body: "TOOLBOX TALK — WORKING AT HEIGHTS (5 min)\n\n1. Why this matters: falls from height account for 20%+ of serious workplace injuries.\n2. Hierarchy of controls: eliminate > substitute > engineer > admin > PPE.\n3. Today's site — where are we working at heights? What's the control?\n4. Harness inspection: check webbing, stitching, connectors.\n5. Rescue plan — if someone falls & is suspended, what do we do?\n\nQuestions:\n- Anyone feel unsure? Speak up.\n- Spotted any hazards this morning?\n\nAttendees: _____________________________" },
  { id: "toolbox-electrical", cat: "Toolbox", title: "Toolbox talk — Electrical safety", desc: "Short, site-ready talk on isolation and test-before-touch.", size: "20 KB", body: "TOOLBOX TALK — ELECTRICAL SAFETY\n\n1. 'Test before touch' is not negotiable.\n2. Isolation: lock out AND tag.\n3. RCDs must be fitted on all portable equipment.\n4. Report damaged leads immediately.\n\nAttendees: _____________________________" },
  { id: "toolbox-mental-health", cat: "Toolbox", title: "Toolbox talk — Mental health & wellbeing", desc: "Psychosocial safety talk aligned to 2023 regulation change.", size: "24 KB", body: "TOOLBOX TALK — MENTAL HEALTH\n\n1. Construction has the highest male suicide rate of any industry.\n2. Warning signs in mates: withdrawal, anger, fatigue, substance use.\n3. How to ask: 'Are you ok? For real?'\n4. Resources: Mates in Construction 1300 642 111, Lifeline 13 11 14.\n5. Our workplace commitment: no-blame reporting, EAP access, reasonable hours.\n\nAttendees: _____________________________" },
  { id: "incident-report", cat: "Incidents", title: "Incident report form", desc: "A4 printable incident report with root-cause fields.", size: "26 KB", body: "INCIDENT REPORT\n\nDate/time: ____________\nSite: ____________\nWorker(s) involved: ____________\nInjury/damage: ____________\nSequence of events: ____________\n\n5-WHYS ROOT CAUSE:\n1. Why? ____________\n2. Why? ____________\n3. Why? ____________\n4. Why? ____________\n5. Why? ____________\n\nCorrective actions: ____________\nResponsible: ____________\nDue date: ____________\nSignature: ____________" },
  { id: "risk-register", cat: "Risk", title: "Risk register template (5×5 matrix)", desc: "5×5 likelihood × consequence matrix with inherent + residual columns.", size: "38 KB", body: "RISK REGISTER\n\nID | Risk | Category | Likelihood(1-5) | Consequence(1-5) | Inherent | Controls | Residual L | Residual C | Owner | Review date\n—\n\nMatrix key:\n1 Rare · 2 Unlikely · 3 Possible · 4 Likely · 5 Almost certain\n1 Insig · 2 Minor · 3 Moderate · 4 Major · 5 Catastrophic\n\nScore = L × C. 1-4 Low, 5-9 Medium, 10-15 High, 16-25 Extreme." },
  { id: "plant-register", cat: "Plant", title: "Plant & equipment register", desc: "Track serial numbers, next inspection, rego expiry.", size: "32 KB", body: "PLANT & EQUIPMENT REGISTER\n\nID | Item | Serial | Ownership | Last service | Next service | Last inspection | Next inspection | Rego expiry | Operator licence required\n—\n\nNotes: high-risk plant (cranes, EWPs, pressure vessels) requires registered design, competent operator." },
  { id: "hazardous-substance", cat: "Substances", title: "Hazardous substances register", desc: "With SDS reference, storage, PPE, emergency response.", size: "34 KB", body: "HAZARDOUS SUBSTANCES REGISTER\n\nSubstance | UN # | GHS class | Storage | Max qty | SDS location | PPE | First aid response\n—\n\nKeep current SDS <5 years old. Review register annually." },
  { id: "whs-policy", cat: "Policy", title: "WHS policy statement", desc: "One-page signed policy aligned to WHS Act.", size: "18 KB", body: "WHS POLICY STATEMENT\n\n[Business name] is committed to providing a safe and healthy workplace for all workers, contractors, and visitors. We will:\n\n1. Comply with the WHS Act, Regulations, and Codes of Practice.\n2. Consult with workers on health and safety matters.\n3. Provide a risk-based approach to hazard management.\n4. Train workers to work safely.\n5. Report and investigate all incidents.\n6. Support worker mental health and wellbeing.\n\nSigned: _____________ (Director)\nDate: _____________\nReview: annually." },
  { id: "emergency-plan", cat: "Policy", title: "Emergency response plan", desc: "Pre-formatted plan with evacuation routes, wardens, first-aid, and notifications.", size: "30 KB", body: "EMERGENCY RESPONSE PLAN\n\nSite: ____________\nAddress: ____________\nDate: ____________\n\n1. WARDEN(S)\nChief warden: ____________  mobile: ____________\nDeputy: ____________  mobile: ____________\n\n2. ASSEMBLY POINT\nPrimary: ____________\nSecondary: ____________\n\n3. EVACUATION ROUTE\nMap on back page. Muster, headcount, report missing.\n\n4. FIRST AID\nOfficer: ____________  qualification: HLTAID011/009\nKit location: ____________\n\n5. EMERGENCY NUMBERS\nEmergency 000\nSite manager: ____________\nRegulator notification (if notifiable): see state contacts.\n\n6. SCENARIOS\n- Fire: raise alarm, evacuate, call 000.\n- Medical: first aid, call 000 if serious.\n- Confined space: stop work, rescue per permit.\n- Spill: contain, follow SDS, call 000 if major.\n\nSigned: ____________  Role: ____________" },
];

export const STATE_GUIDES = {
  NSW: { name: "New South Wales", regulator: "SafeWork NSW", url: "safework.nsw.gov.au", phone: "13 10 50",
    notifiable_hours: 48, act: "Work Health and Safety Act 2011 (NSW)",
    max_fine_individual: "A$3,991,500 (category 1)", max_fine_corporate: "A$10,855,000 (category 1)",
    icons: ["High-rise construction", "Residential trade"], 
    key_facts: ["Industrial manslaughter laws introduced 2024", "Psychosocial hazard regulation since 2022", "Tier-1 builders increasingly require SafeWork-aligned SWMS"], 
    recent_fines: ["Concreting co fined A$375k after worker fall (2024)", "Tier-2 builder fined A$2.2m after truss collapse (2023)"] },
  VIC: { name: "Victoria", regulator: "WorkSafe Victoria", url: "worksafe.vic.gov.au", phone: "1800 136 089",
    notifiable_hours: 48, act: "Occupational Health and Safety Act 2004 (VIC)",
    max_fine_individual: "A$3,787,470 (reckless endangerment)", max_fine_corporate: "A$18,937,350 (reckless endangerment)",
    icons: ["Mixed-use construction", "Renovations"],
    key_facts: ["Workplace manslaughter since 2020", "OHS Act distinct from national WHS model", "Psychosocial changes from mid-2025"],
    recent_fines: ["Builder fined A$1.25m after worker crushed (2024)", "Plumber fined A$180k after trench collapse (2023)"] },
  QLD: { name: "Queensland", regulator: "Workplace Health and Safety Queensland", url: "worksafe.qld.gov.au", phone: "1300 362 128",
    notifiable_hours: 48, act: "Work Health and Safety Act 2011 (QLD)",
    max_fine_individual: "A$3,895,190 (cat 1)", max_fine_corporate: "A$10,865,340 (cat 1)",
    icons: ["Tropical construction", "Resources & mining trades"],
    key_facts: ["Industrial manslaughter since 2017 (first in Australia)", "Multiple recent prosecutions", "Heat-stress regs updated 2024"],
    recent_fines: ["Contractor fined A$3m after industrial manslaughter conviction (2023)", "Electrical firm fined A$900k after shock incident (2024)"] },
  WA: { name: "Western Australia", regulator: "WorkSafe WA", url: "commerce.wa.gov.au/worksafe", phone: "1300 307 877",
    notifiable_hours: 48, act: "Work Health and Safety Act 2020 (WA)",
    max_fine_individual: "A$682,500 (cat 1)", max_fine_corporate: "A$3,415,000 (cat 1)",
    icons: ["Resources & infrastructure", "Remote sites"],
    key_facts: ["Harmonised with model WHS Act in 2022 (late adopter)", "Industrial manslaughter since 2022", "Remote-work regs distinct"],
    recent_fines: ["Civil contractor fined A$950k after fall (2023)", "Mine contractor fined A$2.8m (2022)"] },
  SA: { name: "South Australia", regulator: "SafeWork SA", url: "safework.sa.gov.au", phone: "1300 365 255",
    notifiable_hours: 48, act: "Work Health and Safety Act 2012 (SA)",
    max_fine_individual: "A$3,991,500 (cat 1)", max_fine_corporate: "A$10,855,000 (cat 1)",
    icons: ["Wine & food processing", "Residential"],
    key_facts: ["Industrial manslaughter since 2024", "Strong tier-1 audit culture", "Updated codes of practice 2024"],
    recent_fines: ["Builder fined A$350k after scaffold collapse (2024)"] },
  TAS: { name: "Tasmania", regulator: "WorkSafe Tasmania", url: "worksafe.tas.gov.au", phone: "1300 366 322",
    notifiable_hours: 48, act: "Work Health and Safety Act 2012 (TAS)",
    max_fine_individual: "A$3,991,500 (cat 1)", max_fine_corporate: "A$10,855,000 (cat 1)",
    icons: ["Timber & forestry", "Residential & renovation"],
    key_facts: ["Industrial manslaughter bill progressing 2025", "Smaller operations — simpler enforcement"],
    recent_fines: ["Forestry contractor fined A$250k (2023)"] },
  NT: { name: "Northern Territory", regulator: "NT WorkSafe", url: "worksafe.nt.gov.au", phone: "1800 019 115",
    notifiable_hours: 48, act: "Work Health and Safety (National Uniform Legislation) Act 2011 (NT)",
    max_fine_individual: "A$3,991,500", max_fine_corporate: "A$10,855,000",
    icons: ["Remote & tropical", "Indigenous communities work"],
    key_facts: ["Heat stress controls critical", "Cultural sensitivity training encouraged", "Small regulator — direct relationships possible"],
    recent_fines: ["Civil contractor fined A$400k (2023)"] },
  ACT: { name: "Australian Capital Territory", regulator: "WorkSafe ACT", url: "worksafe.act.gov.au", phone: "13 22 81",
    notifiable_hours: 48, act: "Work Health and Safety Act 2011 (ACT)",
    max_fine_individual: "A$3,991,500", max_fine_corporate: "A$10,855,000",
    icons: ["Government & commercial", "Residential"],
    key_facts: ["Industrial manslaughter since 2021", "High compliance expectation from federal/ACT government clients"],
    recent_fines: ["Commercial builder fined A$800k (2023)"] },
};

export const INTEGRATIONS = [
  { id: "xero", name: "Xero", cat: "Accounting", desc: "Sync invoice-ready data and job costs into Xero.", status: "Available", logo: "💼" },
  { id: "myob", name: "MYOB", cat: "Accounting", desc: "Worker licences linked to payroll in MYOB AccountRight.", status: "Available", logo: "📒" },
  { id: "servicem8", name: "ServiceM8", cat: "Jobs", desc: "Job & SWMS sync — generate a SWMS directly from a ServiceM8 job.", status: "Available", logo: "🔧" },
  { id: "tradify", name: "Tradify", cat: "Jobs", desc: "Worker data, job costing, and invoice sync.", status: "Available", logo: "🛠️" },
  { id: "simpro", name: "Simpro", cat: "Jobs", desc: "Enterprise job management integration — licences, plant, and SWMS.", status: "Beta", logo: "📐" },
  { id: "deputy", name: "Deputy", cat: "Rostering", desc: "Block rostering when a licence is expired or a SWMS not signed.", status: "Available", logo: "📅" },
  { id: "googledrive", name: "Google Drive", cat: "Storage", desc: "Mirror SWMS and documents into your Drive folder automatically.", status: "Available", logo: "☁️" },
  { id: "dropbox", name: "Dropbox", cat: "Storage", desc: "Auto-sync signed SWMS and incident evidence to Dropbox.", status: "Beta", logo: "📦" },
  { id: "slack", name: "Slack", cat: "Comms", desc: "Licence expiry + incident alerts in your #safety channel.", status: "Available", logo: "💬" },
  { id: "msteams", name: "Microsoft Teams", cat: "Comms", desc: "Safety alerts and toolbox talk reminders in Teams.", status: "Available", logo: "🟦" },
  { id: "zapier", name: "Zapier", cat: "Automation", desc: "800+ apps via triggers: new incident, licence expiring, worker onboarded.", status: "Available", logo: "⚡" },
  { id: "quickbooks", name: "QuickBooks", cat: "Accounting", desc: "Compliance cost tracking and job-cost P&L roll-up.", status: "Planned", logo: "📊" },
];

export const COMPETITORS = [
  { name: "SafeTradie", tagline: "AI-powered, built for Aussie trades", price: "A$150–400/mo", rating: 4.9,
    features: { swms_ai: true, incident_register: true, licence_tracking: true, toolbox_talks: true, risk_register: true, plant_register: true, substances: true, inspections: true, academy: true, worker_pwa: true, partner_portal: true, tradecheck: true, ai_insights: true, australian_legislation: true, price_per_user: 30 } },
  { name: "HammerTech", tagline: "Enterprise-first tier-1 builder tool", price: "from A$15k/yr", rating: 4.2,
    features: { swms_ai: false, incident_register: true, licence_tracking: true, toolbox_talks: true, risk_register: true, plant_register: true, substances: true, inspections: true, academy: false, worker_pwa: true, partner_portal: false, tradecheck: false, ai_insights: false, australian_legislation: true, price_per_user: 400 } },
  { name: "HazardCo", tagline: "Safety systems for subbies", price: "A$99/mo per user", rating: 4.3,
    features: { swms_ai: false, incident_register: true, licence_tracking: true, toolbox_talks: true, risk_register: true, plant_register: false, substances: false, inspections: true, academy: false, worker_pwa: false, partner_portal: false, tradecheck: false, ai_insights: false, australian_legislation: true, price_per_user: 99 } },
  { name: "SiteDocs", tagline: "Canadian-built, widely used", price: "US$200/mo", rating: 4.5,
    features: { swms_ai: false, incident_register: true, licence_tracking: true, toolbox_talks: true, risk_register: true, plant_register: true, substances: false, inspections: true, academy: false, worker_pwa: true, partner_portal: false, tradecheck: false, ai_insights: false, australian_legislation: false, price_per_user: 80 } },
  { name: "Donesafe", tagline: "Generic EHS platform", price: "custom (A$20k+/yr)", rating: 4.0,
    features: { swms_ai: false, incident_register: true, licence_tracking: true, toolbox_talks: false, risk_register: true, plant_register: true, substances: true, inspections: true, academy: false, worker_pwa: false, partner_portal: false, tradecheck: false, ai_insights: false, australian_legislation: true, price_per_user: 500 } },
];

// Fine calculator data — realistic (rough) Australian civil penalty ranges
export const FINE_CATEGORIES = {
  cat_1: { label: "Category 1 (reckless endangerment)", individual_min: 300000, individual_max: 3991500, corporate_min: 1500000, corporate_max: 10855000, jail: "up to 5 years" },
  cat_2: { label: "Category 2 (serious breach)", individual_min: 50000, individual_max: 798300, corporate_min: 250000, corporate_max: 3991500, jail: null },
  cat_3: { label: "Category 3 (failure to comply)", individual_min: 0, individual_max: 79830, corporate_min: 0, corporate_max: 399150, jail: null },
  notifiable_fail: { label: "Failure to notify notifiable incident", individual_min: 10000, individual_max: 79830, corporate_min: 50000, corporate_max: 399150, jail: null },
  no_swms: { label: "No SWMS for high-risk work", individual_min: 6000, individual_max: 39915, corporate_min: 30000, corporate_max: 199575, jail: null },
  licence_breach: { label: "Unlicensed high-risk work", individual_min: 8000, individual_max: 39915, corporate_min: 40000, corporate_max: 199575, jail: null },
};
