/**
 * Article reader — /resources/:industry/:slug
 * On first request, the body is generated by Claude and cached on the doc.
 */
import { useEffect, useState } from "react";
import { Link, useParams, useNavigate } from "react-router-dom";
import axios from "axios";
import { MarketingNav, MarketingFooter } from "@/components/marketing/Layout";
import { Button } from "@/components/ui/button";
import { ArrowLeft, Sparkle } from "@phosphor-icons/react";

const API_URL = process.env.REACT_APP_BACKEND_URL;

const ACCENT = {
  trades: "#FFCC00", hospitality: "#E87722", transport: "#0DC4B5",
  healthcare: "#2196A6", retail: "#A855F7",
};

export default function ResourceArticle() {
  const { industry, slug } = useParams();
  const navigate = useNavigate();
  const [article, setArticle] = useState(null);
  const [loading, setLoading] = useState(true);
  const accent = ACCENT[industry] || "#FFCC00";

  useEffect(() => {
    setLoading(true);
    axios.get(`${API_URL}/api/resources/articles/${slug}?industry=${industry}`)
      .then((r) => setArticle(r.data))
      .catch(() => setArticle(null))
      .finally(() => setLoading(false));
  }, [industry, slug]);

  return (
    <div className="bg-background text-ink" data-testid="resources-article">
      <MarketingNav />
      <article className="max-w-3xl mx-auto px-6 py-12 lg:py-20">
        <button onClick={() => navigate(`/resources?industry=${industry}`)} className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-ink mb-8" data-testid="article-back">
          <ArrowLeft size={16} /> Back to resources
        </button>

        {loading ? (
          <div className="py-20 text-center" data-testid="article-loading">
            <Sparkle size={32} weight="fill" className="mx-auto animate-pulse" style={{ color: accent }} />
            <div className="font-display font-black text-xl mt-4">Generating with Claude…</div>
            <p className="text-sm text-muted-foreground mt-2 max-w-md mx-auto">
              First read of this article triggers a fresh AI generation tailored to current Australian {industry} compliance. Subsequent visits are instant.
            </p>
          </div>
        ) : !article ? (
          <div className="py-20 text-center">
            <div className="font-display font-black text-2xl">Article not found.</div>
            <Link to="/resources" className="underline text-sm mt-3 inline-block">Back to all resources →</Link>
          </div>
        ) : (
          <>
            <div className="label-eyebrow" style={{ color: accent }}>/ {industry} · {article.tags}</div>
            <h1 className="font-display text-4xl lg:text-6xl font-black tracking-tighter mt-3" data-testid="article-title">{article.title}</h1>
            <div className="text-sm text-muted-foreground mt-4 flex items-center gap-2">
              <Sparkle size={14} weight="fill" style={{ color: accent }} /> Written by SafeBase AI · {article.view_count} views
            </div>
            <div className="mt-8 prose prose-zinc max-w-none" data-testid="article-body">
              {(article.body_md || "").split("\n").map((line, i) => {
                if (line.startsWith("## ")) return <h2 key={i} className="font-display font-black text-2xl mt-8 mb-3 tracking-tight">{line.slice(3)}</h2>;
                if (line.startsWith("# ")) return <h1 key={i} className="font-display font-black text-3xl mt-8 mb-3">{line.slice(2)}</h1>;
                if (line.match(/^\s*-\s/)) return <li key={i} className="ml-5 list-disc text-base">{line.replace(/^\s*-\s/, "")}</li>;
                if (line.startsWith("**") && line.endsWith("**") && line.length > 4) return <p key={i} className="font-bold text-base my-3">{line.slice(2, -2)}</p>;
                if (line.trim() === "") return <div key={i} className="h-3" />;
                return <p key={i} className="text-base leading-relaxed my-3">{line}</p>;
              })}
            </div>
            <div className="mt-12 bg-warning border-2 border-ink p-6" data-testid="article-cta">
              <div className="label-eyebrow">/ Want this without the homework?</div>
              <h3 className="font-display font-black text-2xl mt-2">SafeBase tracks all of this for you.</h3>
              <p className="text-sm mt-2">Per-industry templates, AI-generated documents, expiry alerts, audit-ready evidence. 14-day free trial.</p>
              <Link to={`/register?industry=${industry}`}>
                <Button className="mt-4 btn-sharp h-12 bg-ink text-white hover:bg-authority" data-testid="article-cta-btn">
                  Start free trial → {industry}
                </Button>
              </Link>
            </div>
          </>
        )}
      </article>
      <MarketingFooter />
    </div>
  );
}
