/**
 * SWMS Generator — 7-step wizard with live preview pane
 * Spec: Phase 1 of SafeTradie Document Library rebuild
 * - Left: stepped form (Steps 1-7)
 * - Right: live preview mirroring the PDF layout
 * - Legal notice banner always visible at top
 */
import { useEffect, useMemo, useState } from "react";
import { useParams, useNavigate } from "react-router-dom";
import api from "@/lib/api";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Checkbox } from "@/components/ui/checkbox";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  Sparkle, FloppyDisk, ArrowLeft, ArrowRight, Warning, CheckCircle,
  Trash, Plus, Copy, FilePdf, PaperPlaneTilt, Hand,
} from "@phosphor-icons/react";
import { toast } from "sonner";
import SwmsPreview from "./SwmsPreview";

const STEPS = [
  { key: "business", label: "1. Business & Job" },
  { key: "trade", label: "2. Trade & Activity" },
  { key: "hrcw", label: "3. HRCW Categories" },
  { key: "rows", label: "4. Tasks / Hazards / Controls" },
  { key: "compliance", label: "5. Compliance & Review" },
  { key: "equipment", label: "6. Equipment / PPE / Training" },
  { key: "signoff", label: "7. Generate & Sign" },
];

const SITE_TYPES = [
  "Residential — house or townhouse construction",
  "Residential — renovation or alteration",
  "Commercial — new construction",
  "Commercial — renovation or fitout",
  "Industrial",
  "Civil / infrastructure",
  "Telecommunications",
  "Other",
];

const DURATIONS = ["Less than 1 day", "1-3 days", "4-7 days", "1-2 weeks", "2-4 weeks", "More than 1 month"];
const STATES = ["NSW", "VIC", "QLD", "WA", "SA", "TAS", "NT", "ACT"];

const HIERARCHY_COLOURS = {
  eliminate: "#065f46", substitute: "#0d9488", isolate: "#1d4ed8",
  engineer: "#1e3a8a", admin: "#d97706", ppe: "#b91c1c",
};

function LegalNoticeBanner() {
  return (
    <div className="bg-warning/20 border-2 border-ink p-3 text-xs leading-relaxed" data-testid="swms-legal-notice">
      <strong className="block label-eyebrow text-ink mb-1">LEGAL NOTICE</strong>
      A SWMS generated by SafeTradie must be reviewed and tailored to your specific site before work
      commences. A generic SWMS does not meet legal requirements unless reviewed on site and amended
      for actual hazards, layout, weather, equipment and workers.
      <strong> Work must stop immediately if HRCW is not being carried out in accordance with this SWMS.</strong>
    </div>
  );
}

export default function SwmsGenerator() {
  const { swms_id } = useParams();
  const nav = useNavigate();
  const [ref, setRef] = useState(null);
  const [workersRoster, setWorkersRoster] = useState([]);
  const [step, setStep] = useState(0);
  const [saving, setSaving] = useState(false);
  const [busyAi, setBusyAi] = useState(false);
  const [form, setForm] = useState({
    company_name: "", abn: "", business_address: "", business_phone: "",
    business_email: "", work_activity: "", site_location: "", site_state: "NSW",
    site_type: "", start_date: "", duration: "",
    works_manager_name: "", works_manager_phone: "",
    has_principal_contractor: false, pc_business: "", pc_contact: "",
    pc_phone: "", pc_swms_date: "",
    trade: "electrician", activity: "",
    workers: [],
    hrcw_codes: [],
    rows: [],
    compliance_responsible: "", compliance_measures: "",
    review_responsible: "", review_measures: "",
    review_date: "", consulted_workers: [], hsr_name: "",
    plant: [], ppe: [], training: [],
    emergency_contact: "", nearest_hospital: "", assembly_point: "",
    first_aider: "",
  });

  // Load reference data + profile + workers
  useEffect(() => {
    (async () => {
      try {
        const [refRes, profRes, wRes] = await Promise.all([
          api.get("/swms/reference"),
          api.get("/auth/me").catch(() => ({ data: {} })),
          api.get("/workers").catch(() => ({ data: [] })),
        ]);
        setRef(refRes.data);
        setWorkersRoster(wRes.data || []);
        // Auto-fill business from profile
        const p = profRes.data || {};
        setForm((f) => ({
          ...f,
          company_name: f.company_name || p.company_name || "",
          business_phone: f.business_phone || p.phone || "",
          business_email: f.business_email || p.email || "",
        }));
      } catch (e) {
        toast.error("Failed to load reference data");
      }
    })();
  }, []);

  // Load existing SWMS if editing
  useEffect(() => {
    if (!swms_id) return;
    api.get(`/swms/${swms_id}`).then((r) => {
      setForm((f) => ({ ...f, ...r.data }));
      setRef((cur) => cur); // keep reference
    }).catch(() => toast.error("Could not load SWMS"));
  }, [swms_id]);

  const patch = (k, v) => setForm((f) => ({ ...f, [k]: v }));
  const patchMany = (obj) => setForm((f) => ({ ...f, ...obj }));

  const tradeDef = ref?.trades?.[form.trade];
  const activities = tradeDef?.activities || [];

  // Compliance-measure defaults
  useEffect(() => {
    if (!form.compliance_measures && form.company_name) {
      patch("compliance_measures",
        `${form.company_name} WHS policies and procedures, general and site-specific induction training, ` +
        "toolbox talk before commencing HRCW, SWMS provided to and discussed with all workers before " +
        "work commences, ongoing supervision by experienced site supervisor.");
    }
    if (!form.review_measures) {
      patch("review_measures",
        "SWMS control measures will be reviewed and revised if necessary when: work tasks or methods " +
        "change; an unexpected hazard is identified; new information about a hazard becomes available; " +
        "a notifiable incident occurs; or control measures are found to be inadequate.");
    }
    // eslint-disable-next-line
  }, [form.company_name]);

  // When trade/activity changes, auto-suggest HRCW
  const suggestHrcw = async () => {
    try {
      const r = await api.post("/swms/ai/suggest-hrcw", { trade: form.trade, activity: form.activity });
      const codes = Array.from(new Set([...(form.hrcw_codes || []), ...(r.data?.hrcw_codes || [])]));
      patch("hrcw_codes", codes);
      toast.success(`${r.data?.hrcw_codes?.length || 0} HRCW categories pre-selected`);
    } catch {
      toast.error("HRCW suggestion failed");
    }
  };

  const suggestRows = async () => {
    setBusyAi(true);
    try {
      const r = await api.post("/swms/ai/suggest-rows", {
        trade: form.trade, activity: form.activity,
        hrcw_codes: form.hrcw_codes, site_state: form.site_state,
        rows: form.rows,
      });
      const newRows = r.data?.rows || [];
      patch("rows", [...(form.rows || []), ...newRows]);
      if (r.data?.fallback) {
        toast.warning("AI unavailable — using safe defaults. Please review and tailor.");
      } else {
        toast.success(`${newRows.length} task rows drafted`);
      }
    } catch (e) {
      toast.error("AI draft failed");
    }
    setBusyAi(false);
  };

  const save = async ({ navigate = false } = {}) => {
    setSaving(true);
    try {
      let res;
      if (form.swms_id) {
        res = await api.patch(`/swms/${form.swms_id}`, form);
      } else {
        res = await api.post("/swms", form);
      }
      setForm((f) => ({ ...f, ...res.data }));
      toast.success(`Saved — ${res.data.reference}`);
      if (navigate) nav("/dashboard/swms");
    } catch (e) {
      toast.error(e?.response?.data?.detail || "Save failed");
    }
    setSaving(false);
  };

  const next = () => setStep((s) => Math.min(STEPS.length - 1, s + 1));
  const prev = () => setStep((s) => Math.max(0, s - 1));

  // Step-specific content renderers
  const stepContent = () => {
    switch (STEPS[step].key) {
      case "business": return <StepBusiness form={form} patch={patch} />;
      case "trade": return <StepTrade form={form} patch={patch} ref={ref}
                                      workersRoster={workersRoster} onAfter={suggestHrcw} />;
      case "hrcw": return <StepHrcw form={form} patch={patch} ref={ref}
                                    onSuggest={suggestHrcw} />;
      case "rows": return <StepRows form={form} patch={patch} ref={ref}
                                    onAiSuggest={suggestRows} busyAi={busyAi}
                                    workersRoster={workersRoster} />;
      case "compliance": return <StepCompliance form={form} patch={patch} workersRoster={workersRoster} />;
      case "equipment": return <StepEquipment form={form} patch={patch} ref={ref} />;
      case "signoff": return <StepSignoff form={form} patch={patch} save={save}
                                          onDone={() => nav("/dashboard/swms")} />;
      default: return null;
    }
  };

  if (!ref) return <div className="p-8 text-sm text-muted-foreground">Loading reference data…</div>;

  return (
    <div className="space-y-4" data-testid="swms-generator">
      <div className="border-b-2 border-ink pb-3 flex items-end justify-between flex-wrap gap-2">
        <div>
          <div className="label-eyebrow">/ Documents · SWMS Generator</div>
          <h1 className="font-display text-3xl md:text-4xl font-black tracking-tighter mt-1">
            {form.swms_id ? `Edit ${form.reference}` : "New SWMS"}
          </h1>
        </div>
        <div className="flex gap-2">
          <Button variant="outline" className="btn-sharp border-ink" onClick={() => save()} disabled={saving} data-testid="swms-save">
            <FloppyDisk className="mr-2" />{saving ? "Saving…" : "Save draft"}
          </Button>
        </div>
      </div>

      <LegalNoticeBanner />

      <div className="grid grid-cols-12 gap-4">
        {/* LEFT — Wizard (7 cols) */}
        <div className="col-span-12 lg:col-span-7 bg-background border border-border p-4">
          <div className="flex flex-wrap gap-1 mb-4 border-b border-border pb-3">
            {STEPS.map((s, i) => (
              <button
                key={s.key}
                onClick={() => setStep(i)}
                className={`text-[10px] px-2 py-1 font-bold tracking-widest ${i === step ? "bg-ink text-warning" : "bg-muted text-ink hover:bg-warning"}`}
                data-testid={`swms-step-${i}`}
              >
                {s.label}
              </button>
            ))}
          </div>
          <div className="min-h-[50vh]">{stepContent()}</div>
          <div className="flex justify-between mt-6 pt-4 border-t border-border gap-2">
            <Button variant="outline" className="btn-sharp border-ink" onClick={prev} disabled={step === 0} data-testid="swms-prev">
              <ArrowLeft className="mr-2" />Back
            </Button>
            {step < STEPS.length - 1 ? (
              <Button className="btn-sharp bg-ink text-white hover:bg-authority" onClick={next} data-testid="swms-next">
                Next <ArrowRight className="ml-2" />
              </Button>
            ) : (
              <Button className="btn-sharp bg-warning text-ink hover:bg-yellow-400" onClick={() => save({ navigate: false })} data-testid="swms-finish">
                Finish <CheckCircle className="ml-2" weight="fill" />
              </Button>
            )}
          </div>
        </div>

        {/* RIGHT — Live Preview (5 cols) */}
        <div className="col-span-12 lg:col-span-5">
          <div className="sticky top-4">
            <div className="label-eyebrow mb-2">Live preview</div>
            <SwmsPreview doc={form} hrcwCatalog={ref.hrcw_categories} />
          </div>
        </div>
      </div>
    </div>
  );
}

// =========================================================
// STEP COMPONENTS
// =========================================================
function Section({ title, hint, children, testid }) {
  return (
    <div className="space-y-3" data-testid={testid}>
      <div>
        <h3 className="font-display font-black text-lg tracking-tighter">{title}</h3>
        {hint && <p className="text-xs text-muted-foreground mt-1">{hint}</p>}
      </div>
      {children}
    </div>
  );
}

function Field({ label, children, span = 1 }) {
  return (
    <div className={`col-span-${span}`}>
      <Label className="label-eyebrow">{label}</Label>
      <div className="mt-1">{children}</div>
    </div>
  );
}

function StepBusiness({ form, patch }) {
  return (
    <Section title="Business and job details" hint="Auto-filled from your profile — review and edit." testid="swms-step-business">
      <div className="grid grid-cols-2 gap-3">
        <Field label="Company / Business Name"><Input value={form.company_name} onChange={(e) => patch("company_name", e.target.value)} className="h-10 rounded-none border-ink" data-testid="swms-company" /></Field>
        <Field label="ABN"><Input value={form.abn} onChange={(e) => patch("abn", e.target.value)} className="h-10 rounded-none border-ink" /></Field>
        <Field label="Business address" span={2}><Input value={form.business_address} onChange={(e) => patch("business_address", e.target.value)} className="h-10 rounded-none border-ink" /></Field>
        <Field label="Business phone"><Input value={form.business_phone} onChange={(e) => patch("business_phone", e.target.value)} className="h-10 rounded-none border-ink" /></Field>
        <Field label="Business email"><Input value={form.business_email} onChange={(e) => patch("business_email", e.target.value)} className="h-10 rounded-none border-ink" /></Field>
        <Field label="Work activity (what is the work being done?)" span={2}>
          <Input value={form.work_activity} onChange={(e) => patch("work_activity", e.target.value)}
                 placeholder="e.g. Solar installation on tiled roof"
                 className="h-10 rounded-none border-ink" data-testid="swms-work-activity" />
        </Field>
        <Field label="Site location (full address)" span={2}>
          <Input value={form.site_location} onChange={(e) => patch("site_location", e.target.value)} className="h-10 rounded-none border-ink" data-testid="swms-site-location" />
        </Field>
        <Field label="Site state">
          <Select value={form.site_state} onValueChange={(v) => patch("site_state", v)}>
            <SelectTrigger className="h-10 rounded-none border-ink" data-testid="swms-site-state"><SelectValue /></SelectTrigger>
            <SelectContent>{STATES.map((s) => <SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent>
          </Select>
        </Field>
        <Field label="Site type">
          <Select value={form.site_type} onValueChange={(v) => patch("site_type", v)}>
            <SelectTrigger className="h-10 rounded-none border-ink"><SelectValue placeholder="Select…" /></SelectTrigger>
            <SelectContent>{SITE_TYPES.map((s) => <SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent>
          </Select>
        </Field>
        <Field label="Estimated start date"><Input type="date" value={form.start_date} onChange={(e) => patch("start_date", e.target.value)} className="h-10 rounded-none border-ink" /></Field>
        <Field label="Estimated duration">
          <Select value={form.duration} onValueChange={(v) => patch("duration", v)}>
            <SelectTrigger className="h-10 rounded-none border-ink"><SelectValue placeholder="Select…" /></SelectTrigger>
            <SelectContent>{DURATIONS.map((s) => <SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent>
          </Select>
        </Field>
        <Field label="Works Manager / Supervisor"><Input value={form.works_manager_name} onChange={(e) => patch("works_manager_name", e.target.value)} className="h-10 rounded-none border-ink" /></Field>
        <Field label="Works Manager phone"><Input value={form.works_manager_phone} onChange={(e) => patch("works_manager_phone", e.target.value)} className="h-10 rounded-none border-ink" /></Field>
      </div>
      <div className="border border-border p-3 space-y-3 mt-4">
        <label className="flex items-center gap-2 text-sm font-bold">
          <Checkbox checked={form.has_principal_contractor} onCheckedChange={(v) => patch("has_principal_contractor", !!v)} data-testid="swms-has-pc" />
          Principal Contractor on this project?
        </label>
        {form.has_principal_contractor && (
          <div className="grid grid-cols-2 gap-3">
            <Field label="PC business name"><Input value={form.pc_business} onChange={(e) => patch("pc_business", e.target.value)} className="h-10 rounded-none border-ink" /></Field>
            <Field label="PC contact name"><Input value={form.pc_contact} onChange={(e) => patch("pc_contact", e.target.value)} className="h-10 rounded-none border-ink" /></Field>
            <Field label="PC phone"><Input value={form.pc_phone} onChange={(e) => patch("pc_phone", e.target.value)} className="h-10 rounded-none border-ink" /></Field>
            <Field label="Date SWMS provided to PC"><Input type="date" value={form.pc_swms_date} onChange={(e) => patch("pc_swms_date", e.target.value)} className="h-10 rounded-none border-ink" /></Field>
          </div>
        )}
      </div>
    </Section>
  );
}

function StepTrade({ form, patch, ref, workersRoster }) {
  const trades = Object.entries(ref?.trades || {});
  const activities = ref?.trades?.[form.trade]?.activities || [];
  const toggleWorker = (w) => {
    const existing = form.workers.find((x) => x.worker_id === w.worker_id || x.name === w.name);
    if (existing) {
      patch("workers", form.workers.filter((x) => x !== existing));
    } else {
      patch("workers", [...form.workers, { worker_id: w.worker_id, name: w.name, role: w.role, signed: false }]);
    }
  };
  return (
    <Section title="Trade and activity" hint="Choose your trade and the specific activity. We'll pre-select the likely HRCW categories." testid="swms-step-trade">
      <div className="grid grid-cols-2 gap-3">
        <Field label="Primary trade">
          <Select value={form.trade} onValueChange={(v) => { patch("trade", v); patch("activity", ""); }}>
            <SelectTrigger className="h-10 rounded-none border-ink" data-testid="swms-trade"><SelectValue /></SelectTrigger>
            <SelectContent>{trades.map(([k, v]) => <SelectItem key={k} value={k}>{v.label}</SelectItem>)}</SelectContent>
          </Select>
        </Field>
        <Field label="Specific activity">
          <Select value={form.activity} onValueChange={(v) => patch("activity", v)}>
            <SelectTrigger className="h-10 rounded-none border-ink" data-testid="swms-activity"><SelectValue placeholder="Select…" /></SelectTrigger>
            <SelectContent>{activities.map((a) => <SelectItem key={a} value={a}>{a}</SelectItem>)}</SelectContent>
          </Select>
        </Field>
      </div>
      <div className="border border-border p-3 mt-3">
        <div className="label-eyebrow mb-2">Workers on this job ({form.workers.length} selected)</div>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-1 max-h-64 overflow-y-auto" data-testid="swms-workers">
          {workersRoster.map((w) => (
            <label key={w.worker_id} className="flex items-center gap-2 p-2 text-sm hover:bg-muted cursor-pointer">
              <Checkbox
                checked={form.workers.some((x) => x.worker_id === w.worker_id)}
                onCheckedChange={() => toggleWorker(w)}
              />
              <span className="font-bold">{w.name}</span>
              <span className="text-xs text-muted-foreground">{w.role}{w.trade ? ` · ${w.trade}` : ""}</span>
            </label>
          ))}
          {workersRoster.length === 0 && <div className="text-xs text-muted-foreground p-2">No workers on file — add some under Workers.</div>}
        </div>
      </div>
    </Section>
  );
}

function StepHrcw({ form, patch, ref, onSuggest }) {
  const cats = ref?.hrcw_categories || [];
  const toggle = (code) => {
    const has = form.hrcw_codes.includes(code);
    patch("hrcw_codes", has ? form.hrcw_codes.filter((c) => c !== code) : [...form.hrcw_codes, code]);
  };
  const none = form.hrcw_codes.length === 0;
  return (
    <Section
      title="High Risk Construction Work identification"
      hint="Tick all that apply. We pre-select the likely categories based on your trade & activity — review carefully."
      testid="swms-step-hrcw"
    >
      <Button variant="outline" className="btn-sharp border-ink" onClick={onSuggest} data-testid="swms-hrcw-suggest">
        <Sparkle className="mr-2" weight="fill" />Re-run AI pre-selection
      </Button>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-2 mt-3" data-testid="swms-hrcw-grid">
        {cats.map((c) => (
          <label key={c.code} className={`flex items-start gap-2 p-2 border text-sm cursor-pointer ${form.hrcw_codes.includes(c.code) ? "bg-warning/30 border-ink font-bold" : "border-border hover:bg-muted"}`} data-testid={`hrcw-${c.code}`}>
            <Checkbox checked={form.hrcw_codes.includes(c.code)} onCheckedChange={() => toggle(c.code)} className="mt-0.5" />
            <span>{c.label}</span>
          </label>
        ))}
      </div>
      {none && (
        <div className="bg-amber-50 border-2 border-amber-600 p-3 text-sm mt-3" data-testid="swms-no-hrcw">
          <Warning weight="fill" className="inline mr-2 text-amber-700" />
          If none of these apply, a SWMS may not be legally required. You must still manage risks —
          consider completing a Job Safety Analysis (JSA) instead.
        </div>
      )}
      {!none && (
        <div className="bg-emerald-50 border-2 border-emerald-600 p-3 text-sm mt-3" data-testid="swms-ok-hrcw">
          <CheckCircle weight="fill" className="inline mr-2 text-emerald-700" />
          <strong>SWMS is legally required.</strong> Continuing to generate your SWMS.
        </div>
      )}
      {form.site_state === "VIC" && (
        <div className="bg-blue-50 border-2 border-blue-600 p-3 text-xs mt-3">
          <strong>Victoria:</strong> In VIC this work is governed by the OHS Regulations 2017.
          WorkSafe Victoria recommends the SWMS focuses only on the HRCW activities identified
          above and does not include non-HRCW tasks or risk matrices.
        </div>
      )}
    </Section>
  );
}

function StepRows({ form, patch, ref, onAiSuggest, busyAi }) {
  const hierarchy = ref?.hierarchy_levels || ["eliminate", "substitute", "isolate", "engineer", "admin", "ppe"];
  const rows = form.rows || [];
  const setRows = (arr) => patch("rows", arr);

  const addRow = () => setRows([...rows, { row_id: `row_${Date.now()}`, task: "", hazards: [""], controls: [{ level: "admin", text: "" }], hrcw_code: null }]);
  const removeRow = (i) => setRows(rows.filter((_, x) => x !== i));
  const moveRow = (i, dir) => {
    const arr = [...rows];
    const j = i + dir;
    if (j < 0 || j >= arr.length) return;
    [arr[i], arr[j]] = [arr[j], arr[i]];
    setRows(arr);
  };
  const patchRow = (i, k, v) => {
    const arr = [...rows]; arr[i] = { ...arr[i], [k]: v }; setRows(arr);
  };
  const addHazard = (i) => patchRow(i, "hazards", [...(rows[i].hazards || []), ""]);
  const patchHazard = (i, j, v) => {
    const arr = [...(rows[i].hazards || [])]; arr[j] = v; patchRow(i, "hazards", arr);
  };
  const removeHazard = (i, j) => patchRow(i, "hazards", rows[i].hazards.filter((_, x) => x !== j));
  const addControl = (i) => patchRow(i, "controls", [...(rows[i].controls || []), { level: "admin", text: "" }]);
  const patchControl = (i, j, k, v) => {
    const arr = [...(rows[i].controls || [])]; arr[j] = { ...arr[j], [k]: v }; patchRow(i, "controls", arr);
  };
  const removeControl = (i, j) => patchRow(i, "controls", rows[i].controls.filter((_, x) => x !== j));
  const duplicate = (i) => {
    const arr = [...rows];
    arr.splice(i + 1, 0, { ...JSON.parse(JSON.stringify(arr[i])), row_id: `row_${Date.now()}` });
    setRows(arr);
  };

  return (
    <Section title="Tasks, hazards and controls"
             hint="The heart of the SWMS. Let AI draft rows, then edit each cell. Reorder with the up/down arrows."
             testid="swms-step-rows">
      <div className="flex gap-2 flex-wrap">
        <Button className="btn-sharp bg-warning text-ink hover:bg-yellow-400" onClick={onAiSuggest} disabled={busyAi} data-testid="swms-rows-ai">
          <Sparkle className="mr-2" weight="fill" />{busyAi ? "Drafting with AI…" : "AI draft rows"}
        </Button>
        <Button variant="outline" className="btn-sharp border-ink" onClick={addRow} data-testid="swms-rows-add">
          <Plus className="mr-1" />Add row
        </Button>
      </div>

      <div className="space-y-3 mt-3" data-testid="swms-rows-list">
        {rows.length === 0 && (
          <div className="bg-muted border border-border p-4 text-sm text-muted-foreground text-center">
            No rows yet — click "AI draft rows" to get started, or add a row manually.
          </div>
        )}
        {rows.map((r, i) => (
          <div key={r.row_id || i} className="border-2 border-ink p-3 space-y-3" data-testid={`swms-row-${i}`}>
            <div className="flex items-start gap-2">
              <div className="flex-1">
                <Label className="label-eyebrow">Task {i + 1}</Label>
                <Input value={r.task} onChange={(e) => patchRow(i, "task", e.target.value)} className="h-10 rounded-none border-ink mt-1" data-testid={`swms-row-task-${i}`} />
              </div>
              <div>
                <Label className="label-eyebrow">Linked HRCW</Label>
                <Select value={r.hrcw_code || "__none__"} onValueChange={(v) => patchRow(i, "hrcw_code", v === "__none__" ? null : v)}>
                  <SelectTrigger className="h-10 rounded-none border-ink mt-1 w-40"><SelectValue /></SelectTrigger>
                  <SelectContent>
                    <SelectItem value="__none__">— None —</SelectItem>
                    {(form.hrcw_codes || []).map((c) => {
                      const cat = ref.hrcw_categories.find((x) => x.code === c);
                      return <SelectItem key={c} value={c}>{cat?.label?.slice(0, 40)}</SelectItem>;
                    })}
                  </SelectContent>
                </Select>
              </div>
              <div className="flex gap-1 mt-6">
                <button onClick={() => moveRow(i, -1)} className="p-1 text-xs hover:bg-muted" title="Move up">↑</button>
                <button onClick={() => moveRow(i, 1)} className="p-1 text-xs hover:bg-muted" title="Move down">↓</button>
                <button onClick={() => duplicate(i)} className="p-1 text-xs hover:bg-muted" title="Duplicate"><Copy size={14} /></button>
                <button onClick={() => removeRow(i)} className="p-1 text-xs text-destructive hover:bg-destructive/10" title="Delete"><Trash size={14} /></button>
              </div>
            </div>

            <div>
              <Label className="label-eyebrow">Hazards</Label>
              <div className="space-y-2 mt-1">
                {(r.hazards || []).map((h, j) => (
                  <div key={j} className="flex gap-1" data-testid={`swms-hazard-${i}-${j}`}>
                    <Input value={h} onChange={(e) => patchHazard(i, j, e.target.value)} className="h-9 rounded-none border-ink flex-1" />
                    <button onClick={() => removeHazard(i, j)} className="text-destructive text-xs px-2"><Trash size={14} /></button>
                  </div>
                ))}
              </div>
              <button onClick={() => addHazard(i)} className="text-xs underline mt-1">+ Add hazard</button>
            </div>

            <div>
              <Label className="label-eyebrow">Control measures (top-down hierarchy)</Label>
              <div className="space-y-2 mt-1">
                {(r.controls || []).map((c, j) => (
                  <div key={j} className="flex gap-1" data-testid={`swms-control-${i}-${j}`}>
                    <Select value={c.level} onValueChange={(v) => patchControl(i, j, "level", v)}>
                      <SelectTrigger className="h-9 w-32 rounded-none border-ink"><SelectValue /></SelectTrigger>
                      <SelectContent>
                        {hierarchy.map((h) => <SelectItem key={h} value={h}>{h.toUpperCase()}</SelectItem>)}
                      </SelectContent>
                    </Select>
                    <Input value={c.text} onChange={(e) => patchControl(i, j, "text", e.target.value)} className="h-9 rounded-none border-ink flex-1" />
                    <button onClick={() => removeControl(i, j)} className="text-destructive text-xs px-2"><Trash size={14} /></button>
                  </div>
                ))}
              </div>
              <button onClick={() => addControl(i)} className="text-xs underline mt-1">+ Add control</button>
            </div>
          </div>
        ))}
      </div>
    </Section>
  );
}

function StepCompliance({ form, patch, workersRoster }) {
  const names = workersRoster.map((w) => w.name);
  return (
    <Section title="Compliance and review" hint="Who's accountable, what the compliance arrangement is, and when this SWMS will be reviewed." testid="swms-step-compliance">
      <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
        <Field label="Person responsible for compliance">
          <Input list="worker-names" value={form.compliance_responsible} onChange={(e) => patch("compliance_responsible", e.target.value)} className="h-10 rounded-none border-ink" />
          <datalist id="worker-names">{names.map((n) => <option key={n} value={n} />)}</datalist>
        </Field>
        <Field label="Person responsible for review">
          <Input list="worker-names" value={form.review_responsible} onChange={(e) => patch("review_responsible", e.target.value)} className="h-10 rounded-none border-ink" />
        </Field>
      </div>
      <Field label="Measures in place to ensure compliance">
        <Textarea rows={3} value={form.compliance_measures} onChange={(e) => patch("compliance_measures", e.target.value)} className="rounded-none border-ink" data-testid="swms-compliance-measures" />
      </Field>
      <Field label="How will SWMS controls be reviewed?">
        <Textarea rows={3} value={form.review_measures} onChange={(e) => patch("review_measures", e.target.value)} className="rounded-none border-ink" />
      </Field>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
        <Field label="Review date"><Input type="date" value={form.review_date} onChange={(e) => patch("review_date", e.target.value)} className="h-10 rounded-none border-ink" /></Field>
        <Field label="HSR consulted (if applicable)"><Input value={form.hsr_name} onChange={(e) => patch("hsr_name", e.target.value)} className="h-10 rounded-none border-ink" /></Field>
      </div>
    </Section>
  );
}

function StepEquipment({ form, patch, ref }) {
  const regulator = ref?.state_regulators?.[form.site_state] || {};
  const togglePpe = (item) => {
    const has = (form.ppe || []).includes(item);
    patch("ppe", has ? form.ppe.filter((x) => x !== item) : [...(form.ppe || []), item]);
  };
  const toggleTraining = (item) => {
    const has = (form.training || []).includes(item);
    patch("training", has ? form.training.filter((x) => x !== item) : [...(form.training || []), item]);
  };
  return (
    <Section title="Equipment, PPE and training" hint="What workers will use, wear, and need to be qualified for." testid="swms-step-equipment">
      <div>
        <div className="label-eyebrow mb-2">PPE Required ({form.ppe.length})</div>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-1" data-testid="swms-ppe-grid">
          {ref.standard_ppe.map((p) => (
            <label key={p} className="flex items-center gap-2 p-2 text-sm hover:bg-muted cursor-pointer">
              <Checkbox checked={(form.ppe || []).includes(p)} onCheckedChange={() => togglePpe(p)} />
              {p}
            </label>
          ))}
        </div>
      </div>
      <div>
        <div className="label-eyebrow mb-2">Training / Licences ({form.training.length})</div>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-1" data-testid="swms-training-grid">
          {ref.standard_training.map((p) => (
            <label key={p} className="flex items-center gap-2 p-2 text-sm hover:bg-muted cursor-pointer">
              <Checkbox checked={(form.training || []).includes(p)} onCheckedChange={() => toggleTraining(p)} />
              {p}
            </label>
          ))}
        </div>
      </div>
      <div className="border border-border p-3 space-y-2 mt-3 bg-blue-50">
        <div className="font-display font-black text-lg">Emergency procedures</div>
        <div className="grid grid-cols-2 gap-3">
          <Field label="Emergency contact"><Input value={form.emergency_contact} onChange={(e) => patch("emergency_contact", e.target.value)} className="h-10 rounded-none border-ink" /></Field>
          <Field label="Nearest hospital"><Input value={form.nearest_hospital} onChange={(e) => patch("nearest_hospital", e.target.value)} className="h-10 rounded-none border-ink" /></Field>
          <Field label="Assembly point"><Input value={form.assembly_point} onChange={(e) => patch("assembly_point", e.target.value)} className="h-10 rounded-none border-ink" /></Field>
          <Field label="First aider on site"><Input value={form.first_aider} onChange={(e) => patch("first_aider", e.target.value)} className="h-10 rounded-none border-ink" /></Field>
        </div>
        <div className="text-xs bg-ink text-white p-2 mt-2 font-bold">
          {form.site_state} — State Regulator: {regulator.name} — <a href={`tel:${regulator.phone}`} className="text-warning underline">{regulator.phone}</a> · Emergency services: 000
        </div>
      </div>
    </Section>
  );
}

function StepSignoff({ form, patch, save, onDone }) {
  const [sigWorker, setSigWorker] = useState("");
  const [sigText, setSigText] = useState("");
  const [busy, setBusy] = useState(false);

  const signInPerson = async () => {
    if (!form.swms_id) { toast.error("Save the SWMS first"); return; }
    if (!sigWorker) { toast.error("Select worker"); return; }
    if (!sigText) { toast.error("Type initials or full name as signature"); return; }
    setBusy(true);
    try {
      await api.post(`/swms/${form.swms_id}/sign`, {
        name: sigWorker, signature_data: sigText, signed_via: "in_person",
      });
      const updated = await api.get(`/swms/${form.swms_id}`);
      patch("workers", updated.data.workers);
      patch("status", updated.data.status);
      toast.success(`${sigWorker} signed`);
      setSigWorker(""); setSigText("");
    } catch { toast.error("Sign failed"); }
    setBusy(false);
  };

  const sendSmsLinks = async () => {
    if (!form.swms_id) { toast.error("Save the SWMS first"); return; }
    try {
      const r = await api.post(`/swms/${form.swms_id}/send-sign-links`);
      toast.success(`${r.data.sent} sign link${r.data.sent === 1 ? "" : "s"} generated (SMS delivery MOCKED — see Alerts for tokens)`);
    } catch { toast.error("Failed to generate links"); }
  };

  const downloadPdf = () => {
    if (!form.swms_id) { toast.error("Save the SWMS first"); return; }
    const token = localStorage.getItem("st_token");
    const backend = process.env.REACT_APP_BACKEND_URL;
    fetch(`${backend}/api/swms/${form.swms_id}/pdf`, { headers: { Authorization: `Bearer ${token}` } })
      .then((r) => r.blob()).then((b) => {
        const url = URL.createObjectURL(b);
        const a = document.createElement("a");
        a.href = url; a.download = `${form.reference || "swms"}.pdf`; a.click();
        URL.revokeObjectURL(url);
        toast.success("PDF downloaded");
      }).catch(() => toast.error("PDF download failed"));
  };

  return (
    <Section title="Generate and sign" hint="Save, download the PDF, and collect worker sign-offs." testid="swms-step-signoff">
      <div className="bg-ink text-white p-4">
        <div className="label-eyebrow text-warning">Status</div>
        <div className="font-display text-2xl font-black tracking-tighter mt-1">{(form.status || "draft").toUpperCase().replace("_", " ")}</div>
        <div className="text-xs text-white/60 mt-1">{form.reference || "Save to assign reference"}</div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-3 mt-3">
        <Button className="btn-sharp bg-warning text-ink hover:bg-yellow-400 h-14" onClick={() => save()} disabled={busy} data-testid="swms-signoff-save">
          <FloppyDisk className="mr-2" weight="fill" />Save
        </Button>
        <Button variant="outline" className="btn-sharp border-ink h-14" onClick={downloadPdf} data-testid="swms-signoff-pdf">
          <FilePdf className="mr-2" weight="fill" />Download PDF
        </Button>
        <Button variant="outline" className="btn-sharp border-ink h-14" onClick={sendSmsLinks} data-testid="swms-signoff-sms">
          <PaperPlaneTilt className="mr-2" weight="fill" />Send SMS sign links
        </Button>
      </div>

      <div className="border-2 border-ink p-4 mt-4 space-y-3">
        <div className="font-display font-black text-lg">In-person sign-off</div>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
          <div>
            <Label className="label-eyebrow">Worker</Label>
            <Select value={sigWorker} onValueChange={setSigWorker}>
              <SelectTrigger className="h-10 rounded-none border-ink mt-1" data-testid="swms-sig-worker"><SelectValue placeholder="Select…" /></SelectTrigger>
              <SelectContent>{form.workers.filter((w) => !w.signed).map((w) => <SelectItem key={w.name} value={w.name}>{w.name}</SelectItem>)}</SelectContent>
            </Select>
          </div>
          <div className="md:col-span-2">
            <Label className="label-eyebrow">Type signature (full name or initials)</Label>
            <Input value={sigText} onChange={(e) => setSigText(e.target.value)} className="h-10 rounded-none border-ink mt-1" data-testid="swms-sig-input" />
          </div>
        </div>
        <Button className="btn-sharp bg-ink text-white hover:bg-authority" onClick={signInPerson} disabled={busy} data-testid="swms-sig-submit">
          <Hand className="mr-2" weight="fill" />Sign
        </Button>
      </div>

      {form.workers?.length > 0 && (
        <div className="border border-border mt-3">
          <div className="label-eyebrow p-3 border-b border-border">Sign-off status</div>
          <div className="divide-y divide-border" data-testid="swms-signed-status">
            {form.workers.map((w) => (
              <div key={w.name} className="flex items-center justify-between p-3 text-sm">
                <span className="font-bold">{w.name}</span>
                {w.signed ? (
                  <span className="text-emerald-700 flex items-center gap-2 text-xs font-bold tracking-widest">
                    <CheckCircle weight="fill" /> SIGNED · {w.signed_at?.slice(0, 10)} · {w.signed_via?.toUpperCase()}
                  </span>
                ) : (
                  <span className="text-amber-600 text-xs font-bold tracking-widest">AWAITING</span>
                )}
              </div>
            ))}
          </div>
        </div>
      )}
    </Section>
  );
}
