/**
 * downloadAsWord — generates a Microsoft-Word-compatible .doc file from a
 * plain-text template body. The output is HTML wrapped with the Office
 * namespace, which Word, LibreOffice and Pages all open as a Word document.
 *
 * Why .doc + HTML rather than a real .docx (OOXML zip): a real .docx requires
 * a ZIP library on the client. The HTML-as-Word approach is dependency-free,
 * produces a file with the Word document icon, and opens cleanly in every
 * mainstream word processor.
 */
export function downloadAsWord(filename, title, bodyText) {
  const lines = (bodyText || "").split("\n");
  const htmlBody = lines
    .map((line) => {
      const trimmed = line.trim();
      if (!trimmed) return "<p>&nbsp;</p>";
      // Render lines that look like section headers (ALL CAPS, short) as <h2>
      if (trimmed.length < 80 && trimmed === trimmed.toUpperCase() && /[A-Z]/.test(trimmed)) {
        return `<h2 style="font-family:Calibri,Arial,sans-serif;font-size:14pt;margin:14pt 0 6pt 0;color:#0A0A0A;">${escapeHtml(trimmed)}</h2>`;
      }
      return `<p style="font-family:Calibri,Arial,sans-serif;font-size:11pt;margin:4pt 0;line-height:1.5;">${escapeHtml(line)}</p>`;
    })
    .join("\n");

  const html = `<!DOCTYPE html>
<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns="http://www.w3.org/TR/REC-html40">
<head>
<meta charset="utf-8">
<title>${escapeHtml(title)}</title>
<!--[if gte mso 9]><xml>
  <w:WordDocument><w:View>Print</w:View><w:Zoom>100</w:Zoom></w:WordDocument>
</xml><![endif]-->
<style>
  body { font-family: Calibri, Arial, sans-serif; font-size: 11pt; color: #0A0A0A; }
  h1 { font-size: 18pt; margin: 0 0 8pt 0; color: #0A0A0A; }
  h2 { font-size: 14pt; margin: 14pt 0 6pt 0; color: #0A0A0A; }
  .footer { margin-top: 24pt; padding-top: 8pt; border-top: 1px solid #ccc; font-size: 9pt; color: #666; }
</style>
</head>
<body>
<h1>${escapeHtml(title)}</h1>
${htmlBody}
<p class="footer">Generated by SafeBase · Free Australian WHS &amp; compliance templates · safebase.com.au</p>
</body>
</html>`;

  // Word recognises both application/msword and the Office mime — msword is
  // the most universally compatible.
  const blob = new Blob(["\ufeff", html], { type: "application/msword" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename.endsWith(".doc") ? filename : `${filename}.doc`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1500);
}

function escapeHtml(s) {
  return String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}
